

INSERT INTO ref_state (code, label) VALUES ('01', 'Johor'); 
INSERT INTO ref_state (code, label) VALUES ('02', 'Kedah'); 
INSERT INTO ref_state (code, label) VALUES ('03', 'Kelantan'); 
INSERT INTO ref_state (code, label) VALUES ('04', 'Melaka'); 
INSERT INTO ref_state (code, label) VALUES ('05', 'Negeri Sembilan'); 
INSERT INTO ref_state (code, label) VALUES ('06', 'Pahang'); 
INSERT INTO ref_state (code, label) VALUES ('07', 'Pulau Pinang'); 
INSERT INTO ref_state (code, label) VALUES ('08', 'Perak'); 
INSERT INTO ref_state (code, label) VALUES ('09', 'Perlis'); 
INSERT INTO ref_state (code, label) VALUES ('10', 'Selangor'); 
INSERT INTO ref_state (code, label) VALUES ('11', 'Terengganu'); 
INSERT INTO ref_state (code, label) VALUES ('12', 'Sabah'); 
INSERT INTO ref_state (code, label) VALUES ('13', 'Sarawak'); 
INSERT INTO ref_state (code, label) VALUES ('14', 'W.Persekutuan (KL)'); 
INSERT INTO ref_state (code, label) VALUES ('15', 'W.Persekutuan (Labuan)'); 
INSERT INTO ref_state (code, label) VALUES ('16', 'W.Persekutuan (Putrajaya)'); 


INSERT INTO ref_city (code, label) VALUES ('0101', 'Asahan'); 
INSERT INTO ref_city (code, label) VALUES ('0102', 'Ayer Baloi'); 
INSERT INTO ref_city (code, label) VALUES ('0103', 'Ayer Hitam'); 
INSERT INTO ref_city (code, label) VALUES ('0104', 'Bakri'); 
INSERT INTO ref_city (code, label) VALUES ('0105', 'Batu Anam'); 
INSERT INTO ref_city (code, label) VALUES ('0106', 'Batu Pahat'); 
INSERT INTO ref_city (code, label) VALUES ('0107', 'Bekok'); 
INSERT INTO ref_city (code, label) VALUES ('0108', 'Benut'); 
INSERT INTO ref_city (code, label) VALUES ('0109', 'Bukit Gambir'); 
INSERT INTO ref_city (code, label) VALUES ('0110', 'Bukit Pasir'); 
INSERT INTO ref_city (code, label) VALUES ('0111', 'Chaah'); 
INSERT INTO ref_city (code, label) VALUES ('0112', 'Endau'); 
INSERT INTO ref_city (code, label) VALUES ('0113', 'Gelang Patah'); 
INSERT INTO ref_city (code, label) VALUES ('0114', 'Gemas'); 
INSERT INTO ref_city (code, label) VALUES ('0115', 'Gerisek'); 
INSERT INTO ref_city (code, label) VALUES ('0116', 'Gugusan Taib Andak'); 
INSERT INTO ref_city (code, label) VALUES ('0117', 'Jementah'); 
INSERT INTO ref_city (code, label) VALUES ('0118', 'Johor Bahru'); 
INSERT INTO ref_city (code, label) VALUES ('0119', 'Kahang'); 
INSERT INTO ref_city (code, label) VALUES ('0120', 'Kluang'); 
INSERT INTO ref_city (code, label) VALUES ('0121', 'Kampung Kenangan Tun Dr Ismail'); 
INSERT INTO ref_city (code, label) VALUES ('0122', 'Kota Tinggi'); 
INSERT INTO ref_city (code, label) VALUES ('0123', 'Kukup'); 
INSERT INTO ref_city (code, label) VALUES ('0124', 'Kulai'); 
INSERT INTO ref_city (code, label) VALUES ('0125', 'Labis'); 
INSERT INTO ref_city (code, label) VALUES ('0126', 'Layang-layang'); 
INSERT INTO ref_city (code, label) VALUES ('0127', 'Masai'); 
INSERT INTO ref_city (code, label) VALUES ('0128', 'Mersing'); 
INSERT INTO ref_city (code, label) VALUES ('0129', 'Muar'); 
INSERT INTO ref_city (code, label) VALUES ('0130', 'Pagoh'); 
INSERT INTO ref_city (code, label) VALUES ('0131', 'Paloh'); 
INSERT INTO ref_city (code, label) VALUES ('0132', 'Panchor'); 
INSERT INTO ref_city (code, label) VALUES ('0133', 'Parit Jawa'); 
INSERT INTO ref_city (code, label) VALUES ('0134', 'Parit Raja'); 
INSERT INTO ref_city (code, label) VALUES ('0135', 'Parit Sulong'); 
INSERT INTO ref_city (code, label) VALUES ('0136', 'Pasir Gudang'); 
INSERT INTO ref_city (code, label) VALUES ('0137', 'Pekan Nenas'); 
INSERT INTO ref_city (code, label) VALUES ('0138', 'Pengerang'); 
INSERT INTO ref_city (code, label) VALUES ('0139', 'Pontian'); 
INSERT INTO ref_city (code, label) VALUES ('0140', 'Rengit'); 
INSERT INTO ref_city (code, label) VALUES ('0141', 'Segamat'); 
INSERT INTO ref_city (code, label) VALUES ('0142', 'Skudai'); 
INSERT INTO ref_city (code, label) VALUES ('0143', 'Semerah'); 
INSERT INTO ref_city (code, label) VALUES ('0144', 'Senai'); 
INSERT INTO ref_city (code, label) VALUES ('0145', 'Senggarang'); 
INSERT INTO ref_city (code, label) VALUES ('0146', 'Simpang Renggam'); 
INSERT INTO ref_city (code, label) VALUES ('0147', 'Sungai Mati'); 
INSERT INTO ref_city (code, label) VALUES ('0148', 'Tangkak'); 
INSERT INTO ref_city (code, label) VALUES ('0149', 'Ulu Tiram'); 
INSERT INTO ref_city (code, label) VALUES ('0150', 'Yong Peng'); 
INSERT INTO ref_city (code, label) VALUES ('0151', 'Sagil'); 
INSERT INTO ref_city (code, label) VALUES ('0157', 'Bukit Kepong'); 
INSERT INTO ref_city (code, label) VALUES ('0177', 'Lenga'); 
INSERT INTO ref_city (code, label) VALUES ('0191', 'Sungai Balang'); 
INSERT INTO ref_city (code, label) VALUES ('0192', 'Gemas Baru'); 
INSERT INTO ref_city (code, label) VALUES ('0193', 'Renggam'); 
INSERT INTO ref_city (code, label) VALUES ('0194', 'Bandar Penawar'); 
INSERT INTO ref_city (code, label) VALUES ('0195', 'Ledang'); 
INSERT INTO ref_city (code, label) VALUES ('0196', 'Nusajaya'); 
INSERT INTO ref_city (code, label) VALUES ('0197', 'Kulaijaya'); 
INSERT INTO ref_city (code, label) VALUES ('0198', 'Kangkar Pulai'); 
INSERT INTO ref_city (code, label) VALUES ('0199', 'Bakri Baru'); 
INSERT INTO ref_city (code, label) VALUES ('0201', 'Alor Setar'); 
INSERT INTO ref_city (code, label) VALUES ('0202', 'Baling'); 
INSERT INTO ref_city (code, label) VALUES ('0203', 'Bandar Baharu'); 
INSERT INTO ref_city (code, label) VALUES ('0204', 'Bedong'); 
INSERT INTO ref_city (code, label) VALUES ('0205', 'Gurun'); 
INSERT INTO ref_city (code, label) VALUES ('0206', 'Jitra'); 
INSERT INTO ref_city (code, label) VALUES ('0207', 'Karangan'); 
INSERT INTO ref_city (code, label) VALUES ('0208', 'Kepala Batas'); 
INSERT INTO ref_city (code, label) VALUES ('0209', 'Kodiang'); 
INSERT INTO ref_city (code, label) VALUES ('0210', 'Kota Kuala Muda'); 
INSERT INTO ref_city (code, label) VALUES ('0211', 'Kuala Kedah'); 
INSERT INTO ref_city (code, label) VALUES ('0212', 'Kuala Ketil'); 
INSERT INTO ref_city (code, label) VALUES ('0213', 'Kuala Nerang'); 
INSERT INTO ref_city (code, label) VALUES ('0214', 'Kulim'); 
INSERT INTO ref_city (code, label) VALUES ('0215', 'Kupang'); 
INSERT INTO ref_city (code, label) VALUES ('0216', 'Langgar'); 
INSERT INTO ref_city (code, label) VALUES ('0217', 'Langkawi'); 
INSERT INTO ref_city (code, label) VALUES ('0218', 'Lunas'); 
INSERT INTO ref_city (code, label) VALUES ('0219', 'Merbok'); 
INSERT INTO ref_city (code, label) VALUES ('0220', 'Padang Serai'); 
INSERT INTO ref_city (code, label) VALUES ('0221', 'Pendang'); 
INSERT INTO ref_city (code, label) VALUES ('0222', 'Pokok Sena'); 
INSERT INTO ref_city (code, label) VALUES ('0223', 'Serdang'); 
INSERT INTO ref_city (code, label) VALUES ('0224', 'Sik'); 
INSERT INTO ref_city (code, label) VALUES ('0225', 'Sungai Petani'); 
INSERT INTO ref_city (code, label) VALUES ('0226', 'Yan'); 
INSERT INTO ref_city (code, label) VALUES ('0234', 'Changloon'); 
INSERT INTO ref_city (code, label) VALUES ('0281', 'Sungai Bakap'); 
INSERT INTO ref_city (code, label) VALUES ('0282', 'Bukit Kayu Hitam'); 
INSERT INTO ref_city (code, label) VALUES ('0283', 'Ayer Hitam'); 
INSERT INTO ref_city (code, label) VALUES ('0284', 'Simpang Empat'); 
INSERT INTO ref_city (code, label) VALUES ('0285', 'Kota Sarang Semut'); 
INSERT INTO ref_city (code, label) VALUES ('0286', 'Jeniang'); 
INSERT INTO ref_city (code, label) VALUES ('0287', 'Kuala Pegang'); 
INSERT INTO ref_city (code, label) VALUES ('0288', 'Sintok'); 
INSERT INTO ref_city (code, label) VALUES ('0301', 'Ayer Lanas'); 
INSERT INTO ref_city (code, label) VALUES ('0302', 'Bachok'); 
INSERT INTO ref_city (code, label) VALUES ('0303', 'Cherang Ruku'); 
INSERT INTO ref_city (code, label) VALUES ('0304', 'Dabong'); 
INSERT INTO ref_city (code, label) VALUES ('0305', 'Gua Musang'); 
INSERT INTO ref_city (code, label) VALUES ('0306', 'Jeli'); 
INSERT INTO ref_city (code, label) VALUES ('0307', 'Kem Desa Pahlawan'); 
INSERT INTO ref_city (code, label) VALUES ('0308', 'Ketereh'); 
INSERT INTO ref_city (code, label) VALUES ('0309', 'Kota Bharu'); 
INSERT INTO ref_city (code, label) VALUES ('0310', 'Kuala Krai'); 
INSERT INTO ref_city (code, label) VALUES ('0311', 'Machang'); 
INSERT INTO ref_city (code, label) VALUES ('0312', 'Melor'); 
INSERT INTO ref_city (code, label) VALUES ('0313', 'Pasir Mas'); 
INSERT INTO ref_city (code, label) VALUES ('0314', 'Pasir Puteh'); 
INSERT INTO ref_city (code, label) VALUES ('0315', 'Pulai Chondong'); 
INSERT INTO ref_city (code, label) VALUES ('0316', 'Rantau Panjang'); 
INSERT INTO ref_city (code, label) VALUES ('0317', 'Tanah Merah'); 
INSERT INTO ref_city (code, label) VALUES ('0318', 'Temangan'); 
INSERT INTO ref_city (code, label) VALUES ('0319', 'Tumpat'); 
INSERT INTO ref_city (code, label) VALUES ('0320', 'Wakaf Bharu'); 
INSERT INTO ref_city (code, label) VALUES ('0321', 'Selising'); 
INSERT INTO ref_city (code, label) VALUES ('0322', 'Kuala Balah'); 
INSERT INTO ref_city (code, label) VALUES ('0323', 'Kubang Kerian'); 
INSERT INTO ref_city (code, label) VALUES ('0401', 'Alor Gajah'); 
INSERT INTO ref_city (code, label) VALUES ('0402', 'Asahan'); 
INSERT INTO ref_city (code, label) VALUES ('0403', 'Batang Melaka'); 
INSERT INTO ref_city (code, label) VALUES ('0404', 'Bemban'); 
INSERT INTO ref_city (code, label) VALUES ('0405', 'Durian Tunggal'); 
INSERT INTO ref_city (code, label) VALUES ('0406', 'Gemas'); 
INSERT INTO ref_city (code, label) VALUES ('0407', 'Jasin'); 
INSERT INTO ref_city (code, label) VALUES ('0408', 'Kuala Sungai Baru'); 
INSERT INTO ref_city (code, label) VALUES ('0409', 'Lubok China'); 
INSERT INTO ref_city (code, label) VALUES ('0410', 'Masjid Tanah'); 
INSERT INTO ref_city (code, label) VALUES ('0411', 'Melaka'); 
INSERT INTO ref_city (code, label) VALUES ('0412', 'Merlimau'); 
INSERT INTO ref_city (code, label) VALUES ('0413', 'Sungai Rambai'); 
INSERT INTO ref_city (code, label) VALUES ('0414', 'Sungai Udang'); 
INSERT INTO ref_city (code, label) VALUES ('0415', 'Tampin'); 
INSERT INTO ref_city (code, label) VALUES ('0416', 'Tanjong Kling'); 
INSERT INTO ref_city (code, label) VALUES ('0417', 'Selandar'); 
INSERT INTO ref_city (code, label) VALUES ('0418', 'Bukit Katil'); 
INSERT INTO ref_city (code, label) VALUES ('0419', 'Ayer Keroh'); 
INSERT INTO ref_city (code, label) VALUES ('0421', 'Kem Trendak'); 
INSERT INTO ref_city (code, label) VALUES ('0501', 'Asahan'); 
INSERT INTO ref_city (code, label) VALUES ('0502', 'Bahau'); 
INSERT INTO ref_city (code, label) VALUES ('0503', 'Batang Melaka'); 
INSERT INTO ref_city (code, label) VALUES ('0504', 'Batu Kikir'); 
INSERT INTO ref_city (code, label) VALUES ('0505', 'Durian Tipus'); 
INSERT INTO ref_city (code, label) VALUES ('0506', 'Gemas'); 
INSERT INTO ref_city (code, label) VALUES ('0507', 'Gemencheh'); 
INSERT INTO ref_city (code, label) VALUES ('0508', 'Johol'); 
INSERT INTO ref_city (code, label) VALUES ('0509', 'Kota'); 
INSERT INTO ref_city (code, label) VALUES ('0510', 'Kuala Klawang'); 
INSERT INTO ref_city (code, label) VALUES ('0511', 'Kuala Pilah'); 
INSERT INTO ref_city (code, label) VALUES ('0512', 'Labu'); 
INSERT INTO ref_city (code, label) VALUES ('0513', 'Lenggeng'); 
INSERT INTO ref_city (code, label) VALUES ('0514', 'Linggi'); 
INSERT INTO ref_city (code, label) VALUES ('0515', 'Lubok China'); 
INSERT INTO ref_city (code, label) VALUES ('0516', 'Mantin'); 
INSERT INTO ref_city (code, label) VALUES ('0517', 'Nilai'); 
INSERT INTO ref_city (code, label) VALUES ('0518', 'Pasir Panjang'); 
INSERT INTO ref_city (code, label) VALUES ('0519', 'Pedas'); 
INSERT INTO ref_city (code, label) VALUES ('0520', 'Port Dickson'); 
INSERT INTO ref_city (code, label) VALUES ('0521', 'Rantau'); 
INSERT INTO ref_city (code, label) VALUES ('0522', 'Rembau'); 
INSERT INTO ref_city (code, label) VALUES ('0523', 'Rompin'); 
INSERT INTO ref_city (code, label) VALUES ('0524', 'Seliau'); 
INSERT INTO ref_city (code, label) VALUES ('0525', 'Seremban'); 
INSERT INTO ref_city (code, label) VALUES ('0526', 'Seri Menanti'); 
INSERT INTO ref_city (code, label) VALUES ('0527', 'Si Rusa'); 
INSERT INTO ref_city (code, label) VALUES ('0528', 'Siliau'); 
INSERT INTO ref_city (code, label) VALUES ('0529', 'Simpang Pertang'); 
INSERT INTO ref_city (code, label) VALUES ('0530', 'Sungai Gadut'); 
INSERT INTO ref_city (code, label) VALUES ('0531', 'Tampin'); 
INSERT INTO ref_city (code, label) VALUES ('0532', 'Tanjong Ipoh'); 
INSERT INTO ref_city (code, label) VALUES ('0533', 'Titi'); 
INSERT INTO ref_city (code, label) VALUES ('0534', 'Bukit Pelandok'); 
INSERT INTO ref_city (code, label) VALUES ('0535', 'Chuah'); 
INSERT INTO ref_city (code, label) VALUES ('0536', 'Lukut'); 
INSERT INTO ref_city (code, label) VALUES ('0537', 'Teluk Kemang'); 
INSERT INTO ref_city (code, label) VALUES ('0538', 'Pengkalan Kempas'); 
INSERT INTO ref_city (code, label) VALUES ('0539', 'Jelebu'); 
INSERT INTO ref_city (code, label) VALUES ('0540', 'Bandar Seri Jempol'); 
INSERT INTO ref_city (code, label) VALUES ('0541', 'Juasseh'); 
INSERT INTO ref_city (code, label) VALUES ('0542', 'Bandar Baru Jempol'); 
INSERT INTO ref_city (code, label) VALUES ('0543', 'Bandar Baru Enstek'); 
INSERT INTO ref_city (code, label) VALUES ('0544', 'Simpang Durian'); 
INSERT INTO ref_city (code, label) VALUES ('0545', 'Pusat Bandar Palong'); 
INSERT INTO ref_city (code, label) VALUES ('0546', 'Senawang'); 
INSERT INTO ref_city (code, label) VALUES ('0601', 'Bandar Jengka'); 
INSERT INTO ref_city (code, label) VALUES ('0602', 'Benta'); 
INSERT INTO ref_city (code, label) VALUES ('0603', 'Bentong'); 
INSERT INTO ref_city (code, label) VALUES ('0604', 'Beserah'); 
INSERT INTO ref_city (code, label) VALUES ('0605', 'Bukit Fraser'); 
INSERT INTO ref_city (code, label) VALUES ('0606', 'Chenor'); 
INSERT INTO ref_city (code, label) VALUES ('0607', 'Dong'); 
INSERT INTO ref_city (code, label) VALUES ('0608', 'Gambang'); 
INSERT INTO ref_city (code, label) VALUES ('0609', 'Genting Highlands'); 
INSERT INTO ref_city (code, label) VALUES ('0610', 'Jerantut'); 
INSERT INTO ref_city (code, label) VALUES ('0611', 'Karak'); 
INSERT INTO ref_city (code, label) VALUES ('0612', 'Kemayan'); 
INSERT INTO ref_city (code, label) VALUES ('0613', 'Kuala Lipis'); 
INSERT INTO ref_city (code, label) VALUES ('0614', 'Kuala Rompin'); 
INSERT INTO ref_city (code, label) VALUES ('0615', 'Kuantan'); 
INSERT INTO ref_city (code, label) VALUES ('0616', 'Lanchang'); 
INSERT INTO ref_city (code, label) VALUES ('0617', 'Lurah Bilut'); 
INSERT INTO ref_city (code, label) VALUES ('0618', 'Maran'); 
INSERT INTO ref_city (code, label) VALUES ('0619', 'Mengkarak'); 
INSERT INTO ref_city (code, label) VALUES ('0620', 'Mentakab'); 
INSERT INTO ref_city (code, label) VALUES ('0621', 'Mersing'); 
INSERT INTO ref_city (code, label) VALUES ('0622', 'Muadzam Shah'); 
INSERT INTO ref_city (code, label) VALUES ('0623', 'Padang Tengku'); 
INSERT INTO ref_city (code, label) VALUES ('0624', 'Pekan'); 
INSERT INTO ref_city (code, label) VALUES ('0625', 'Raub'); 
INSERT INTO ref_city (code, label) VALUES ('0626', 'Ringlet'); 
INSERT INTO ref_city (code, label) VALUES ('0627', 'Segamat'); 
INSERT INTO ref_city (code, label) VALUES ('0628', 'Sungai Lembing'); 
INSERT INTO ref_city (code, label) VALUES ('0629', 'Sungai Ruan'); 
INSERT INTO ref_city (code, label) VALUES ('0630', 'Tanah Rata'); 
INSERT INTO ref_city (code, label) VALUES ('0631', 'Temerloh'); 
INSERT INTO ref_city (code, label) VALUES ('0632', 'Triang'); 
INSERT INTO ref_city (code, label) VALUES ('0633', 'Bandar Tun Abdul Razak'); 
INSERT INTO ref_city (code, label) VALUES ('0634', 'Rompin'); 
INSERT INTO ref_city (code, label) VALUES ('0635', 'Cameron Highlands'); 
INSERT INTO ref_city (code, label) VALUES ('0636', 'Bandar Bera'); 
INSERT INTO ref_city (code, label) VALUES ('0637', 'Sega'); 
INSERT INTO ref_city (code, label) VALUES ('0638', 'Kuala Krau'); 
INSERT INTO ref_city (code, label) VALUES ('0639', 'Brinchang'); 
INSERT INTO ref_city (code, label) VALUES ('0640', 'Bukit Goh'); 
INSERT INTO ref_city (code, label) VALUES ('0641', 'Balok'); 
INSERT INTO ref_city (code, label) VALUES ('0642', 'Bukit Kuin'); 
INSERT INTO ref_city (code, label) VALUES ('0643', 'Chini'); 
INSERT INTO ref_city (code, label) VALUES ('0644', 'Damak'); 
INSERT INTO ref_city (code, label) VALUES ('0645', 'Sungai Koyan'); 
INSERT INTO ref_city (code, label) VALUES ('0701', 'Ayer Itam'); 
INSERT INTO ref_city (code, label) VALUES ('0702', 'Balik Pulau'); 
INSERT INTO ref_city (code, label) VALUES ('0703', 'Batu Ferringhi'); 
INSERT INTO ref_city (code, label) VALUES ('0704', 'Bayan Lepas'); 
INSERT INTO ref_city (code, label) VALUES ('0705', 'Bukit Mertajam'); 
INSERT INTO ref_city (code, label) VALUES ('0706', 'Butterworth'); 
INSERT INTO ref_city (code, label) VALUES ('0707', 'Gelugor'); 
INSERT INTO ref_city (code, label) VALUES ('0708', 'Georgetown'); 
INSERT INTO ref_city (code, label) VALUES ('0709', 'Kepala Batas'); 
INSERT INTO ref_city (code, label) VALUES ('0710', 'Nibong Tebal'); 
INSERT INTO ref_city (code, label) VALUES ('0711', 'Penaga'); 
INSERT INTO ref_city (code, label) VALUES ('0712', 'Penang Hill'); 
INSERT INTO ref_city (code, label) VALUES ('0713', 'Perai'); 
INSERT INTO ref_city (code, label) VALUES ('0714', 'Permatang Pauh'); 
INSERT INTO ref_city (code, label) VALUES ('0715', 'Pulau Pinang'); 
INSERT INTO ref_city (code, label) VALUES ('0716', 'Simpang Ampat'); 
INSERT INTO ref_city (code, label) VALUES ('0717', 'Sungai Jawi'); 
INSERT INTO ref_city (code, label) VALUES ('0718', 'Tanjong Bungah'); 
INSERT INTO ref_city (code, label) VALUES ('0719', 'Tasek Gelugor'); 
INSERT INTO ref_city (code, label) VALUES ('0720', 'Usm Pulau Pinang'); 
INSERT INTO ref_city (code, label) VALUES ('0721', 'Sungai Bakap'); 
INSERT INTO ref_city (code, label) VALUES ('0722', 'Jelutong'); 
INSERT INTO ref_city (code, label) VALUES ('0723', 'Batu Maung'); 
INSERT INTO ref_city (code, label) VALUES ('0724', 'Kubang Semang'); 
INSERT INTO ref_city (code, label) VALUES ('0801', 'Ayer Tawar'); 
INSERT INTO ref_city (code, label) VALUES ('0802', 'Bagan Datoh'); 
INSERT INTO ref_city (code, label) VALUES ('0803', 'Bagan Serai'); 
INSERT INTO ref_city (code, label) VALUES ('0804', 'Batu Gajah'); 
INSERT INTO ref_city (code, label) VALUES ('0805', 'Batu Kurau'); 
INSERT INTO ref_city (code, label) VALUES ('0806', 'Bruas'); 
INSERT INTO ref_city (code, label) VALUES ('0807', 'Bidor'); 
INSERT INTO ref_city (code, label) VALUES ('0808', 'Bota'); 
INSERT INTO ref_city (code, label) VALUES ('0809', 'Changkat Keruing'); 
INSERT INTO ref_city (code, label) VALUES ('0810', 'Chemor'); 
INSERT INTO ref_city (code, label) VALUES ('0811', 'Chenderiang'); 
INSERT INTO ref_city (code, label) VALUES ('0812', 'Chenderong Balai'); 
INSERT INTO ref_city (code, label) VALUES ('0813', 'Enggor'); 
INSERT INTO ref_city (code, label) VALUES ('0814', 'Gerik'); 
INSERT INTO ref_city (code, label) VALUES ('0815', 'Gopeng'); 
INSERT INTO ref_city (code, label) VALUES ('0816', 'Hutan Melintang'); 
INSERT INTO ref_city (code, label) VALUES ('0817', 'Klian Intan'); 
INSERT INTO ref_city (code, label) VALUES ('0818', 'Ipoh'); 
INSERT INTO ref_city (code, label) VALUES ('0819', 'Kampar'); 
INSERT INTO ref_city (code, label) VALUES ('0820', 'Kampung Gajah'); 
INSERT INTO ref_city (code, label) VALUES ('0821', 'Kampung Kepayang'); 
INSERT INTO ref_city (code, label) VALUES ('0822', 'Kamunting'); 
INSERT INTO ref_city (code, label) VALUES ('0823', 'Kuala Kangsar'); 
INSERT INTO ref_city (code, label) VALUES ('0824', 'Kuala Sepetang'); 
INSERT INTO ref_city (code, label) VALUES ('0825', 'Lahat'); 
INSERT INTO ref_city (code, label) VALUES ('0826', 'Langkap'); 
INSERT INTO ref_city (code, label) VALUES ('0827', 'Lenggong'); 
INSERT INTO ref_city (code, label) VALUES ('0828', 'Lumut'); 
INSERT INTO ref_city (code, label) VALUES ('0829', 'Malim Nawar'); 
INSERT INTO ref_city (code, label) VALUES ('0830', 'Mambang Di Awan'); 
INSERT INTO ref_city (code, label) VALUES ('0831', 'Manong'); 
INSERT INTO ref_city (code, label) VALUES ('0832', 'Matang'); 
INSERT INTO ref_city (code, label) VALUES ('0833', 'Menglembu'); 
INSERT INTO ref_city (code, label) VALUES ('0834', 'Padang Rengas'); 
INSERT INTO ref_city (code, label) VALUES ('0835', 'Pangkor'); 
INSERT INTO ref_city (code, label) VALUES ('0836', 'Pantai Remis'); 
INSERT INTO ref_city (code, label) VALUES ('0837', 'Parit'); 
INSERT INTO ref_city (code, label) VALUES ('0838', 'Parit Buntar'); 
INSERT INTO ref_city (code, label) VALUES ('0839', 'Pengkalan Hulu'); 
INSERT INTO ref_city (code, label) VALUES ('0840', 'Pusing'); 
INSERT INTO ref_city (code, label) VALUES ('0841', 'Sauk'); 
INSERT INTO ref_city (code, label) VALUES ('0842', 'Selama'); 
INSERT INTO ref_city (code, label) VALUES ('0843', 'Selekoh'); 
INSERT INTO ref_city (code, label) VALUES ('0844', 'Semanggol'); 
INSERT INTO ref_city (code, label) VALUES ('0845', 'Simpang'); 
INSERT INTO ref_city (code, label) VALUES ('0846', 'Simpang Ampat'); 
INSERT INTO ref_city (code, label) VALUES ('0847', 'Sitiawan'); 
INSERT INTO ref_city (code, label) VALUES ('0848', 'Slim River'); 
INSERT INTO ref_city (code, label) VALUES ('0849', 'Sungai Siput'); 
INSERT INTO ref_city (code, label) VALUES ('0850', 'Sungai Sumun'); 
INSERT INTO ref_city (code, label) VALUES ('0851', 'Sungkai'); 
INSERT INTO ref_city (code, label) VALUES ('0852', 'Taiping'); 
INSERT INTO ref_city (code, label) VALUES ('0853', 'Tanjung Malim'); 
INSERT INTO ref_city (code, label) VALUES ('0854', 'Tanjong Piandang'); 
INSERT INTO ref_city (code, label) VALUES ('0855', 'Tanjong Rambutan'); 
INSERT INTO ref_city (code, label) VALUES ('0856', 'Tanjong Tualang'); 
INSERT INTO ref_city (code, label) VALUES ('0857', 'Tapah'); 
INSERT INTO ref_city (code, label) VALUES ('0858', 'Tapah Road'); 
INSERT INTO ref_city (code, label) VALUES ('0859', 'Teluk Intan'); 
INSERT INTO ref_city (code, label) VALUES ('0860', 'Temoh'); 
INSERT INTO ref_city (code, label) VALUES ('0861', 'Trong'); 
INSERT INTO ref_city (code, label) VALUES ('0862', 'Tronoh'); 
INSERT INTO ref_city (code, label) VALUES ('0863', 'Ulu Kinta'); 
INSERT INTO ref_city (code, label) VALUES ('0864', 'Ulu Bernam'); 
INSERT INTO ref_city (code, label) VALUES ('0865', 'Sg Siput'); 
INSERT INTO ref_city (code, label) VALUES ('0866', 'Behrang Stesen'); 
INSERT INTO ref_city (code, label) VALUES ('0867', 'Trolak'); 
INSERT INTO ref_city (code, label) VALUES ('0880', 'Kuala Dipang'); 
INSERT INTO ref_city (code, label) VALUES ('0881', 'Kuala Kurau'); 
INSERT INTO ref_city (code, label) VALUES ('0882', 'Seri Manjung'); 
INSERT INTO ref_city (code, label) VALUES ('0883', 'Seri Iskandar'); 
INSERT INTO ref_city (code, label) VALUES ('0884', 'Lambor Kanan'); 
INSERT INTO ref_city (code, label) VALUES ('0885', 'Jeram'); 
INSERT INTO ref_city (code, label) VALUES ('0886', 'Rantau Panjang'); 
INSERT INTO ref_city (code, label) VALUES ('0887', 'Chikus'); 
INSERT INTO ref_city (code, label) VALUES ('0888', 'Changkat Jering'); 
INSERT INTO ref_city (code, label) VALUES ('0889', 'Gunong Semanggol'); 
INSERT INTO ref_city (code, label) VALUES ('0890', 'Simpang Ampat Semanggol'); 
INSERT INTO ref_city (code, label) VALUES ('0901', 'Arau'); 
INSERT INTO ref_city (code, label) VALUES ('0902', 'Kaki Bukit'); 
INSERT INTO ref_city (code, label) VALUES ('0903', 'Kangar'); 
INSERT INTO ref_city (code, label) VALUES ('0904', 'Kuala Perlis'); 
INSERT INTO ref_city (code, label) VALUES ('0905', 'Padang Besar'); 
INSERT INTO ref_city (code, label) VALUES ('0906', 'Simpang Ampat'); 
INSERT INTO ref_city (code, label) VALUES ('1001', 'Ampang'); 
INSERT INTO ref_city (code, label) VALUES ('1002', 'Banting'); 
INSERT INTO ref_city (code, label) VALUES ('1003', 'Batang Berjuntai'); 
INSERT INTO ref_city (code, label) VALUES ('1004', 'Batang Kali'); 
INSERT INTO ref_city (code, label) VALUES ('1005', 'Batu 9 Cheras'); 
INSERT INTO ref_city (code, label) VALUES ('1006', 'Batu Arang'); 
INSERT INTO ref_city (code, label) VALUES ('1007', 'Batu Caves'); 
INSERT INTO ref_city (code, label) VALUES ('1008', 'Beranang'); 
INSERT INTO ref_city (code, label) VALUES ('1009', 'Bukit Rotan'); 
INSERT INTO ref_city (code, label) VALUES ('1010', 'Dengkil'); 
INSERT INTO ref_city (code, label) VALUES ('1011', 'Hulu Langat'); 
INSERT INTO ref_city (code, label) VALUES ('1012', 'Jenjarom'); 
INSERT INTO ref_city (code, label) VALUES ('1013', 'Jeram'); 
INSERT INTO ref_city (code, label) VALUES ('1014', 'Kajang'); 
INSERT INTO ref_city (code, label) VALUES ('1015', 'Kapar'); 
INSERT INTO ref_city (code, label) VALUES ('1016', 'Klang'); 
INSERT INTO ref_city (code, label) VALUES ('1017', 'Kerling'); 
INSERT INTO ref_city (code, label) VALUES ('1018', 'Kuala Kubu Bharu'); 
INSERT INTO ref_city (code, label) VALUES ('1019', 'Kuala Lumpur'); 
INSERT INTO ref_city (code, label) VALUES ('1020', 'Kuala Selangor'); 
INSERT INTO ref_city (code, label) VALUES ('1021', 'Mantin'); 
INSERT INTO ref_city (code, label) VALUES ('1022', 'Nilai'); 
INSERT INTO ref_city (code, label) VALUES ('1023', 'Pelabuhan Klang'); 
INSERT INTO ref_city (code, label) VALUES ('1024', 'Petaling Jaya'); 
INSERT INTO ref_city (code, label) VALUES ('1025', 'Puchong'); 
INSERT INTO ref_city (code, label) VALUES ('1026', 'Pulau Carey'); 
INSERT INTO ref_city (code, label) VALUES ('1027', 'Pulau Ketam'); 
INSERT INTO ref_city (code, label) VALUES ('1028', 'Pulau Indah'); 
INSERT INTO ref_city (code, label) VALUES ('1029', 'Rantau Panjang'); 
INSERT INTO ref_city (code, label) VALUES ('1030', 'Rasa'); 
INSERT INTO ref_city (code, label) VALUES ('1031', 'Rawang'); 
INSERT INTO ref_city (code, label) VALUES ('1032', 'Sabak Bernam'); 
INSERT INTO ref_city (code, label) VALUES ('1033', 'Sekinchan'); 
INSERT INTO ref_city (code, label) VALUES ('1034', 'Semenyih'); 
INSERT INTO ref_city (code, label) VALUES ('1035', 'Sepang'); 
INSERT INTO ref_city (code, label) VALUES ('1036', 'Serendah'); 
INSERT INTO ref_city (code, label) VALUES ('1037', 'Seri Kembangan'); 
INSERT INTO ref_city (code, label) VALUES ('1038', 'Shah Alam'); 
INSERT INTO ref_city (code, label) VALUES ('1039', 'Subang Jaya'); 
INSERT INTO ref_city (code, label) VALUES ('1040', 'Sungai Ayer Tawar'); 
INSERT INTO ref_city (code, label) VALUES ('1041', 'Sungai Besar'); 
INSERT INTO ref_city (code, label) VALUES ('1042', 'Sungai Buloh'); 
INSERT INTO ref_city (code, label) VALUES ('1043', 'Sungai Pelek'); 
INSERT INTO ref_city (code, label) VALUES ('1044', 'Tanjong Karang'); 
INSERT INTO ref_city (code, label) VALUES ('1045', 'Tanjong Sepat'); 
INSERT INTO ref_city (code, label) VALUES ('1046', 'Telok Panglima Garang'); 
INSERT INTO ref_city (code, label) VALUES ('1047', 'Ukm Bangi'); 
INSERT INTO ref_city (code, label) VALUES ('1048', 'Upm Serdang'); 
INSERT INTO ref_city (code, label) VALUES ('1049', 'Hulu Bernam'); 
INSERT INTO ref_city (code, label) VALUES ('1050', 'Bandar Baru Bangi'); 
INSERT INTO ref_city (code, label) VALUES ('1052', 'Cyberjaya'); 
INSERT INTO ref_city (code, label) VALUES ('1053', 'Selayang'); 
INSERT INTO ref_city (code, label) VALUES ('1087', 'Bandar Baru Sungai Buloh'); 
INSERT INTO ref_city (code, label) VALUES ('1088', 'Ulu Yam Baru'); 
INSERT INTO ref_city (code, label) VALUES ('1089', 'Gombak'); 
INSERT INTO ref_city (code, label) VALUES ('1090', 'Pandan'); 
INSERT INTO ref_city (code, label) VALUES ('1091', 'Subang Airport'); 
INSERT INTO ref_city (code, label) VALUES ('1092', 'Cheras'); 
INSERT INTO ref_city (code, label) VALUES ('1093', 'Lapangan Terbang Antarabangsa Sepang'); 
INSERT INTO ref_city (code, label) VALUES ('1094', 'Serdang'); 
INSERT INTO ref_city (code, label) VALUES ('1095', 'Bandar Puncak Alam'); 
INSERT INTO ref_city (code, label) VALUES ('1096', 'Bestari Jaya'); 
INSERT INTO ref_city (code, label) VALUES ('1101', 'Ajil'); 
INSERT INTO ref_city (code, label) VALUES ('1102', 'Besut'); 
INSERT INTO ref_city (code, label) VALUES ('1103', 'Bukit Besi'); 
INSERT INTO ref_city (code, label) VALUES ('1104', 'Dungun'); 
INSERT INTO ref_city (code, label) VALUES ('1105', 'Jerteh'); 
INSERT INTO ref_city (code, label) VALUES ('1106', 'Bandar Permaisuri'); 
INSERT INTO ref_city (code, label) VALUES ('1107', 'Kemaman'); 
INSERT INTO ref_city (code, label) VALUES ('1108', 'Kemasek'); 
INSERT INTO ref_city (code, label) VALUES ('1109', 'Kijal'); 
INSERT INTO ref_city (code, label) VALUES ('1110', 'Kuala Berang'); 
INSERT INTO ref_city (code, label) VALUES ('1111', 'Kuala Besut'); 
INSERT INTO ref_city (code, label) VALUES ('1112', 'Kuala Terengganu'); 
INSERT INTO ref_city (code, label) VALUES ('1113', 'Marang'); 
INSERT INTO ref_city (code, label) VALUES ('1114', 'Paka'); 
INSERT INTO ref_city (code, label) VALUES ('1115', 'Kerteh'); 
INSERT INTO ref_city (code, label) VALUES ('1116', 'Al Muktafi Billah Shah'); 
INSERT INTO ref_city (code, label) VALUES ('1117', 'Kampung Raja'); 
INSERT INTO ref_city (code, label) VALUES ('1118', 'Cukai'); 
INSERT INTO ref_city (code, label) VALUES ('1119', 'Sungai Tong'); 
INSERT INTO ref_city (code, label) VALUES ('1120', 'Ceneh'); 
INSERT INTO ref_city (code, label) VALUES ('1121', 'Bukit Payong'); 
INSERT INTO ref_city (code, label) VALUES ('1122', 'Chalok'); 
INSERT INTO ref_city (code, label) VALUES ('1123', 'Setiu'); 
INSERT INTO ref_city (code, label) VALUES ('1124', 'Ketengah Jaya'); 
INSERT INTO ref_city (code, label) VALUES ('1125', 'Ayer Puteh'); 
INSERT INTO ref_city (code, label) VALUES ('1201', 'Beaufort'); 
INSERT INTO ref_city (code, label) VALUES ('1202', 'Beluran'); 
INSERT INTO ref_city (code, label) VALUES ('1203', 'Bongawan'); 
INSERT INTO ref_city (code, label) VALUES ('1204', 'Inanam'); 
INSERT INTO ref_city (code, label) VALUES ('1205', 'Keningau'); 
INSERT INTO ref_city (code, label) VALUES ('1206', 'Kota Belud'); 
INSERT INTO ref_city (code, label) VALUES ('1207', 'Kota Kinabalu'); 
INSERT INTO ref_city (code, label) VALUES ('1208', 'Kota Marudu'); 
INSERT INTO ref_city (code, label) VALUES ('1209', 'Kuala Penyu'); 
INSERT INTO ref_city (code, label) VALUES ('1210', 'Kudat'); 
INSERT INTO ref_city (code, label) VALUES ('1211', 'Kunak'); 
INSERT INTO ref_city (code, label) VALUES ('1212', 'Lahad Datu'); 
INSERT INTO ref_city (code, label) VALUES ('1213', 'Lamag'); 
INSERT INTO ref_city (code, label) VALUES ('1214', 'Likas'); 
INSERT INTO ref_city (code, label) VALUES ('1215', 'Membakut'); 
INSERT INTO ref_city (code, label) VALUES ('1216', 'Menumbok'); 
INSERT INTO ref_city (code, label) VALUES ('1217', 'Nabawan'); 
INSERT INTO ref_city (code, label) VALUES ('1218', 'Papar'); 
INSERT INTO ref_city (code, label) VALUES ('1219', 'Penampang'); 
INSERT INTO ref_city (code, label) VALUES ('1220', 'Ranau'); 
INSERT INTO ref_city (code, label) VALUES ('1221', 'Sandakan'); 
INSERT INTO ref_city (code, label) VALUES ('1222', 'Semporna'); 
INSERT INTO ref_city (code, label) VALUES ('1223', 'Sipitang'); 
INSERT INTO ref_city (code, label) VALUES ('1224', 'Tambunan'); 
INSERT INTO ref_city (code, label) VALUES ('1225', 'Tamparuli'); 
INSERT INTO ref_city (code, label) VALUES ('1226', 'Tanjung Aru'); 
INSERT INTO ref_city (code, label) VALUES ('1227', 'Tawau'); 
INSERT INTO ref_city (code, label) VALUES ('1228', 'Tenom'); 
INSERT INTO ref_city (code, label) VALUES ('1229', 'Tuaran'); 
INSERT INTO ref_city (code, label) VALUES ('1230', 'Kota Kinabatangan'); 
INSERT INTO ref_city (code, label) VALUES ('1231', 'Pamol'); 
INSERT INTO ref_city (code, label) VALUES ('1232', 'Putatan'); 
INSERT INTO ref_city (code, label) VALUES ('1234', 'Bandar Plaza Damansa'); 
INSERT INTO ref_city (code, label) VALUES ('1235', 'Beverly'); 
INSERT INTO ref_city (code, label) VALUES ('1236', 'Tenghilan'); 
INSERT INTO ref_city (code, label) VALUES ('1301', 'Asajaya'); 
INSERT INTO ref_city (code, label) VALUES ('1302', 'Balingian'); 
INSERT INTO ref_city (code, label) VALUES ('1303', 'Baram'); 
INSERT INTO ref_city (code, label) VALUES ('1304', 'Bau'); 
INSERT INTO ref_city (code, label) VALUES ('1305', 'Bekenu'); 
INSERT INTO ref_city (code, label) VALUES ('1306', 'Belaga'); 
INSERT INTO ref_city (code, label) VALUES ('1307', 'Belawai'); 
INSERT INTO ref_city (code, label) VALUES ('1308', 'Betong'); 
INSERT INTO ref_city (code, label) VALUES ('1309', 'Bintangor'); 
INSERT INTO ref_city (code, label) VALUES ('1310', 'Bintulu'); 
INSERT INTO ref_city (code, label) VALUES ('1311', 'Dalat'); 
INSERT INTO ref_city (code, label) VALUES ('1312', 'Daro'); 
INSERT INTO ref_city (code, label) VALUES ('1313', 'Debak'); 
INSERT INTO ref_city (code, label) VALUES ('1314', 'Engkilili'); 
INSERT INTO ref_city (code, label) VALUES ('1315', 'Julau'); 
INSERT INTO ref_city (code, label) VALUES ('1316', 'Kabong'); 
INSERT INTO ref_city (code, label) VALUES ('1317', 'Kanowit'); 
INSERT INTO ref_city (code, label) VALUES ('1318', 'Kapit'); 
INSERT INTO ref_city (code, label) VALUES ('1319', 'Kota Samarahan'); 
INSERT INTO ref_city (code, label) VALUES ('1320', 'Kuching'); 
INSERT INTO ref_city (code, label) VALUES ('1321', 'Lawas'); 
INSERT INTO ref_city (code, label) VALUES ('1322', 'Limbang'); 
INSERT INTO ref_city (code, label) VALUES ('1323', 'Lingga'); 
INSERT INTO ref_city (code, label) VALUES ('1324', 'Long Lama'); 
INSERT INTO ref_city (code, label) VALUES ('1325', 'Lubok Antu'); 
INSERT INTO ref_city (code, label) VALUES ('1326', 'Lundu'); 
INSERT INTO ref_city (code, label) VALUES ('1327', 'Matu'); 
INSERT INTO ref_city (code, label) VALUES ('1328', 'Miri'); 
INSERT INTO ref_city (code, label) VALUES ('1329', 'Mukah'); 
INSERT INTO ref_city (code, label) VALUES ('1330', 'Nanga Medamit'); 
INSERT INTO ref_city (code, label) VALUES ('1331', 'Niah'); 
INSERT INTO ref_city (code, label) VALUES ('1332', 'Pekenu'); 
INSERT INTO ref_city (code, label) VALUES ('1333', 'Pusa'); 
INSERT INTO ref_city (code, label) VALUES ('1334', 'Roban'); 
INSERT INTO ref_city (code, label) VALUES ('1335', 'Saratok'); 
INSERT INTO ref_city (code, label) VALUES ('1336', 'Sarikei'); 
INSERT INTO ref_city (code, label) VALUES ('1337', 'Sebauh'); 
INSERT INTO ref_city (code, label) VALUES ('1338', 'Sebuyau'); 
INSERT INTO ref_city (code, label) VALUES ('1339', 'Serian'); 
INSERT INTO ref_city (code, label) VALUES ('1340', 'Simunjan'); 
INSERT INTO ref_city (code, label) VALUES ('1341', 'Song'); 
INSERT INTO ref_city (code, label) VALUES ('1342', 'Spaoh'); 
INSERT INTO ref_city (code, label) VALUES ('1343', 'Sri Aman'); 
INSERT INTO ref_city (code, label) VALUES ('1344', 'Sundar'); 
INSERT INTO ref_city (code, label) VALUES ('1345', 'Tatau'); 
INSERT INTO ref_city (code, label) VALUES ('1346', 'Tebakang'); 
INSERT INTO ref_city (code, label) VALUES ('1347', 'Sibu'); 
INSERT INTO ref_city (code, label) VALUES ('1348', 'Bintangor'); 
INSERT INTO ref_city (code, label) VALUES ('1349', 'Tebedu'); 
INSERT INTO ref_city (code, label) VALUES ('1378', 'Pakan'); 
INSERT INTO ref_city (code, label) VALUES ('1379', 'Sibuti'); 
INSERT INTO ref_city (code, label) VALUES ('1380', 'Oya'); 
INSERT INTO ref_city (code, label) VALUES ('1381', 'Maludam'); 
INSERT INTO ref_city (code, label) VALUES ('1382', 'Lutong'); 
INSERT INTO ref_city (code, label) VALUES ('1383', 'Siburan'); 
INSERT INTO ref_city (code, label) VALUES ('1401', 'Kuala Lumpur'); 
INSERT INTO ref_city (code, label) VALUES ('1402', 'Setapak'); 
INSERT INTO ref_city (code, label) VALUES ('1403', 'Batu Caves'); 
INSERT INTO ref_city (code, label) VALUES ('1404', 'Sungai Besi'); 
INSERT INTO ref_city (code, label) VALUES ('1501', 'Labuan'); 
INSERT INTO ref_city (code, label) VALUES ('1601', 'Putrajaya'); 


INSERT INTO ref_country (code, label) VALUES ('3000', 'Malaysia'); 
INSERT INTO ref_country (code, label) VALUES ('3101', 'Afghanistan'); 
INSERT INTO ref_country (code, label) VALUES ('3102', 'Algeria'); 
INSERT INTO ref_country (code, label) VALUES ('3103', 'Antigua & Barbuda'); 
INSERT INTO ref_country (code, label) VALUES ('3104', 'Australia'); 
INSERT INTO ref_country (code, label) VALUES ('3105', 'Angola'); 
INSERT INTO ref_country (code, label) VALUES ('3106', 'Argentina'); 
INSERT INTO ref_country (code, label) VALUES ('3107', 'Albania'); 
INSERT INTO ref_country (code, label) VALUES ('3108', 'Austria'); 
INSERT INTO ref_country (code, label) VALUES ('3109', 'Arab Saudi'); 
INSERT INTO ref_country (code, label) VALUES ('3110', 'Rep.Afrika Tengah'); 
INSERT INTO ref_country (code, label) VALUES ('3111', 'Afrika Selatan'); 
INSERT INTO ref_country (code, label) VALUES ('3112', 'Andorra'); 
INSERT INTO ref_country (code, label) VALUES ('3113', 'Azerbaijan'); 
INSERT INTO ref_country (code, label) VALUES ('3114', 'American Samoa'); 
INSERT INTO ref_country (code, label) VALUES ('3115', 'Anguilla'); 
INSERT INTO ref_country (code, label) VALUES ('3116', 'Antarctica'); 
INSERT INTO ref_country (code, label) VALUES ('3117', 'Armenia'); 
INSERT INTO ref_country (code, label) VALUES ('3118', 'Aruba'); 
INSERT INTO ref_country (code, label) VALUES ('3201', 'Bahrain'); 
INSERT INTO ref_country (code, label) VALUES ('3202', 'Bangladesh'); 
INSERT INTO ref_country (code, label) VALUES ('3203', 'Bahamas'); 
INSERT INTO ref_country (code, label) VALUES ('3204', 'Barbados'); 
INSERT INTO ref_country (code, label) VALUES ('3205', 'Belize'); 
INSERT INTO ref_country (code, label) VALUES ('3206', 'Botswana'); 
INSERT INTO ref_country (code, label) VALUES ('3207', 'Britain'); 
INSERT INTO ref_country (code, label) VALUES ('3208', 'Benin'); 
INSERT INTO ref_country (code, label) VALUES ('3209', 'Bhutan'); 
INSERT INTO ref_country (code, label) VALUES ('3210', 'Bolivia'); 
INSERT INTO ref_country (code, label) VALUES ('3211', 'Brazil'); 
INSERT INTO ref_country (code, label) VALUES ('3212', 'Burma'); 
INSERT INTO ref_country (code, label) VALUES ('3213', 'Burundi'); 
INSERT INTO ref_country (code, label) VALUES ('3214', 'Bulgaria'); 
INSERT INTO ref_country (code, label) VALUES ('3215', 'Belgium'); 
INSERT INTO ref_country (code, label) VALUES ('3216', 'Byelorussia'); 
INSERT INTO ref_country (code, label) VALUES ('3217', 'Brunei'); 
INSERT INTO ref_country (code, label) VALUES ('3218', 'Bosnia Herzegovina'); 
INSERT INTO ref_country (code, label) VALUES ('3219', 'Bermuda'); 
INSERT INTO ref_country (code, label) VALUES ('3220', 'Burkina Faso/Burkina'); 
INSERT INTO ref_country (code, label) VALUES ('3221', 'Bora-bora'); 
INSERT INTO ref_country (code, label) VALUES ('3222', 'Belarus'); 
INSERT INTO ref_country (code, label) VALUES ('3223', 'Bouvet Island'); 
INSERT INTO ref_country (code, label) VALUES ('3224', 'British Indian Ocean Territory'); 
INSERT INTO ref_country (code, label) VALUES ('3301', 'Cameroon'); 
INSERT INTO ref_country (code, label) VALUES ('3302', 'Chad'); 
INSERT INTO ref_country (code, label) VALUES ('3303', 'Cambodia'); 
INSERT INTO ref_country (code, label) VALUES ('3304', 'Canada'); 
INSERT INTO ref_country (code, label) VALUES ('3305', 'Cyprus'); 
INSERT INTO ref_country (code, label) VALUES ('3306', 'Cape Verde'); 
INSERT INTO ref_country (code, label) VALUES ('3307', 'Central African Republic'); 
INSERT INTO ref_country (code, label) VALUES ('3308', 'Chile'); 
INSERT INTO ref_country (code, label) VALUES ('3309', 'Colombia'); 
INSERT INTO ref_country (code, label) VALUES ('3310', 'Comoros'); 
INSERT INTO ref_country (code, label) VALUES ('3312', 'Costa Rica'); 
INSERT INTO ref_country (code, label) VALUES ('3313', 'Cuba'); 
INSERT INTO ref_country (code, label) VALUES ('3314', 'China'); 
INSERT INTO ref_country (code, label) VALUES ('3315', 'Czechoslovakia'); 
INSERT INTO ref_country (code, label) VALUES ('3316', 'Kampuchea'); 
INSERT INTO ref_country (code, label) VALUES ('3317', 'Cayman Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3318', 'Congo-brazzaville'); 
INSERT INTO ref_country (code, label) VALUES ('3319', 'Congo-kinshasa'); 
INSERT INTO ref_country (code, label) VALUES ('3320', 'Croatia'); 
INSERT INTO ref_country (code, label) VALUES ('3321', 'Czech Republic'); 
INSERT INTO ref_country (code, label) VALUES ('3322', 'Cocos (Keeling) Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3323', 'Cook Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3325', 'Christmas Island'); 
INSERT INTO ref_country (code, label) VALUES ('3401', 'Djibouti'); 
INSERT INTO ref_country (code, label) VALUES ('3402', 'Dominica'); 
INSERT INTO ref_country (code, label) VALUES ('3403', 'Democratic Kampuche'); 
INSERT INTO ref_country (code, label) VALUES ('3405', 'Dahomey'); 
INSERT INTO ref_country (code, label) VALUES ('3406', 'Denmark'); 
INSERT INTO ref_country (code, label) VALUES ('3407', 'Dominican Republic'); 
INSERT INTO ref_country (code, label) VALUES ('3501', 'Egypt'); 
INSERT INTO ref_country (code, label) VALUES ('3502', 'Ecuador'); 
INSERT INTO ref_country (code, label) VALUES ('3503', 'El Salvador'); 
INSERT INTO ref_country (code, label) VALUES ('3504', 'Equatorial Guinea'); 
INSERT INTO ref_country (code, label) VALUES ('3505', 'Ethiopia'); 
INSERT INTO ref_country (code, label) VALUES ('3506', 'Estonia'); 
INSERT INTO ref_country (code, label) VALUES ('3507', 'Eritrea'); 
INSERT INTO ref_country (code, label) VALUES ('3601', 'Fiji'); 
INSERT INTO ref_country (code, label) VALUES ('3602', 'France'); 
INSERT INTO ref_country (code, label) VALUES ('3603', 'Finland'); 
INSERT INTO ref_country (code, label) VALUES ('3604', 'Falkland Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3605', 'French Guiana'); 
INSERT INTO ref_country (code, label) VALUES ('3606', 'Faeroe Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3607', 'Finland, Metropolitan'); 
INSERT INTO ref_country (code, label) VALUES ('3608', 'French Polynesia'); 
INSERT INTO ref_country (code, label) VALUES ('3609', 'French Southern Territories'); 
INSERT INTO ref_country (code, label) VALUES ('3701', 'Gabon'); 
INSERT INTO ref_country (code, label) VALUES ('3702', 'Gambia'); 
INSERT INTO ref_country (code, label) VALUES ('3703', 'Guinea'); 
INSERT INTO ref_country (code, label) VALUES ('3704', 'Guinea-bissau'); 
INSERT INTO ref_country (code, label) VALUES ('3705', 'Ghana'); 
INSERT INTO ref_country (code, label) VALUES ('3706', 'Grenada'); 
INSERT INTO ref_country (code, label) VALUES ('3707', 'Guyana'); 
INSERT INTO ref_country (code, label) VALUES ('3708', 'Guatemala'); 
INSERT INTO ref_country (code, label) VALUES ('3709', 'Greece'); 
INSERT INTO ref_country (code, label) VALUES ('3710', 'Germany'); 
INSERT INTO ref_country (code, label) VALUES ('3712', 'Georgia'); 
INSERT INTO ref_country (code, label) VALUES ('3713', 'Gibraltar'); 
INSERT INTO ref_country (code, label) VALUES ('3714', 'Greenland'); 
INSERT INTO ref_country (code, label) VALUES ('3715', 'Guadeloupe'); 
INSERT INTO ref_country (code, label) VALUES ('3716', 'Guam'); 
INSERT INTO ref_country (code, label) VALUES ('3717', 'Germany'); 
INSERT INTO ref_country (code, label) VALUES ('3801', 'Haiti'); 
INSERT INTO ref_country (code, label) VALUES ('3802', 'Honduras'); 
INSERT INTO ref_country (code, label) VALUES ('3803', 'Hungary'); 
INSERT INTO ref_country (code, label) VALUES ('3804', 'Hong Kong'); 
INSERT INTO ref_country (code, label) VALUES ('3805', 'Heard And McDonald Islands'); 
INSERT INTO ref_country (code, label) VALUES ('3806', 'Holy See (Vatican City)'); 
INSERT INTO ref_country (code, label) VALUES ('3901', 'Indonesia'); 
INSERT INTO ref_country (code, label) VALUES ('3902', 'Iran'); 
INSERT INTO ref_country (code, label) VALUES ('3903', 'Iraq'); 
INSERT INTO ref_country (code, label) VALUES ('3904', 'India'); 
INSERT INTO ref_country (code, label) VALUES ('3905', 'Ivory Coast'); 
INSERT INTO ref_country (code, label) VALUES ('3906', 'Israel'); 
INSERT INTO ref_country (code, label) VALUES ('3907', 'Ireland'); 
INSERT INTO ref_country (code, label) VALUES ('3908', 'Italy'); 
INSERT INTO ref_country (code, label) VALUES ('3909', 'Iceland'); 
INSERT INTO ref_country (code, label) VALUES ('4001', 'Jordan'); 
INSERT INTO ref_country (code, label) VALUES ('4002', 'Jamaica'); 
INSERT INTO ref_country (code, label) VALUES ('4003', 'Japan'); 
INSERT INTO ref_country (code, label) VALUES ('4101', 'Kuwait'); 
INSERT INTO ref_country (code, label) VALUES ('4102', 'Kenya'); 
INSERT INTO ref_country (code, label) VALUES ('4103', 'Kiribati'); 
INSERT INTO ref_country (code, label) VALUES ('4104', 'Korea (selatan)'); 
INSERT INTO ref_country (code, label) VALUES ('4105', 'Korea (utara)'); 
INSERT INTO ref_country (code, label) VALUES ('4106', 'Kazakhstan'); 
INSERT INTO ref_country (code, label) VALUES ('4107', 'Kyrgyzstan'); 
INSERT INTO ref_country (code, label) VALUES ('4201', 'Lebanon'); 
INSERT INTO ref_country (code, label) VALUES ('4202', 'Libya'); 
INSERT INTO ref_country (code, label) VALUES ('4203', 'Lesotho'); 
INSERT INTO ref_country (code, label) VALUES ('4204', 'Laos'); 
INSERT INTO ref_country (code, label) VALUES ('4205', 'Liberia'); 
INSERT INTO ref_country (code, label) VALUES ('4206', 'Luxembourg'); 
INSERT INTO ref_country (code, label) VALUES ('4207', 'Latvia'); 
INSERT INTO ref_country (code, label) VALUES ('4208', 'Liechtenstein'); 
INSERT INTO ref_country (code, label) VALUES ('4209', 'Lithuania'); 
INSERT INTO ref_country (code, label) VALUES ('4301', 'Mali'); 
INSERT INTO ref_country (code, label) VALUES ('4302', 'Maldives'); 
INSERT INTO ref_country (code, label) VALUES ('4303', 'Mauritania'); 
INSERT INTO ref_country (code, label) VALUES ('4304', 'Morocco'); 
INSERT INTO ref_country (code, label) VALUES ('4305', 'Malawi'); 
INSERT INTO ref_country (code, label) VALUES ('4306', 'Malta'); 
INSERT INTO ref_country (code, label) VALUES ('4307', 'Madagascar'); 
INSERT INTO ref_country (code, label) VALUES ('4308', 'Mauritius'); 
INSERT INTO ref_country (code, label) VALUES ('4309', 'Mexico'); 
INSERT INTO ref_country (code, label) VALUES ('4310', 'Mozambique'); 
INSERT INTO ref_country (code, label) VALUES ('4311', 'Malagasy'); 
INSERT INTO ref_country (code, label) VALUES ('4312', 'Mongolia'); 
INSERT INTO ref_country (code, label) VALUES ('4313', 'Maghribi'); 
INSERT INTO ref_country (code, label) VALUES ('4314', 'Monaco'); 
INSERT INTO ref_country (code, label) VALUES ('4315', 'Montserrat'); 
INSERT INTO ref_country (code, label) VALUES ('4316', 'Micronesia'); 
INSERT INTO ref_country (code, label) VALUES ('4317', 'Myanmar'); 
INSERT INTO ref_country (code, label) VALUES ('4318', 'Macau'); 
INSERT INTO ref_country (code, label) VALUES ('4319', 'Marshall Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4320', 'Macedonia'); 
INSERT INTO ref_country (code, label) VALUES ('4321', 'Martinique'); 
INSERT INTO ref_country (code, label) VALUES ('4322', 'Mayotte'); 
INSERT INTO ref_country (code, label) VALUES ('4323', 'Montenegro'); 
INSERT INTO ref_country (code, label) VALUES ('4401', 'Niger'); 
INSERT INTO ref_country (code, label) VALUES ('4402', 'Nauru'); 
INSERT INTO ref_country (code, label) VALUES ('4403', 'New Zealand'); 
INSERT INTO ref_country (code, label) VALUES ('4404', 'Nigeria'); 
INSERT INTO ref_country (code, label) VALUES ('4405', 'Nepal'); 
INSERT INTO ref_country (code, label) VALUES ('4406', 'Nicaragua'); 
INSERT INTO ref_country (code, label) VALUES ('4407', 'Netherlands'); 
INSERT INTO ref_country (code, label) VALUES ('4408', 'Norway'); 
INSERT INTO ref_country (code, label) VALUES ('4409', 'Namibia'); 
INSERT INTO ref_country (code, label) VALUES ('4410', 'Netherlands Antilles'); 
INSERT INTO ref_country (code, label) VALUES ('4411', 'Neutral Zone'); 
INSERT INTO ref_country (code, label) VALUES ('4412', 'New Caledonia'); 
INSERT INTO ref_country (code, label) VALUES ('4413', 'Niue'); 
INSERT INTO ref_country (code, label) VALUES ('4414', 'Norfolk Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4415', 'Northern Marianas Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4501', 'Oman'); 
INSERT INTO ref_country (code, label) VALUES ('4502', 'Outer Mongolia'); 
INSERT INTO ref_country (code, label) VALUES ('4601', 'Pakistan'); 
INSERT INTO ref_country (code, label) VALUES ('4602', 'Papua New Guinea'); 
INSERT INTO ref_country (code, label) VALUES ('4603', 'Palestine'); 
INSERT INTO ref_country (code, label) VALUES ('4604', 'Panama'); 
INSERT INTO ref_country (code, label) VALUES ('4605', 'Paraguay'); 
INSERT INTO ref_country (code, label) VALUES ('4606', 'Peru'); 
INSERT INTO ref_country (code, label) VALUES ('4607', 'Philippines'); 
INSERT INTO ref_country (code, label) VALUES ('4608', 'Poland'); 
INSERT INTO ref_country (code, label) VALUES ('4609', 'Portugal'); 
INSERT INTO ref_country (code, label) VALUES ('4610', 'Pitcairn Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4611', 'Puerto Rico'); 
INSERT INTO ref_country (code, label) VALUES ('4612', 'Palau'); 
INSERT INTO ref_country (code, label) VALUES ('4701', 'Qatar'); 
INSERT INTO ref_country (code, label) VALUES ('4801', 'Romania'); 
INSERT INTO ref_country (code, label) VALUES ('4802', 'Rwanda'); 
INSERT INTO ref_country (code, label) VALUES ('4803', 'Reunion'); 
INSERT INTO ref_country (code, label) VALUES ('4804', 'Russian Federation'); 
INSERT INTO ref_country (code, label) VALUES ('4805', 'Refugee Article 1/1951'); 
INSERT INTO ref_country (code, label) VALUES ('4806', 'Refugee'); 
INSERT INTO ref_country (code, label) VALUES ('4807', 'Rep. Of Moldova'); 
INSERT INTO ref_country (code, label) VALUES ('4808', 'Republic Of Yemen'); 
INSERT INTO ref_country (code, label) VALUES ('4901', 'Senegal'); 
INSERT INTO ref_country (code, label) VALUES ('4902', 'Sierra Leone'); 
INSERT INTO ref_country (code, label) VALUES ('4903', 'Somalia'); 
INSERT INTO ref_country (code, label) VALUES ('4904', 'Sudan'); 
INSERT INTO ref_country (code, label) VALUES ('4905', 'Syria'); 
INSERT INTO ref_country (code, label) VALUES ('4906', 'St.lucia'); 
INSERT INTO ref_country (code, label) VALUES ('4907', 'St.vicent'); 
INSERT INTO ref_country (code, label) VALUES ('4908', 'Seychelles'); 
INSERT INTO ref_country (code, label) VALUES ('4909', 'Singapura'); 
INSERT INTO ref_country (code, label) VALUES ('4910', 'Solomon Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4911', 'Sri Lanka'); 
INSERT INTO ref_country (code, label) VALUES ('4912', 'Swaziland'); 
INSERT INTO ref_country (code, label) VALUES ('4913', 'Samoa'); 
INSERT INTO ref_country (code, label) VALUES ('4914', 'Sao Tome & Principe'); 
INSERT INTO ref_country (code, label) VALUES ('4915', 'Suriname'); 
INSERT INTO ref_country (code, label) VALUES ('4916', 'Samoa Barat'); 
INSERT INTO ref_country (code, label) VALUES ('4917', 'Sweden'); 
INSERT INTO ref_country (code, label) VALUES ('4918', 'Spain'); 
INSERT INTO ref_country (code, label) VALUES ('4919', 'Swapo'); 
INSERT INTO ref_country (code, label) VALUES ('4920', 'Switzerland'); 
INSERT INTO ref_country (code, label) VALUES ('4921', 'St. Helena'); 
INSERT INTO ref_country (code, label) VALUES ('4922', 'St. Kitts And Nevis'); 
INSERT INTO ref_country (code, label) VALUES ('4923', 'Serbia'); 
INSERT INTO ref_country (code, label) VALUES ('4924', 'San Marino'); 
INSERT INTO ref_country (code, label) VALUES ('4925', 'Slovakia'); 
INSERT INTO ref_country (code, label) VALUES ('4926', 'Slovenia'); 
INSERT INTO ref_country (code, label) VALUES ('4927', 'South Georgia & The South Sandwich Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4928', 'Stateless Person Article 1/1954'); 
INSERT INTO ref_country (code, label) VALUES ('4929', 'Svalbard And Jan Mayen Islands'); 
INSERT INTO ref_country (code, label) VALUES ('4930', 'St. Pierre And Miquelon'); 
INSERT INTO ref_country (code, label) VALUES ('4931', 'St. Vincent And The Grenadines'); 
INSERT INTO ref_country (code, label) VALUES ('4932', 'St. Lucia'); 
INSERT INTO ref_country (code, label) VALUES ('5001', 'Tunisia'); 
INSERT INTO ref_country (code, label) VALUES ('5002', 'Turkey'); 
INSERT INTO ref_country (code, label) VALUES ('5003', 'Tanzania'); 
INSERT INTO ref_country (code, label) VALUES ('5004', 'Tonga'); 
INSERT INTO ref_country (code, label) VALUES ('5005', 'Trinidad & Tobago'); 
INSERT INTO ref_country (code, label) VALUES ('5006', 'Tuvalu'); 
INSERT INTO ref_country (code, label) VALUES ('5007', 'Thailand'); 
INSERT INTO ref_country (code, label) VALUES ('5008', 'Togo'); 
INSERT INTO ref_country (code, label) VALUES ('5009', 'Taiwan'); 
INSERT INTO ref_country (code, label) VALUES ('5010', 'Tajikistan'); 
INSERT INTO ref_country (code, label) VALUES ('5011', 'Turkmenistan'); 
INSERT INTO ref_country (code, label) VALUES ('5012', 'Timor Leste'); 
INSERT INTO ref_country (code, label) VALUES ('5013', 'Tokelau'); 
INSERT INTO ref_country (code, label) VALUES ('5014', 'Turks And Caicos Islands'); 
INSERT INTO ref_country (code, label) VALUES ('5101', 'Uganda'); 
INSERT INTO ref_country (code, label) VALUES ('5102', 'United Arab Emirates'); 
INSERT INTO ref_country (code, label) VALUES ('5103', 'Upper Volta'); 
INSERT INTO ref_country (code, label) VALUES ('5106', 'Uruguay'); 
INSERT INTO ref_country (code, label) VALUES ('5107', 'U.s.s.r'); 
INSERT INTO ref_country (code, label) VALUES ('5108', 'Ukraine'); 
INSERT INTO ref_country (code, label) VALUES ('5110', 'United States Of America'); 
INSERT INTO ref_country (code, label) VALUES ('5111', 'Uzbekistan'); 
INSERT INTO ref_country (code, label) VALUES ('5112', 'Uk-dependent Territories Citizen'); 
INSERT INTO ref_country (code, label) VALUES ('5113', 'Uk-national Overseas'); 
INSERT INTO ref_country (code, label) VALUES ('5114', 'Uk-oversean Citizen'); 
INSERT INTO ref_country (code, label) VALUES ('5115', 'Uk-protected Person'); 
INSERT INTO ref_country (code, label) VALUES ('5116', 'Uk-subject'); 
INSERT INTO ref_country (code, label) VALUES ('5117', 'Un Specialized Agency'); 
INSERT INTO ref_country (code, label) VALUES ('5119', 'United Nations Organization'); 
INSERT INTO ref_country (code, label) VALUES ('5120', 'United States Minor Outlying Islands'); 
INSERT INTO ref_country (code, label) VALUES ('5121', 'Unspecified Nationality'); 
INSERT INTO ref_country (code, label) VALUES ('5201', 'Vanuatu'); 
INSERT INTO ref_country (code, label) VALUES ('5202', 'Venezuela'); 
INSERT INTO ref_country (code, label) VALUES ('5203', 'Vietnam'); 
INSERT INTO ref_country (code, label) VALUES ('5204', 'Vatican City'); 
INSERT INTO ref_country (code, label) VALUES ('5205', 'Virgin Islands'); 
INSERT INTO ref_country (code, label) VALUES ('5206', 'Virgin Islands (usa)'); 
INSERT INTO ref_country (code, label) VALUES ('5207', 'Wallis And Futuna Islands'); 
INSERT INTO ref_country (code, label) VALUES ('5208', 'Western Sahara'); 
INSERT INTO ref_country (code, label) VALUES ('5301', 'Yemen Arab Rep.'); 
INSERT INTO ref_country (code, label) VALUES ('5302', 'Yemen People Dem.re'); 
INSERT INTO ref_country (code, label) VALUES ('5303', 'Yugoslavia'); 
INSERT INTO ref_country (code, label) VALUES ('5401', 'Zaire'); 
INSERT INTO ref_country (code, label) VALUES ('5402', 'Zambia'); 
INSERT INTO ref_country (code, label) VALUES ('5403', 'Zimbabwe'); 
INSERT INTO ref_country (code, label) VALUES ('5501', 'Western Samoa'); 
