

INSERT INTO `ref_skill` (`val`) VALUES
('React'),
('GraphQL'),
('PHP'),
('Oracle'),
('MySQL'),
('Adobe Photoshop'),
('Software Development'),
('Wordpress'),
('Javascript'),
('Redux'),
('Test'),
('Web Development'),
('Java'),
('C'),
('C++'),
('C#'),
('MATLAB'),
('ImageJ'),
('NX 11.0'),
('Python'),
('HTML/CSS'),
('SolidWorks'),
('AutoCAD'),
('Photoshop'),
('Illustrator'),
('Microsoft Excel'),
('Vector CANoe'),
('Microsoft Project'),
('Microsoft Word'),
('Microsoft PowerPoint'),
('Microsoft Visio'),
('Microsoft Excel with Macro'),
('Autodesk Inventor'),
('SQL'),


('English'),
('Malay'),
('Mandarin'),





('Microsoft Office Suite'),
('MicroSquisher'),
('Microscopy'),
('AFM'),
('Lathe'),
('Mill'),

('Guitar'),
('Piano'),
('Saxophone'),
('Modflow'),
('EM31 '),
('GPR'),

('Premiere Pro'),
('Sony Vegas'),
('After Effects'),
('Design'),
('Poster'),
('Logo Design'),
('REFRACT'),
('Geophones'),
('Project Management'),
('Data Analysis'),
('Public Speaking'),
('Strategic Planning'),
('Stata'),
('Policy Analysis'),
('Marketing'),
('Editing'),
('Microsoft Office'),
('CMG Reservoir Simulator'),
('Microsoft Office (words, PP, Excel)'),
('Microsoft Visual Studios C++'),
('Time Management'),
('Organization skills'),
('Computer-Aided Design (CAD)'),

('Mathcad'),
('COMSOL Multiphysics'),
('Design Failure Mode Effect and Analysis (DFMEA)'),
('Geometric Dimensioning and Tolerancing (GD&T)'),
('Design for Assembly and Manufacturability (DFA DFM)'),
('New Product Introduction (NPI)'),
('CAD Drawings'),
('Bill of Materials (BOM)'),
('Finite Element Analysis (FEA)'),
('Tolerance Analysis (TA)'),
('Sheet Metal/Welded Assembly Design'),
('Plastic Molding Design'),
('Spin Casting Zinc Design'),
('SCRUM'),
('English (Fluent)'),
('Malay (Native Language)'),
('Machine shop fabrication'),
('Engineering Design and Drafting techniques'),
('Aircraft Design'),
('ArcMap (GIS)'),
('Groundwater Vistas (Groundwater Flow Modeling)'),
('Dev C++ (Programming)'),
('Research'),
('Writing (English and Malay)'),
('80/20 Design'),
('Microsoft Suites'),
('RStudio'),
('Matlab and Simulink'),
('Aspen Plus'),
('LoggerPro Software'),
('Fusion 360'),
('Customer Service'),
('Japanese'),
('Arabic'),
('Mathematica'),
('CREO Parametric'),
('Pixlr Editor'),
('PowerPoint'),
('Aspen Plus Simulation'),
('Refinery Operation'),
('Process Control'),
('Corrosion Engineering'),
('Scientific Research'),
('Electrochemistry'),
('Computer: SOLIDWORKS, CATIA V5, PTC CREO, AutoCAD, 3D Revit, Microsoft Office'),
('Programming Software: SQL, C++, Python, GIT, MATLAB, Arduino'),
('Aspen'),
('Event planning'),
('Excel VBA'),
('Multitasking'),
('Excel'),
('R'),
('R studio'),
('SPSS'),
('Analytical '),
('Machine: CNC router, Foam cutter, Laser cutter, 3D printer, Wind tunnel'),
('Adobe Illustrator'),
('Adobe XD'),
('Fossil Preparation'),
('Chemical Preparation'),
('Bash Programming'),
('Unix/Linux Command'),
('General Mapping Tools (GMT)'),
('ArcGIS'),
('Adobe Creative Suites'),
('CNC'),
('SAS'),
('VBA'),
('Tableau'),
('Access'),
('Aspen HYSYS'),
('Aspen Energy Analyzer'),
('Minitab'),
('Six-Sigma Design'),
('Entrepreneurship '),
('Teamwork'),
('Quality Management'),
('Adobe Creative Suite'),
('Process and Design'),
('Material Engineering'),
('Petrochemical'),
('Arduino'),
('Mill Machine'),
('Lathe Machine'),
('Adobe Lightroom'),
('Microsoft (Word, Excel)'),
('Java (Eclipse)'),
('Html 5& CSS ( Notepad ++)'),
('Drilling Engineering '),
('Petroleum Engineering '),
('Geology '),
('Unconventional Reservoir '),
('Well Logging '),
('Photography '),
('Adobe'),
('Team Leader '),
('Petra'),
('Leadership Skills'),
('Stimplan'),
('TechLog '),
('Volunteering '),
('Trllingual'),
('Market research'),
('Word'),
('Techlog Well Logging Simulator'),
('R program'),
('Sidra 2.0'),
('Adobe Creative'),
('Microsoft Suite: Word, Powerpoint & Excel'),
('Heat Integration Network'),
('Water Recycle Network'),
('Electrospinning for polymer synthesis'),
('Research skill'),
('Laboratory Skill'),
('Geographical Information Systems'),
('MIcorosft Powerpoint'),
('Microsoft Power Point'),
('Battery Testing'),
('Microsoft Word, Excel, Power Point'),
('Visual Basic Programming (VBA)'),
('Stanford Geostatistical Modeling Software (SGeMS)'),
('Petrel (Reservoir Software)'),
('TIBCO Spotfire'),
('Computer Modeling Group (CMG-Reservoir Simulation Software)'),
('microcontroller'),
('Web Programming'),
('Adaptability'),
('Self-Motivation'),
('MS Visio'),
('PHDWin Decline Curve Analysis'),
('Drillinginfo '),
('CMG Reservoir Simulation '),
('Linux'),
('Aircraft Structure Analysis'),
('Aircraft Stability and Control'),
('Aerodynamics '),
('Aeronautics'),
('LabView for Wind Tunnel Analysis'),
('Flight Testing'),
('Mobile Robotics'),
('Verilog'),
('Social skill'),
('Public speaking and presentation skills'),
('Ingenuity '),
('Statistical Analysis'),
('Ansys'),
('RevIt'),
('CNC Coding'),
('IBM SPSS'),
('Machining'),
('Woodwork'),
('Soldering'),
('Car Repair'),
('Shop Machine'),
('Milling'),
('Welding'),
('Bloomberg Terminal'),
('Adobe Audition '),
('Adobe Premiere '),
('Self Motivated'),
('Microsoft Applications'),
('Conscientious '),
('Prospecting'),
('Creative play director'),
('Algorithms'),
('Graphic Design'),
('Assembly lang'),
('Adobe InDesign'),
('Blender'),
('Solid Works'),
('Have worked with CNC Machines'),
('SketchUp'),
('Creativity'),
('SWMM'),
('Engineering'),
('Project Planning'),
('Technical Documentation'),
('C Language'),
('Assembly x86'),
('Microcontrollers'),
('PCB Design'),
('Multi-meters'),
('Oscilloscope'),
('Internet of Things'),
('Machine Learning'),
('Microsoft'),
('Retail Sales'),
('Microsoft Access'),
('JIRA software'),
('CREO Pro/Engineer'),
('LabVIEW'),
('SuperPro Designer'),
('Polymath'),
('Crude Oil Upgrading'),
('VMGSim'),
('P&ID'),
('MS Office Suite'),
('MS Project'),
('Autodesk Revit'),
('SAP2000'),
('AGI32'),
('R-Project'),
('On-Screen Takeoff'),
('Chinese'),
('Cantonese'),
('MS Office'),
('Unisim'),
('Research Data Analysis'),
('Public Speaking/ Presentation Skill'),
('Event Management'),
('Siemens NX'),
('LoopPro'),
('Teamwork Skills'),
('Microsoft Word, Excel and Powerpoint'),
('Adobe Photoshop, InDesign'),
('Helpdesk'),
('Detailed and organized'),
('Problem solving skills'),
('Oral and written communication'),
('Phyton'),
('Relator '),
('Ruby'),
('Search Engine Optimization '),
('Google Analytics '),
('Google Tag Manager'),
('Achiever'),
('Focus'),
('Deliberative'),
('Competition'),
('Computer-Aided Design (CAD) - Solidworks'),
('Programming - MATLAB, C++, Arduino uno'),
('Experienced with C, C++, Matlab, and Python programming language.'),
('Linear Regression'),
('Independent Learner'),
('Writing, Reporting, Editing'),
('Video and audio production and editing'),
('Wordpress, writing for the web (SEO headlines and keywords)'),
('Fact-Checking'),
('Final Cut Pro, Adobe Premiere Pro, Audacity'),
('Mac OS, MS Office'),
('Management'),
('Infogram, CoveritLive, Storify, Timeline JS, Soundslides'),
('Lav Mics, Canon 60D Cameras'),
('Basic HTML, CSS, basic JavaScript'),
('communication and writing abilities'),
('CATIA v5'),
('Designing and Manufacturing'),
('Technical Writing'),
('Training'),
('Applied Behavior Analysis'),
('Consulting'),
('Psychology'),
('Programming'),
('Languange C'),
('C++ Programming'),
('Assembly Coding'),
('PSpice Design and Simulation'),
('Electronic Circuit Design'),
('jQuery'),
('Agile/Scrum'),
('Unix'),
('Git'),
('ASP.NET MVC'),
('business development'),
('microsoft outlook'),
('VBA Excel'),
('PIPESIM'),
('Harmony Software'),
('ECLIPSE'),
('IHS PETRA'),
('iMovie'),
('Photron Fastcam Viewer (PFV)'),
('JAVA Programmer'),
('IT Tech Support'),
('TCP UDP Knowledge Experience'),
('Proficiency in English and Malay'),
('Model Design Through Software'),
('Matlab Programming'),
('Communcations and Interactive Human Skills'),
('FEA'),
('Visual analysis'),
('Petrel'),
('Product Development'),
('Android Development'),
('Big Data'),
('Debugging'),
('Embedded C'),
('Hadoop'),
('Android Studio'),
('Technical Presentation'),
('Fl Studio'),
('Account'),
('Xero'),
('Management Accounting'),
('Digital Marketing'),
('Graphic Desiging'),
('Debating'),
('Bookkeeping'),
('Coaching'),
('Online Marketing'),
('Wix Expert'),
('Financial Accounting'),
('Problem Solving'),
('Microsoft Office - Word, Excel and PowerPoint'),
('Aspen Plus & HYSYS'),
('Good Communication skills'),
('Community organizing'),
('MYOB - Accounting Software'),
('Xero -  Accounting Software'),
('Organizational Commitment'),
('Cross-Organization Collaboration'),
('Keen to learn'),
('Mandarin - Elementary'),
('Petroleum Process'),
('Rugby'),
('COMSOL'),
('Technology Savvy'),
('Team Facilitation'),
('Resourceful'),
('Financial Literate'),
('Microsoft Office (Excel, Words, Publisher, Powerpoint, Outlook)'),
('Passionate and keen to learn new things'),
('Microsoft Office (Words, Excel, Powerpoint)'),
('Computer Literacy'),
('Professional Communication'),
('Microsoft Offices (Words, Excel, PowerPoint)'),
('MYOB Essential'),
('Web Development (HTML, CSS)'),
('Video Editing (iMovie)'),
('HTML'),
('Engagement'),
('Communication and teamwork'),
('Passionate and enthusiastic'),
('Basic Microsoft Excel - Multiple short cut skills learned and utilized during my previous audit internship at EY Malaysia.'),
('Strong Communication Skills '),
('Enthusiastic Team Player '),
('Energetic leadership traits '),
('Excellent Public Speaking and Presentation skills'),
('Amicable People Skills'),
('Web Content Management'),
('Management Skill'),
('Communication Skill'),
('Micorsoft Office Excel'),
('CCH Software'),
('New Zealand Financial Reporting (NZFRIS)'),
('Good communication and negotiating skill'),
('Fluent Bilingual - Bahasa Malaysia and English'),
('Financially Literate'),
('Accounting Software - SAP, Aura, Xero'),
('Other technological knowledge - Microsoft Office, Photoshop etc'),
('Sports - Climbing, Volleyball, Swimming etc'),
('Great Interpersonal, Leadership and Teamwork skills'),
('Accounting'),
('Badminton'),
('CAD'),
('ANSYS Fluent'),
('ChemCAD'),
('CATIA'),
('Star-CCM+'),
('Energy Plus'),
('AmeSIM'),
('Visual Basic'),
('Unity3D'),
('Rotating Equipment'),
('Maintenance Engineering'),
('CMMS'),
('Preventive Maintenance'),
('Pumps'),
('Valves'),
('Microsoft Words'),
('Interpersonal skill'),
('Multi-tasker'),
('Highly organized'),
('Self-motivated'),
('Critical thinker'),
('Solidwork'),
('Effects'),
('ALOHA'),
('Spectroscopie'),
('Taekwondo'),
('French'),
('Security Industrial'),
('ISO 14001'),
('Organic & Mineral Chemistry'),
('Mechanics of fluid'),
('Hydraulic'),
('Hydrogeology'),
('Thermochemistry'),
('Reactor & Agitation'),
('Schema TI'),
('Heat transfer'),
('Prophyl plus'),
('Prosim'),
('Environment'),
('Extraction'),
('Distillation'),
('Abs-Adsorption'),
('Treatment of water'),
('Cristallisation'),
('Regulation PID'),
('HPLC'),
('CPG'),
('Infrared'),
('UV-Visible'),
('Process Simulation'),
('SolidEdge'),
('Event Organisation'),
('NI Multisim'),
('MS - Office'),
('Design Software'),
('MS Word'),
('MS PowerPoint'),
('MS Excel'),
('Marketing Campaign'),
('Land Management'),
('Public Speaking & Debate'),
('Rail & Transportation'),
('Manufacturing '),
('Statistic'),
('Supply Chain Engineering'),
('Procurement'),
('Quality Control'),
('CAM'),
('CIM'),
('DOE'),
('German'),
('Metamaterial'),
('Planning'),
('Critical thinking'),
('hardworker'),
('ability to work under pressure'),
('fast learner'),
('siemens nx software'),
('spanish'),
('Conceptual Design'),
('Topology Optimization (Optistruct)'),
('Innovation'),
('Computer Modeling (2D & 3D)'),
('Orcaflex (Fatigue and Dynamic Simulation)'),
('CATIA V5 (CAD)'),
('Finite Element Analysis (Abaqus)'),
('Molecular Biology'),
('Microbiology'),
('Research & Strategy'),
('Driving License'),
('GIMP'),
('Inkscape'),
('Geological mapping'),
('Hysplit'),
('Microsoft Office Word Excel etc'),
('Matlab/Simulink'),
('ETAS INCA'),
('FEM Altair'),
('UniPlot'),
('Corporate Relationship'),
('Programming C, C++'),
('Circuit Design Eagle, Altium'),
('Mechanical Construction PCB Creo'),
('Social Work'),
('FESTO Fluidsim'),
('Visual Studio C++'),
('CAD/CAM'),
('Automotive'),
('HTML5'),
('PTC Creo'),
('Mdesign'),
('CITAVI'),
('FTIR'),
('GC-MS'),
('Six-Sigma'),
('SimaPro'),
('Creo'),
('Analytical Chemistry'),
('AspenPlus'),
('ProII'),
('Metallography Lab'),
('Thermal Management'),
('Electronic cooling'),
('Polyurethane'),
('like to work in group'),
('independent and reliable'),
('Ready to learn new things'),
('Visio'),
('CAD - NX 10.0 '),
('FEA - ANSYS 19'),
('MTS TOPCAM'),
('HSi-Plan'),
('Microsoft (Word,PowerPoint,Excel)'),
('Ecotoxicology'),
('ISO 50001'),
('ANSYS Workbench'),
('Academic  Writing'),
('CAD Software'),
('Programming using C/C++ and Arduino'),
('Designing using AutoCAD and CATIA V5'),
('French as Third Language'),
('Chemistry'),
('Proofreading'),
('Polymer'),
('Transcription'),
('Translation'),
('Plastics'),
('Prosim Plus'),
('Fortran'),
('IoT'),
('Communication Protocoll'),
('Andoird'),
('Radar'),
('Bus System'),
('Planning and research skill'),
('IT skills'),
('Strong Work Ethic'),
('Autodesk AutoCAD'),
('Proteus'),
('NI LABView'),
('Quartus'),
('Siemens Tecnomatix Plant Simulation'),
('V-REP'),
('WITNESS'),
('Qt'),
('Corel Video Studio Pro'),
('Pneumatics'),
('Lean Line Design'),
('Public Speaking and Debating'),
('Researcher'),
('Teaching and Mentoring'),
('Graphic design: Basic knowledge in Photoshop and Illustrator'),
('Languages: Fluent in both written and spoken for English, Mandarin and Bahasa Malaysia'),
('Proficient in Microsoft Word, Excel and PowerPoint'),
('Organised, analytical and detail-oriented '),
('Strong communication and delegation skills '),
('Document Drafting'),
('LaTeX'),
('SAP BusinessObjects'),
('Statistical Data Analysis'),
('Peer Tutoring'),
('Organisational'),
('Creative thinking'),
('Land Surveying '),
('OpenFOAM'),
('QGIS'),
('BUSINESS ACUMEN'),
('DATA ANALYTICS'),
('PYTHON CODING'),
('Writing'),
('Editorial Process'),
('Mediation'),
('Organisation'),
('Chemical Engineering'),
('Process Design'),
('Process Evaluations'),
('gPROMS'),
('CPLEX'),
('Biogeme '),
('Positive attitude'),
('Finite Element Analysis'),
('Critical Analysis'),
('Excel software'),
('Words '),
('Power point '),
('Microsoft Office (Word, Powerpoint, Sharepoint, Outlook)'),
('Layout design (Canva, basic Adobe InDesign)'),
('Mathematics'),
('Statistics'),
('Working in groups'),
('Finance'),
('Data analysing'),
('Time managment '),
('Negotiation'),
('Retail'),
('R-Studio'),
('Fluent in English and Malay'),
('Sports'),
('Electrical Engineering'),
('Semiconductors'),
('Power Electronics'),
('Human Resources'),
('Simulink'),
('Time-efficient'),
('Power Engineering'),
('Solar PV'),
('Solar System Design'),
('Engineering Mathematics'),
('Law'),
('Adobe Premiere Pro CC'),
('Adobe Photoshop CC'),
('Adobe After Effects CC'),
('Adobe Lightroom CC'),
('Debate'),
('Presentation'),
('Microsoft Offices'),
('SPRINT'),
('Scuba Diving'),
('Tutoring'),
('Non-Profit Volunteering'),
('C, C++, Java Programming'),
('Marketing & Outreach'),
('RStudio Programming'),
('Excel VBA Programming'),
('MySQL, SQLite Database'),
('C Programming'),
('R Programming'),
('Oasys Suite'),
('Abaqus'),
('MiTS'),
('Ultimaker Cura'),
('IviumSoft'),
('Electronics and Computing DIY'),
('Game Development'),
('GAMS'),
('Effective Communication '),
('Team Building'),
('Problem-Solving'),
('General Algebraic Modelling Software (GAMS)'),
('Requirement Gathering'),
('Teamworking'),
('R programming language'),
('AutoAccounting'),
('Event Photography'),
('Communication and Soft skills'),
('Citrix'),
('Autodesk (Revit and AutoCAD)'),
('MS Office (Word, PowerPoint and Excel)'),
('japanese translator'),
('Safety, Health and Environment'),
('Hysys'),
('Consim'),
('Chinese Language'),
('Environmental Risk Assessment'),
('HAZID and Hazop Safety Studies'),
('C Language Computer Programming'),
('Economics'),
('Mandarin'),
('Proficient in MacOs and Windows'),
('Proficient in the English Language '),
('Working level of Chinese and Bahasa Malaysia'),
('Spotfire'),
('Visual Basic Application (VBA)'),
('business planning'),
('retail marketing'),
('corporate social responsibilty'),
('Smart sketch'),
('Handover Control System'),
('Draft Sight'),
('Laser cutting'),
('3D printing'),
('Bandsaw'),
('C and C++'),
('Fast Learning '),
('Creative'),
('Professionalism'),
('Legal Research'),
('Public Speaking/Debating/Mooting/Negotiating'),
('Public relation'),
('Marketing and Advertisement'),
('MiniTab Statistics Software'),
('HTML Programming'),
('Microsoft SQL'),
('Radiant (Statistical Software)'),
('Tableau (Data Visualization Software)'),
('Programming: Python'),
('Programming: Arduino'),
('Programming: C'),
('CAD: Solidworks'),
('CAD: Autodesk Inventor'),
('Image Processing'),
('Proficient in Microsoft Office'),
('Decision Making'),
('Communicating'),
('Self-Management'),
('Thinking Skills'),
('Willingness to learn'),
('Resilient'),
('Computing Skills'),
('Cadence Design Systems'),
('Proteus Design Suite'),
('Robotic Operating System'),
('C programming language'),
('Gazebo simulation environment'),
('Finite Element Method Magnetics'),
('Machine design'),
('Altium Designer'),
('Filmora 9 Pro'),
('Pro II'),
('API'),
('Data Analytic'),
('Quantitative Analytics'),
('Econometrics'),
('Eviews'),
('agile development'),
('data management for data science'),
('indesign'),
('typography'),
('information security'),
('Batch'),
('front-end'),
('Assembly'),
('Chemical Process Safety'),
('Language'),
('Rescue Scuba Certified'),
('Advanced Scuba Certified'),
('Optimization'),
('Corporate Finance'),
('Engineering Economics Analysis'),
('Geologic Mapping'),
('Core Characterization'),
('Fluid Flow in Porous Media'),
('Formation Acidizing'),
('Identifying Zonal Isolation Process'),
('IOR/EOR Recovery Process'),
('Modelling '),
('Well Cementing'),
('Gohfer'),
('CMG'),
('Pressure Transient Analysis'),
('PVT Analysis'),
('Sapphire '),
('Schlumberger PIPESIM'),
('Microsoft Visual Basic'),
('Flexible'),
('CAM and CAD'),
('MathWorks MATLAB'),
('Fluid dynamics'),
('HVAC system'),
('Instrumentation'),
('Java Programming'),
('Python Programming'),
('Mechanical component design'),
('Quick learner'),
('Lean principles knowledge'),
('Advanced critical thinking'),
('Works well in diverse team environment'),
('CREO 3-D models'),
('Technical problem-solving'),
('Operations Management'),
('Financial Analysis'),
('Sensitivity Analysis'),
('Database Management'),
('Budgeting'),
('Financial Reporting'),
('Financial Management'),
('Time Value of Money'),
('Micro- and Macro-economics'),
('Business'),
('FEA simulation'),
('Software Design'),
('Manufacturing Process'),
('Xcode'),
('Vim'),
('ARM Assembly'),
('Mobile App Development'),
('Documentation'),
('Organizational Skills'),
('Conflict Management and Resolution Skills'),
('Employee Relations Skills '),
('Teamwork and Collaboration '),
('Analytical Skills '),
('Financial Modeling'),
('DCF modeling'),
('Microsoft Excel (Advanced Functions, Pivot Table, Simulation, Dashboard)'),
('Financial Modelling'),
('Cash Flow Analysis'),
('Hardness Testing'),
('Tensile Testing'),
('Metal Characterization'),
('Matlab (Programming)'),
('Corrosion Evaluation '),
('Impedance Testing'),
('High Temperature Furnace Operation'),
('Casting'),
('Electrospinning'),
('Computer Aided Design'),
('Scanning Electron Microscopy'),
('CREO Parametric and Design'),
('Microsoft Project Professional'),
('Bahasa Malaysia'),
('Google Docs'),
('Google Sheets'),
('Google Slides'),
('process flow diagram'),
('process instrumentation diagram'),
('Microsoft applications literate'),
('STATA (statistical tool) literate'),
('Bilingual (English and Malay language)'),
('Video Production'),
('Google Suite'),
('MS Word, Excel, Powerpoint '),
('Basic-Level Programming(Languages: C++, Python) '),
('Excellent Engineering Knowledge'),
('Excellent Technical Skills'),
('Competent'),
('Hardworking'),
('Energetic'),
('Great Team Player'),
('Excellent Communication Skills'),
('Fluency In 5 Languages (English, Mandarin, Bahasa Melayu, Tamil, Malayalam)'),
('Excellent Public Speaker'),
('HVAC Design '),
('Fracture Mechanics'),
('Thermodynamics 2'),
('Materials Engineering'),
('Finite Element Methods (FEM)'),
('Control Systems Design'),
('MAXQDA'),
('Computer-Aided Design'),
('Computational Fluid Dynamics'),
('Data Analyzing'),
('Engineering Design'),
('Circuit Analysis'),
('Control Systems'),
('Embedded Systems'),
('Signal and Systems'),
('Videography'),
('Adobe Creative Cloud'),
('Final Cut Pro'),
('macOS'),
('Microsoft Windows OS'),
('PRO/ll'),
('Proficient in English '),
('Attention to detail '),
('Good team player '),
('Self-discipline '),
('Proactive '),
('Autodesk Inventor Professional (3D CAD)'),
('Microsoft Visual'),
('Applied Physics'),
('Engineering Drawing'),
('Engineering Economics'),
('System Dynamics'),
('Energy Economics '),
('Sustainable Energy'),
('Environmental Engineering Research'),
('Resources & Environment Economics '),
('CADCAM'),
('FMEA'),
('Structural Analysis'),
('Reinforced Concrete Design'),
('Hydraulics Engineering'),
('Geotechnical Engineering'),
('Building Energy Audits'),
('Fluidsim'),
('Unity Pro'),
('Mindstorm'),
('Computer Modeling Group Softwares'),
('Microsoft Softwares'),
('Front-end Web Development'),
('iOS Programming'),
('Object-oriented Programming'),
('Customer Services'),
('Microsoft Excel VBA'),
('Ms Azure'),
('AKM Servo Driver'),
('Javascript Programming'),
('LTSpice Circuit Simulation and Design'),
('Cadence Circuit Layout, Simulation, and Design'),
('Surface characterization: AFM, TEM, SEM, XRD, BET, Tensiometer'),
('Thermal analyses: TGA, DSC. Chromatography: GPC, HPLC, GC'),
('Fundamental analytical: UV-VIS, TOC/TN, FTIR, Zetasizer'),
('Drilling fluids testing equipment: HTHP Filter Press, viscometer, hydrometer'),
('Arduino Programming '),
('PTC Creo Design'),
('Portfolio Management '),
('Real Estate Financing '),
('Time-management'),
('Adaptive to new environment '),
('separation process'),
('HTML, CSS and Javascript'),
('SPEEDA'),
('SAP ERP'),
('Design Expert'),
('Organizational'),
('Auto CAD'),
('Machine language '),
('Video graphic'),
('Plc'),
('Creo 3.0'),
('Wind'),
('Capital IQ'),
('C programming (beginner)'),
('Continuous drive for improvement'),
('Creative problem solving'),
('Ethics'),
('Facility planning'),
('Process Analysis'),
('ARENA'),
('Material Handling'),
('Inventory Control'),
('Operations Research'),
('Statistical software'),
('MS Office: Word, Excel, Access, PowerPoint, and MS Project'),
('MS Advanced Excel'),
('Smart Factory Simulation software'),
('MS Outlook'),
('Supply Chain Management '),
('Cost analysis, cost estimating skills for analyzing alternative solutions'),
('Statistical Modeling '),
('Big Data Analytic'),
('Hospitality'),
('Abaqus CAE'),
('IHT'),
('EES'),
('PROJECT'),
('SHAREPOINT'),
('Slack'),
('OUTLOOK'),
('Microsoft Office (Word, Excel, Powerpoint)'),
('Troubleshooting'),
('Information seeking'),
('Collaboration'),
('Verbal communication'),
('Active listening'),
('Korean'),
('Asyst'),
('SMS'),
('Wiring Installation'),
('microsoft Excell'),
('Engineering Software'),
('SOLAR OFF-GRID INSTALLATION'),
('MATLAB, C++, Microsoft Excel, CMG, Petrel, Communication'),
('multilingual in English, Mandarin, Malay and Cantonese'),
('Fluent in Korean Language'),
('business analytics'),
('equity research'),
('social media marketing'),
('data modelling'),
('Interpreting'),
('Social Media Operations'),
('TOPIK(Test of Proficiency In Korean) Grade 6 '),
('Administrative Assistance'),
('making friends'),
('Expert in Microsoft Ofiice, and familiar with Pr, Ps, Ai'),
('IT Skill: Microsoft Word, Microsoft Excel and Microsoft PowerPoint '),
('Simply video making'),
('6 Languages'),
('interpersonal and communication skills'),
('Report writing'),
('Inquisitive'),
('Mbal, Prosper, Gap - Software'),
('String communication'),
('Soft skills and hard skills'),
('Creative thinking skills'),
('Rhino'),
('Design Thinking'),
('Investment Analysis'),
('Intercultural Communication'),
('Adobe Photoshop and Adobe Illustrator'),
('Microsoft Office and Microsoft Visio'),
('MatLAB 2017 - 2018'),
('Aspen Plus V10'),
('3D Max Software Designing'),
('Iron CAD Computer simulation'),
('WinCurveFit'),
('English speaker'),
('First aid rescue'),
('Sima Pro'),
('Base Impact ADEME'),
('KiCAD'),
('LTSpice'),
('Adobe Photoshop / Affinity Photo'),
('Design for manufacture'),
('Testing and Commissioning'),
('Electronic Data Management'),
('Site Coordination'),
('Ecolizer 2.0'),
('LaTeX Overleaf'),
('Teamworks'),
('Finite Element Analyse'),
('SAM 7.0'),
('Data collection and analysis'),
('HAZOP '),
('HACCP'),
('Presentation Skill'),
('Team work'),
('Analytical skill'),
('CMG Simulator'),
('Basic knowledge of Microsoft Office'),
('Basic knowledge of SPSS'),
('Basic programming skills (Java)'),
('Able to listen to others'),
('Able to work with minimum supervision '),
('Conceptualizing'),
('Brainstorming'),
('Electrical Diagrams'),
('Power System'),
('Logistic'),
('Liquefied Natural Gas (LNG)'),
('Additive Manufacturing (3D Printing)'),
('SAP'),
('Presenting'),
('Adobe Premiere Pro '),
('Glodon Cubicost'),
('Bulk Mailing'),
('Tehnical analysis'),
('Fundamental analysis'),
('Presentation skills'),
('Equity'),
('Private equity'),
('Piping and Instrumentation Diagram'),
('SPMat'),
('Aveva Engineering'),
('Microsoft PowerPoints'),
('Data Science'),
('Data Visualization'),
('Data Analyst'),
('Q+'),
('SuperPro'),
('Piping & Instrumentation Drawings'),
('Mechanical Engineering'),
('Mechanical'),
('Engineering Industry'),
('Oil and Gas Industry'),
('German Language'),
('Web Dev'),
('Microsoft application literate (Word, Excel and PowerPoint)'),
('Tableau software'),
('Bilingual verbal and written presentation (Malay language and English)'),
('Event Planning and Management');
