CREATE TABLE `wp_career_fair`.`ref_city` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `val` VARCHAR(700)  CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ,
  `state_id` INT NOT NULL DEFAULT '0', 
  `country_id` INT NOT NULL DEFAULT '0', 
PRIMARY KEY (`ID`), UNIQUE(`val`, `state_id`, `country_id`), INDEX (`val`), INDEX (`state_id`), INDEX (`country_id`)) ENGINE = InnoDB;


INSERT INTO ref_city (val, state_id) VALUES ('Asahan', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Baloi', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Hitam', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bakri', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Anam', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Pahat', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bekok', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Benut', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Gambir', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Pasir', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chaah', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Endau', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gelang Patah', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gemas', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gerisek', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gugusan Taib Andak', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jementah', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Johor Bahru', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kahang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kluang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kampung Kenangan Tun Dr Ismail', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Tinggi', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kukup', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kulai', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Labis', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Layang-layang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Masai', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mersing', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Muar', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pagoh', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Paloh', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Panchor', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Parit Jawa', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Parit Raja', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Parit Sulong', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pasir Gudang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pekan Nenas', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pengerang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pontian', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rengit', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Segamat', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Skudai', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Semerah', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Senai', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Senggarang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Renggam', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Mati', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tangkak', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ulu Tiram', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Yong Peng', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sagil', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Kepong', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lenga', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Balang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gemas Baru', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Renggam', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Penawar', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ledang', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Nusajaya', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kulaijaya', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kangkar Pulai', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bakri Baru', '1'); 
INSERT INTO ref_city (val, state_id) VALUES ('Alor Setar', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Baling', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Baharu', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bedong', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gurun', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jitra', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Karangan', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kepala Batas', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kodiang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Kuala Muda', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Kedah', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Ketil', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Nerang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kulim', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kupang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Langgar', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Langkawi', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lunas', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Merbok', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Padang Serai', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pendang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pokok Sena', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Serdang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sik', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Petani', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Yan', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Changloon', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Bakap', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Kayu Hitam', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Empat', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Sarang Semut', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jeniang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Pegang', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sintok', '2'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Lanas', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bachok', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Cherang Ruku', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Dabong', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gua Musang', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jeli', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kem Desa Pahlawan', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ketereh', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Bharu', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Krai', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Machang', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Melor', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pasir Mas', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pasir Puteh', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pulai Chondong', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rantau Panjang', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanah Merah', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Temangan', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tumpat', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Wakaf Bharu', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Selising', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Balah', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kubang Kerian', '3'); 
INSERT INTO ref_city (val, state_id) VALUES ('Alor Gajah', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batang Melaka', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bemban', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Durian Tunggal', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jasin', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Sungai Baru', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lubok China', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Masjid Tanah', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Melaka', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Merlimau', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Rambai', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Udang', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tampin', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Kling', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Selandar', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Katil', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Keroh', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kem Trendak', '4'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bahau', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Kikir', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Durian Tipus', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gemencheh', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Johol', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Klawang', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Pilah', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Labu', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lenggeng', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Linggi', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mantin', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Nilai', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pasir Panjang', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pedas', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Port Dickson', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rantau', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rembau', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rompin', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seliau', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seremban', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seri Menanti', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Si Rusa', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Siliau', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Pertang', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Gadut', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Ipoh', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Titi', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Pelandok', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chuah', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lukut', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Teluk Kemang', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pengkalan Kempas', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jelebu', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Seri Jempol', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Juasseh', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Baru Jempol', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Baru Enstek', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Durian', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pusat Bandar Palong', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Senawang', '5'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Jengka', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Benta', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bentong', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Beserah', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Fraser', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chenor', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Dong', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gambang', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Genting Highlands', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jerantut', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Karak', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kemayan', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Lipis', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Rompin', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuantan', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lanchang', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lurah Bilut', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Maran', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mengkarak', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mentakab', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Muadzam Shah', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Padang Tengku', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pekan', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Raub', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ringlet', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Lembing', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Ruan', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanah Rata', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Temerloh', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Triang', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Tun Abdul Razak', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Cameron Highlands', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Bera', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sega', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Krau', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Brinchang', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Goh', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Balok', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Kuin', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chini', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Damak', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Koyan', '6'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Itam', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Balik Pulau', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Ferringhi', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bayan Lepas', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Mertajam', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Butterworth', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gelugor', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Georgetown', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Nibong Tebal', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Penaga', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Penang Hill', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Perai', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Permatang Pauh', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pulau Pinang', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Ampat', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Jawi', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Bungah', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tasek Gelugor', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Usm Pulau Pinang', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jelutong', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Maung', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kubang Semang', '7'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Tawar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bagan Datoh', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bagan Serai', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Gajah', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Kurau', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bruas', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bidor', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bota', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Changkat Keruing', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chemor', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chenderiang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chenderong Balai', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Enggor', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gerik', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gopeng', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Hutan Melintang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Klian Intan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ipoh', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kampar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kampung Gajah', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kampung Kepayang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kamunting', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Kangsar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Sepetang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lahat', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Langkap', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lenggong', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lumut', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Malim Nawar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mambang Di Awan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Manong', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Matang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Menglembu', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Padang Rengas', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pangkor', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pantai Remis', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Parit', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Parit Buntar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pengkalan Hulu', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pusing', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sauk', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Selama', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Selekoh', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Semanggol', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sitiawan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Slim River', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Siput', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Sumun', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungkai', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Taiping', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjung Malim', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Piandang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Rambutan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Tualang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tapah', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tapah Road', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Teluk Intan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Temoh', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Trong', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tronoh', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ulu Kinta', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ulu Bernam', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sg Siput (u)', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Behrang Stesen', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Trolak', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Dipang', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Kurau', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seri Manjung', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seri Iskandar', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lambor Kanan', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jeram', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chikus', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Changkat Jering', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gunong Semanggol', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simpang Ampat Semanggol', '8'); 
INSERT INTO ref_city (val, state_id) VALUES ('Arau', '9'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kaki Bukit', '9'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kangar', '9'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Perlis', '9'); 
INSERT INTO ref_city (val, state_id) VALUES ('Padang Besar', '9'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ampang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Banting', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batang Berjuntai', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batang Kali', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu 9 Cheras', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Arang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Batu Caves', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Beranang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Rotan', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Dengkil', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Hulu Langat', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jenjarom', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kajang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kapar', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Klang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kerling', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Kubu Bharu', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Lumpur', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Selangor', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pelabuhan Klang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Petaling Jaya', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Puchong', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pulau Carey', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pulau Ketam', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pulau Indah', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rasa', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Rawang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sabak Bernam', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sekinchan', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Semenyih', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sepang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Serendah', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Seri Kembangan', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Shah Alam', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Subang Jaya', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Ayer Tawar', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Besar', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Buloh', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Pelek', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Karang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjong Sepat', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Telok Panglima Garang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ukm Bangi', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Upm Serdang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Hulu Bernam', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Baru Bangi', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Cyberjaya', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Selayang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Baru Sungai Buloh', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ulu Yam Baru', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Gombak', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pandan', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Subang Airport', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Cheras', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lapangan Terbang Antarabangsa Sepang', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Puncak Alam', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bestari Jaya', '10'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ajil', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Besut', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Besi', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Dungun', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Jerteh', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Permaisuri', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kemaman', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kemasek', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kijal', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Berang', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Besut', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Terengganu', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Marang', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Paka', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kerteh', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Al Muktafi Billah Shah', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kampung Raja', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Cukai', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Tong', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ceneh', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bukit Payong', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Chalok', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Setiu', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ketengah Jaya', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ayer Puteh', '11'); 
INSERT INTO ref_city (val, state_id) VALUES ('Beaufort', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Beluran', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bongawan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Inanam', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Keningau', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Belud', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Kinabalu', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Marudu', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuala Penyu', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kudat', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kunak', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lahad Datu', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lamag', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Likas', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Membakut', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Menumbok', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Nabawan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Papar', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Penampang', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Ranau', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sandakan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Semporna', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sipitang', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tambunan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tamparuli', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tanjung Aru', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tawau', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tenom', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tuaran', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Kinabatangan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pamol', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Putatan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bandar Plaza Damansa', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Beverly', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tenghilan', '12'); 
INSERT INTO ref_city (val, state_id) VALUES ('Asajaya', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Balingian', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Baram', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bau', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bekenu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Belaga', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Belawai', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Betong', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bintangor', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Bintulu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Dalat', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Daro', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Debak', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Engkilili', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Julau', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kabong', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kanowit', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kapit', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kota Samarahan', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Kuching', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lawas', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Limbang', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lingga', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Long Lama', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lubok Antu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lundu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Matu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Miri', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Mukah', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Nanga Medamit', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Niah', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pekenu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pusa', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Roban', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Saratok', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sarikei', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sebauh', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sebuyau', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Serian', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Simunjan', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Song', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Spaoh', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sri Aman', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sundar', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tatau', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tebakang', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sibu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Tebedu', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Pakan', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sibuti', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Oya', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Maludam', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Lutong', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Siburan', '13'); 
INSERT INTO ref_city (val, state_id) VALUES ('Setapak', '14'); 
INSERT INTO ref_city (val, state_id) VALUES ('Sungai Besi', '14'); 
INSERT INTO ref_city (val, state_id) VALUES ('Labuan', '15'); 
INSERT INTO ref_city (val, state_id) VALUES ('Putrajaya', '16'); 


UPDATE ref_city SET country_id = 1 WHERE country_id = 0;
