CREATE TABLE `wp_career_fair`.`ref_field_study` 
( `ID` INT NOT NULL AUTO_INCREMENT , 
 `val` VARCHAR(700)  CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ,
 `category` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
PRIMARY KEY (`ID`), UNIQUE(`val`,`category`), INDEX (`val`), INDEX (`category`)) ENGINE = InnoDB;


-- ###############################################################################################
-- ###############################################################################################

insert into wp_career_fair.ref_field_study (val, category) VALUES  ('Advertising/Media','advertising-media'), 
 ('Agriculture/Aquaculture/Forestry','agriculture-aquaculture-forestry'), 
 ('Architecture','architecture'), 
 ('Art/Design/Creative Multimedia','art-design-creative-multimedia'), 
 ('Biology','biology'), 
 ('Biotechnology','biotechnology'), 
 ('Business Studies/Administration/Management','business-studies-administration-management'), 
 ('Chemistry','chemistry'), 
 ('Commerce','commerce'), 
 ('Computer Science/Information Technology','computer-science-information-technology'), 
 ('Dentistry','dentistry'), 
 ('Economics','economics'), 
 ('Education/Teaching/Training','education-teaching-training'), 
 ('Engineering (Aviation/Aeronautics/Astronautics)','engineering-aviation-aeronautics-astronautics'), 
 ('Engineering (Bioengineering/Biomedical)','engineering-bioengineering-biomedical'), 
 ('Engineering (Chemical)','engineering-chemical'), 
 ('Engineering (Civil)','engineering-civil'), 
 ('Engineering (Computer/Telecommunication)','engineering-computer-telecommunication'), 
 ('Engineering (Electrical/Electronic)','engineering-electrical-electronic'), 
 ('Engineering (Environmental/Health/Safety','engineering-environmental-health-safety'), 
 ('Engineering (Industrial)','engineering-industrial'), 
 ('Engineering (Marine)','engineering-marine'), 
 ('Engineering (Material Science)','engineering-material-science'), 
 ('Engineering (Mechanical)','engineering-mechanical'), 
 ('Engineering (Mechatronic/Electromechanical)','engineering-mechatronic-electromechanical'), 
 ('Engineering (Metal Fabrication/Tool & Die/Welding)','engineering-metal-fabrication-tool-die-welding'), 
 ('Engineering (Mining/Mineral)','engineering-mining-mineral'), 
 ('Engineering (Others)','engineering-others'), 
 ('Engineering (Petroleum/Oil/Gas)','engineering-petroleum-oil-gas'), 
 ('Finance/Accountancy/Banking','finance-accountancy-banking'), 
 ('Food & Beverage Services Management','food-beverage-services-management'), 
 ('Food Technology/Nutrition/Dietetics','food-technology-nutrition-dietetics'), 
 ('Geographical Science','geographical-science'), 
 ('Geology/Geophysics','geology-geophysics'), 
 ('History','history'), 
 ('Hospitality/Tourism/Hotel Management','hospitality-tourism-hotel-management'), 
 ('Human Resource Management','human-resource-management'), 
 ('Humanities/Liberal Arts','humanities-liberal-arts'), 
 ('Journalism','journalism'), 
 ('Law','law'), 
 ('Library Management','library-management'), 
 ('Linguistic/Languages','linguistic-languages'), 
 ('Logistic/Transportation','logistic-transportation'), 
 ('Maritime Studies','maritime-studies'), 
 ('Marketing','marketing'), 
 ('Mass Communications','mass-communications'), 
 ('Mathematics','mathematics'), 
 ('Medical Science','medical-science'), 
 ('Medicine','medicine'), 
 ('Music/Performing Arts Studies','music-performing-arts-studies'), 
 ('Nursing','nursing'), 
 ('Optometry','optometry'), 
 ('Personal Services','personal-services'), 
 ('Pharmacy/Pharmacology','pharmacy-pharmacology'), 
 ('Philosophy','philosophy'), 
 ('Physical Therapy/Physiotherapy','physical-therapy-physiotherapy'), 
 ('Physics','physics'), 
 ('Political Science','political-science'), 
 ('Property Development/Real Estate Management','property-development-real-estate-management'), 
 ('Protective Services & Management','protective-services-management'), 
 ('Psychology','psychology'), 
 ('Quantity Survey','quantity-survey'), 
 ('Science & Technology','science-technology'), 
 ('Secretarial','secretarial'), 
 ('Social Science/Sociology','social-science-sociology'), 
 ('Sports Science & Management','sports-science-management'), 
 ('Textile/Fashion Design','textile-fashion-design'), 
 ('Urban Studies/Town Planning','urban-studies-town-planning'), 
 ('Veterinary','veterinary'), 
 ('Others','others');