DROP TABLE IF EXISTS `wp_career_fair`.`ref_tcrep_child_current_edu`;
CREATE TABLE `wp_career_fair`.`ref_tcrep_child_current_edu` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `val` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
PRIMARY KEY (`ID`), UNIQUE(`val`), INDEX (`val`)) ENGINE = InnoDB;
INSERT INTO ref_tcrep_child_current_edu (val) VALUES ('Not Applicable'); 
INSERT INTO ref_tcrep_child_current_edu (val) VALUES ('Preschool'); 
INSERT INTO ref_tcrep_child_current_edu (val) VALUES ('Primary'); 
INSERT INTO ref_tcrep_child_current_edu (val) VALUES ('Secondary'); 
INSERT INTO ref_tcrep_child_current_edu (val) VALUES ('Tertiary'); 



DROP TABLE IF EXISTS `wp_career_fair`.`ref_yes_no_na`;
CREATE TABLE `wp_career_fair`.`ref_yes_no_na` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `val` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
PRIMARY KEY (`ID`), UNIQUE(`val`), INDEX (`val`)) ENGINE = InnoDB;
INSERT INTO ref_yes_no_na (val) VALUES ('Yes'); 
INSERT INTO ref_yes_no_na (val) VALUES ('No'); 
INSERT INTO ref_yes_no_na (val) VALUES ('N/A'); 

DROP TABLE IF EXISTS `wp_career_fair`.`ref_gender_mf`;
CREATE TABLE `wp_career_fair`.`ref_gender_mf` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `val` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
PRIMARY KEY (`ID`), UNIQUE(`val`), INDEX (`val`)) ENGINE = InnoDB;
INSERT INTO ref_gender_mf (val) VALUES ('Male'); 
INSERT INTO ref_gender_mf (val) VALUES ('Female'); 


DROP TABLE IF EXISTS `wp_career_fair`.`ref_nationality_country`;
CREATE TABLE `wp_career_fair`.`ref_nationality_country` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `val` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
PRIMARY KEY (`ID`), UNIQUE(`val`), INDEX (`val`)) ENGINE = InnoDB;
INSERT INTO ref_nationality_country (val) VALUES ('Afghanistan');
INSERT INTO ref_nationality_country (val) VALUES ('Albania');
INSERT INTO ref_nationality_country (val) VALUES ('Algeria');
INSERT INTO ref_nationality_country (val) VALUES ('American Samoa');
INSERT INTO ref_nationality_country (val) VALUES ('Andorra');
INSERT INTO ref_nationality_country (val) VALUES ('Angola');
INSERT INTO ref_nationality_country (val) VALUES ('Antigua and Barbuda');
INSERT INTO ref_nationality_country (val) VALUES ('Argentina');
INSERT INTO ref_nationality_country (val) VALUES ('Armenia');
INSERT INTO ref_nationality_country (val) VALUES ('Aruba');
INSERT INTO ref_nationality_country (val) VALUES ('Australia');
INSERT INTO ref_nationality_country (val) VALUES ('Austria');
INSERT INTO ref_nationality_country (val) VALUES ('Azerbaijan');
INSERT INTO ref_nationality_country (val) VALUES ('Bahamas, The');
INSERT INTO ref_nationality_country (val) VALUES ('Bahrain');
INSERT INTO ref_nationality_country (val) VALUES ('Bangladesh');
INSERT INTO ref_nationality_country (val) VALUES ('Barbados');
INSERT INTO ref_nationality_country (val) VALUES ('Belarus');
INSERT INTO ref_nationality_country (val) VALUES ('Belgium');
INSERT INTO ref_nationality_country (val) VALUES ('Belize');
INSERT INTO ref_nationality_country (val) VALUES ('Benin');
INSERT INTO ref_nationality_country (val) VALUES ('Bermuda');
INSERT INTO ref_nationality_country (val) VALUES ('Bhutan');
INSERT INTO ref_nationality_country (val) VALUES ('Bolivia');
INSERT INTO ref_nationality_country (val) VALUES ('Bosnia and Herzegovina');
INSERT INTO ref_nationality_country (val) VALUES ('Botswana');
INSERT INTO ref_nationality_country (val) VALUES ('Brazil');
INSERT INTO ref_nationality_country (val) VALUES ('British Virgin Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Brunei Darussalam');
INSERT INTO ref_nationality_country (val) VALUES ('Bulgaria');
INSERT INTO ref_nationality_country (val) VALUES ('Burkina Faso');
INSERT INTO ref_nationality_country (val) VALUES ('Burundi');
INSERT INTO ref_nationality_country (val) VALUES ('Cabo Verde');
INSERT INTO ref_nationality_country (val) VALUES ('Cambodia');
INSERT INTO ref_nationality_country (val) VALUES ('Cameroon');
INSERT INTO ref_nationality_country (val) VALUES ('Canada');
INSERT INTO ref_nationality_country (val) VALUES ('Cayman Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Central African Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Chad');
INSERT INTO ref_nationality_country (val) VALUES ('Channel Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Chile');
INSERT INTO ref_nationality_country (val) VALUES ('China');
INSERT INTO ref_nationality_country (val) VALUES ('Colombia');
INSERT INTO ref_nationality_country (val) VALUES ('Comoros');
INSERT INTO ref_nationality_country (val) VALUES ('Congo, Dem. Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Congo, Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Costa Rica');
INSERT INTO ref_nationality_country (val) VALUES ('Cote d\'Ivoire');
INSERT INTO ref_nationality_country (val) VALUES ('Croatia');
INSERT INTO ref_nationality_country (val) VALUES ('Cuba');
INSERT INTO ref_nationality_country (val) VALUES ('Curacao');
INSERT INTO ref_nationality_country (val) VALUES ('Cyprus');
INSERT INTO ref_nationality_country (val) VALUES ('Czech Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Denmark');
INSERT INTO ref_nationality_country (val) VALUES ('Djibouti');
INSERT INTO ref_nationality_country (val) VALUES ('Dominica');
INSERT INTO ref_nationality_country (val) VALUES ('Dominican Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Ecuador');
INSERT INTO ref_nationality_country (val) VALUES ('Egypt, Arab Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('El Salvador');
INSERT INTO ref_nationality_country (val) VALUES ('Equatorial Guinea');
INSERT INTO ref_nationality_country (val) VALUES ('Eritrea');
INSERT INTO ref_nationality_country (val) VALUES ('Estonia');
INSERT INTO ref_nationality_country (val) VALUES ('Eswatini');
INSERT INTO ref_nationality_country (val) VALUES ('Ethiopia');
INSERT INTO ref_nationality_country (val) VALUES ('Faroe Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Fiji');
INSERT INTO ref_nationality_country (val) VALUES ('Finland');
INSERT INTO ref_nationality_country (val) VALUES ('France');
INSERT INTO ref_nationality_country (val) VALUES ('French Polynesia');
INSERT INTO ref_nationality_country (val) VALUES ('Gabon');
INSERT INTO ref_nationality_country (val) VALUES ('Gambia, The');
INSERT INTO ref_nationality_country (val) VALUES ('Georgia');
INSERT INTO ref_nationality_country (val) VALUES ('Germany');
INSERT INTO ref_nationality_country (val) VALUES ('Ghana');
INSERT INTO ref_nationality_country (val) VALUES ('Gibraltar');
INSERT INTO ref_nationality_country (val) VALUES ('Greece');
INSERT INTO ref_nationality_country (val) VALUES ('Greenland');
INSERT INTO ref_nationality_country (val) VALUES ('Grenada');
INSERT INTO ref_nationality_country (val) VALUES ('Guam');
INSERT INTO ref_nationality_country (val) VALUES ('Guatemala');
INSERT INTO ref_nationality_country (val) VALUES ('Guinea');
INSERT INTO ref_nationality_country (val) VALUES ('Guinea-Bissau');
INSERT INTO ref_nationality_country (val) VALUES ('Guyana');
INSERT INTO ref_nationality_country (val) VALUES ('Haiti');
INSERT INTO ref_nationality_country (val) VALUES ('Holy See');
INSERT INTO ref_nationality_country (val) VALUES ('Honduras');
INSERT INTO ref_nationality_country (val) VALUES ('Hong Kong SAR, China');
INSERT INTO ref_nationality_country (val) VALUES ('Hungary');
INSERT INTO ref_nationality_country (val) VALUES ('Iceland');
INSERT INTO ref_nationality_country (val) VALUES ('India');
INSERT INTO ref_nationality_country (val) VALUES ('Indonesia');
INSERT INTO ref_nationality_country (val) VALUES ('Iran, Islamic Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Iraq');
INSERT INTO ref_nationality_country (val) VALUES ('Ireland');
INSERT INTO ref_nationality_country (val) VALUES ('Isle of Man');
INSERT INTO ref_nationality_country (val) VALUES ('Israel');
INSERT INTO ref_nationality_country (val) VALUES ('Italy');
INSERT INTO ref_nationality_country (val) VALUES ('Jamaica');
INSERT INTO ref_nationality_country (val) VALUES ('Japan');
INSERT INTO ref_nationality_country (val) VALUES ('Jordan');
INSERT INTO ref_nationality_country (val) VALUES ('Kazakhstan');
INSERT INTO ref_nationality_country (val) VALUES ('Kenya');
INSERT INTO ref_nationality_country (val) VALUES ('Kiribati');
INSERT INTO ref_nationality_country (val) VALUES ('Korea, Dem. People\'s Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Korea, Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Kosovo');
INSERT INTO ref_nationality_country (val) VALUES ('Kuwait');
INSERT INTO ref_nationality_country (val) VALUES ('Kyrgyz Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Lao PDR');
INSERT INTO ref_nationality_country (val) VALUES ('Latvia');
INSERT INTO ref_nationality_country (val) VALUES ('Lebanon');
INSERT INTO ref_nationality_country (val) VALUES ('Lesotho');
INSERT INTO ref_nationality_country (val) VALUES ('Liberia');
INSERT INTO ref_nationality_country (val) VALUES ('Libya');
INSERT INTO ref_nationality_country (val) VALUES ('Liechtenstein');
INSERT INTO ref_nationality_country (val) VALUES ('Lithuania');
INSERT INTO ref_nationality_country (val) VALUES ('Luxembourg');
INSERT INTO ref_nationality_country (val) VALUES ('Macao SAR, China');
INSERT INTO ref_nationality_country (val) VALUES ('Madagascar');
INSERT INTO ref_nationality_country (val) VALUES ('Malawi');
INSERT INTO ref_nationality_country (val) VALUES ('Malaysia');
INSERT INTO ref_nationality_country (val) VALUES ('Maldives');
INSERT INTO ref_nationality_country (val) VALUES ('Mali');
INSERT INTO ref_nationality_country (val) VALUES ('Malta');
INSERT INTO ref_nationality_country (val) VALUES ('Marshall Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Mauritania');
INSERT INTO ref_nationality_country (val) VALUES ('Mauritius');
INSERT INTO ref_nationality_country (val) VALUES ('Mexico');
INSERT INTO ref_nationality_country (val) VALUES ('Micronesia, Fed. Sts.');
INSERT INTO ref_nationality_country (val) VALUES ('Moldova');
INSERT INTO ref_nationality_country (val) VALUES ('Monaco');
INSERT INTO ref_nationality_country (val) VALUES ('Mongolia');
INSERT INTO ref_nationality_country (val) VALUES ('Montenegro');
INSERT INTO ref_nationality_country (val) VALUES ('Morocco');
INSERT INTO ref_nationality_country (val) VALUES ('Mozambique');
INSERT INTO ref_nationality_country (val) VALUES ('Myanmar');
INSERT INTO ref_nationality_country (val) VALUES ('Namibia');
INSERT INTO ref_nationality_country (val) VALUES ('Nauru');
INSERT INTO ref_nationality_country (val) VALUES ('Nepal');
INSERT INTO ref_nationality_country (val) VALUES ('Netherlands');
INSERT INTO ref_nationality_country (val) VALUES ('New Caledonia');
INSERT INTO ref_nationality_country (val) VALUES ('New Zealand');
INSERT INTO ref_nationality_country (val) VALUES ('Nicaragua');
INSERT INTO ref_nationality_country (val) VALUES ('Niger');
INSERT INTO ref_nationality_country (val) VALUES ('Nigeria');
INSERT INTO ref_nationality_country (val) VALUES ('North Macedonia');
INSERT INTO ref_nationality_country (val) VALUES ('Northern Mariana Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Norway');
INSERT INTO ref_nationality_country (val) VALUES ('Oman');
INSERT INTO ref_nationality_country (val) VALUES ('Pakistan');
INSERT INTO ref_nationality_country (val) VALUES ('Palau');
INSERT INTO ref_nationality_country (val) VALUES ('Palestine');
INSERT INTO ref_nationality_country (val) VALUES ('Panama');
INSERT INTO ref_nationality_country (val) VALUES ('Papua New Guinea');
INSERT INTO ref_nationality_country (val) VALUES ('Paraguay');
INSERT INTO ref_nationality_country (val) VALUES ('Peru');
INSERT INTO ref_nationality_country (val) VALUES ('Philippines');
INSERT INTO ref_nationality_country (val) VALUES ('Poland');
INSERT INTO ref_nationality_country (val) VALUES ('Portugal');
INSERT INTO ref_nationality_country (val) VALUES ('Puerto Rico');
INSERT INTO ref_nationality_country (val) VALUES ('Qatar');
INSERT INTO ref_nationality_country (val) VALUES ('Romania');
INSERT INTO ref_nationality_country (val) VALUES ('Russian Federation');
INSERT INTO ref_nationality_country (val) VALUES ('Rwanda');
INSERT INTO ref_nationality_country (val) VALUES ('Samoa');
INSERT INTO ref_nationality_country (val) VALUES ('San Marino');
INSERT INTO ref_nationality_country (val) VALUES ('Sao Tome and Principe');
INSERT INTO ref_nationality_country (val) VALUES ('Saudi Arabia');
INSERT INTO ref_nationality_country (val) VALUES ('Senegal');
INSERT INTO ref_nationality_country (val) VALUES ('Serbia');
INSERT INTO ref_nationality_country (val) VALUES ('Seychelles');
INSERT INTO ref_nationality_country (val) VALUES ('Sierra Leone');
INSERT INTO ref_nationality_country (val) VALUES ('Singapore');
INSERT INTO ref_nationality_country (val) VALUES ('Sint Maarten (Dutch part)');
INSERT INTO ref_nationality_country (val) VALUES ('Slovak Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Slovenia');
INSERT INTO ref_nationality_country (val) VALUES ('Solomon Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Somalia');
INSERT INTO ref_nationality_country (val) VALUES ('South Africa');
INSERT INTO ref_nationality_country (val) VALUES ('South Sudan');
INSERT INTO ref_nationality_country (val) VALUES ('Spain');
INSERT INTO ref_nationality_country (val) VALUES ('Sri Lanka');
INSERT INTO ref_nationality_country (val) VALUES ('St. Kitts and Nevis');
INSERT INTO ref_nationality_country (val) VALUES ('St. Lucia');
INSERT INTO ref_nationality_country (val) VALUES ('St. Martin (French part)');
INSERT INTO ref_nationality_country (val) VALUES ('St. Vincent and the Grenadines');
INSERT INTO ref_nationality_country (val) VALUES ('Sudan');
INSERT INTO ref_nationality_country (val) VALUES ('Suriname');
INSERT INTO ref_nationality_country (val) VALUES ('Sweden');
INSERT INTO ref_nationality_country (val) VALUES ('Switzerland');
INSERT INTO ref_nationality_country (val) VALUES ('Syrian Arab Republic');
INSERT INTO ref_nationality_country (val) VALUES ('Tajikistan');
INSERT INTO ref_nationality_country (val) VALUES ('Tanzania');
INSERT INTO ref_nationality_country (val) VALUES ('Thailand');
INSERT INTO ref_nationality_country (val) VALUES ('Timor-Leste');
INSERT INTO ref_nationality_country (val) VALUES ('Togo');
INSERT INTO ref_nationality_country (val) VALUES ('Tonga');
INSERT INTO ref_nationality_country (val) VALUES ('Trinidad and Tobago');
INSERT INTO ref_nationality_country (val) VALUES ('Tunisia');
INSERT INTO ref_nationality_country (val) VALUES ('Turkey');
INSERT INTO ref_nationality_country (val) VALUES ('Turkmenistan');
INSERT INTO ref_nationality_country (val) VALUES ('Turks and Caicos Islands');
INSERT INTO ref_nationality_country (val) VALUES ('Tuvalu');
INSERT INTO ref_nationality_country (val) VALUES ('Uganda');
INSERT INTO ref_nationality_country (val) VALUES ('Ukraine');
INSERT INTO ref_nationality_country (val) VALUES ('United Arab Emirates');
INSERT INTO ref_nationality_country (val) VALUES ('United Kingdom');
INSERT INTO ref_nationality_country (val) VALUES ('United States');
INSERT INTO ref_nationality_country (val) VALUES ('Uruguay');
INSERT INTO ref_nationality_country (val) VALUES ('Uzbekistan');
INSERT INTO ref_nationality_country (val) VALUES ('Vanuatu');
INSERT INTO ref_nationality_country (val) VALUES ('Venezuela, RB');
INSERT INTO ref_nationality_country (val) VALUES ('Vietnam');
INSERT INTO ref_nationality_country (val) VALUES ('Virgin Islands (U.S.)');
INSERT INTO ref_nationality_country (val) VALUES ('Yemen, Rep.');
INSERT INTO ref_nationality_country (val) VALUES ('Zambia');
INSERT INTO ref_nationality_country (val) VALUES ('Zimbabwe');


-- ################################################################################################################################################
-- ################################################################################################################################################
-- ################################################################################################################################################
-- ################################################################################################################################################
-- ################################################################################################################################################

DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_employ_status;

CREATE TABLE wp_career_fair.ref_tcrep_employ_status 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_employ_status (val) VALUES ('Unemployed');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Further Study');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Self-employed with no employees');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Full-time permanent employed');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Full-time contract employed');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Part-time contract employed');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Fixed-term contract employed');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Freelancers');
INSERT INTO ref_tcrep_employ_status (val) VALUES ('Own Business consisting employees');




DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_employ_role;

CREATE TABLE wp_career_fair.ref_tcrep_employ_role 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_employ_role (val) VALUES ('1111 Legislators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1112 Senior Government Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1113 Traditional Chiefs And Heads Of Village');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1114 Senior Officials Of Special-Interest Organisations');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1121 Managing Directors And Chief Executives');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1211 Finance Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1212 Human Resource Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1213 Policy And Planning Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1214 Business Services Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1215 Administrative Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1216 Quality Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1219 Business Services And Administration Managers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1221 Sales And Marketing Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1222 Advertising And Public Relations Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1223 Research And Development Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1311 Agricultural, Forestry And Livestock Production Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1312 Aquaculture And Fisheries Production Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1321 Manufacturing Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1322 Mining Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1323 Construction Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1324 Supply, Distribution And Related Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1411 Hotel And Homestay Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1412 Restaurant Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1421 Retail And Wholesale Trade Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1511 Information And Communications Technology Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1611 Child Care Services Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1612 Health Services Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1613 Aged Care Services Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1614 Social Welfare Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1615 Education Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1616 Financial And Insurance Services Branch Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1617 Legal Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1618 Property Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1619 Professional Services Managers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1621 Sports And Recreation Centre Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1622 Personal Care, Cleaning And Related Services Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1623 Security Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1624 Cultural Centre, Museum And Library Managers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('1629 Other Services Managers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2111 Physicists And Astronomers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2112 Meteorologists And Seismologists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2113 Chemists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2114 Geologists And Geophysicists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2121 Mathematicians, Actuaries And Statisticians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2131 Biologists, Botanists, Zoologists And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2132 Farming, Forestry, Plantation, And Fisheries Advisers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2133 Environmental Protection Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2134 Pharmacologists, Pathologists And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2141 Industrial And Production Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2142 Civil Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2143 Environmental Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2144 Mechanical Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2145 Chemical Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2146 Mining Engineers, Metallurgists And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2149 Engineering Professionals (Excluding Electrotechnology) Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2151 Electrical Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2152 Electronic Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2153 Telecommunications Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2161 Building Architects');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2162 Landscape Architects');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2163 Product And Garment Designers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2164 Town And Traffic Planners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2165 Cartographers And Surveyors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2166 Graphic And Multimedia Designers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2171 Ship Engineers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2172 Ship Deck Officers And Pilots');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2173 Aircraft Pilots And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2174 Air Traffic Controllers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2175 Train/ Locomotive Controllers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2179 Transport Controllers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2181 Mining Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2182 Manufacturing Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2183 Construction Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2211 Generalist Medical Practitioners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2212 Specialist Medical Practitioners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2221 Nursing Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2222 Midwifery Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2231 Traditional And Complementary Medicine Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2241 Paramedical Practitioners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2251 Veterinarians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2261 Dentists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2262 Pharmacists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2263 Environmental And Occupational Health And Hygiene Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2264 Physiotherapists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2265 Dieticians And Nutritionists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2266 Audiologists And Speech Therapists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2267 Optometrists And Ophthalmic Opticians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2268 Occupational Therapists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2269 Health Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2311 University And Higher Education Teaching Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2321 Vocational Education Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2331 Secondary School Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2341 Primary School Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2342 Early Childhood Educators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2351 Music Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2352 Arts Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2353 Performing Arts Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2361 Language Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2371 Religious Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2381 Vocational Training Officers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2391 Education Method Specialists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2392 Special Needs Teachers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2393 Information Technology Trainers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2399 Teaching Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2411 Accountants And Auditors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2412 Financial And Investment Advisers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2413 Financial Analysts');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2421 Management And Organisation Analysts');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2422 Policy Administration Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2423 Personnel And Career Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2424 Training And Staff Development Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2425 Administrative Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2426 Research And Development Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2431 Advertising And Marketing Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2432 Public Relations Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2433 Technical And Medical Sales Professionals (Excluding ICT)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2434 Information And Communications Technology (ICT) Sales Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2511 Computer Systems Analysts');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2512 Software Developers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2513 Web And Multimedia Developers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2514 Application Programmers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2519 Software And Application Developers And Analysts Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2521 Database Designers And Administrators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2522 Information Technology System Administrators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2523 Computer Network Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2524 Data Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2531 Cyber Security Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2541 Animation And Visual Effects Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2542 Digital Games And E-Sport Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2543 Creative Contents Designer Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2611 Lawyers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2612 Judges');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2619 Legal Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2711 Hotel Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2712 Restaurant Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2811 Archivists And Curators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2812 Librarians And Related Information Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2821 Economists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2822 Sociologists, Anthropologists And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2823 Philosophers, Historians And Political Scientists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2824 Psychologists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2825 Social Work And Counselling Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2826 Religious Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2831 Authors And Related Writers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2832 Journalists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2833 Translators, Interpreters And Other Linguists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2841 Visual Artists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2842 Musicians, Singers And Composers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2843 Dancers And Choreographers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2844 Film, Stage And Related Directors And Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2845 Actors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2846 Announcers On Radio, Television And Other Media');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2847 Clowns, Magicians, Acrobats And Related Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2848 Animal Keepers And Trainers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2849 Creative And Performing Artists Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2911 Professional Customs And Border Inspectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2912 Profesional Taxation And Excise Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2913 Professional Government Social Benefit Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2914 Professional Government Licensing Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2915 Professional Police Inspectors And Detectives');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2916 Professional Civil Defence Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('2919 Regulatory Government Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3111 Chemical And Physical Science Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3112 Civil Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3113 Electrical Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3114 Electronics Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3115 Mechanical Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3116 Chemical Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3117 Mining And Metallurgical Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3118 Draughtspersons And Surveying Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3119 Industrial And Production Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3121 Mining Supervisors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3122 Manufacturing Supervisors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3123 Construction Supervisors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3129 Other Supervisors Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3131 Power Production Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3132 Incinerator And Water Treatment Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3133 Chemical Processing Plant Controllers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3134 Petroleum And Natural Gas Refining Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3135 Metal Production Process Controllers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3139 Process Control Technicians Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3141 Life Science Technicians (Excluding Medical)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3142 Agricultural And Livestock Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3143 Forestry Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3144 Fishery Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3151 Aircraft Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3152 Ship/ Marine Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3153 Train/ Locomotive Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3154 Motor Vehicle Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3159 Transport Technicians Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3161 Nuclear Research And Development Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3211 Medical Imaging And Therapeutic Equipment Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3212 Medical And Pathology Laboratory Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3213 Pharmaceutical Technicians And Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3214 Medical And Dental Prosthetic Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3215 Orthotic And Prosthetic Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3221 Nursing Associate Professionals (Except Dental)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3222 Midwifery Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3231 Traditional And Complementary Medicine Associate   Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3241 Veterinary Technicians And Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3251 Dental Assistants And Therapists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3252 Medical Record And Health Information Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3253 Community Health Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3254 Dispensing Opticians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3255 Physiotherapy Technicians And Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3256 Medical Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3257 Environmental And Occupational Health Inspectors And Associates');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3258 Ambulance Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3259 Health Associate Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3311 Securities And Finance Dealers And Brokers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3312 Credit And Loan Officers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3313 Accounting And Auditing Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3314 Statistical, Mathematical And Actuarial Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3315 Valuers And Loss Assessors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3321 Insurance Representatives');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3322 Commercial Sales Representatives');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3323 Buyers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3324 Trade Brokers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3331 Clearing And Forwarding Agents');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3332 Conference And Event Agents');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3333 Employment Agents And Contractors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3334 Real Estate And Property Agents');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3339 Business Services Agents Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3341 Administrative Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3342 Legal Secretaries');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3343 Administrative And Executive Secretaries');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3344 Medical Secretaries');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3411 Legal And Related Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3511 Information And Communications Technology Operation Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3512 Information And Communications Technology User Support Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3513 Computer Network And Systems Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3514 Web Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3521 Broadcasting And Audio-Visual Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3522 Telecommunications Engineering Technicians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3611 Social Work Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3612 Religious Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3621 Athletes And Sports Players');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3622 Sports Coaches, Instructors And Officials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3623 Fitness And Recreation Instructors And Programme Leaders');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3631 Photographers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3632 Interior Designers And Decorators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3633 Gallery, Museum And Library Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3634 Cultural And Artistic Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3639 Artistic And Cultural Associate Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3641 Chefs');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3711 Customs And Border Inspector Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3712 Taxation And Excise Official Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3713 Government Social Benefit Official Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3714 Government Licensing Official Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3715 Police Officers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3716 Civil Defence Associate Professionals');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('3719 Regulatory Government Associate Professionals Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4111 General Office Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4121 Secretaries (General)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4131 Typist And Word Processor Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4132 Data Entry Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4211 Bank Tellers And Related Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4212 Bookmakers, Croupiers And Related Gaming Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4213 Pawnbrokers And Money-Lenders');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4214 Debt And Rent Collectors And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4221 Travel Consultants And Related Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4222 Contact Centre Information Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4223 Telephone Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4224 Receptionists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4225 Enquiry Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4226 Survey And Market Research Interviewers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4229 Client Information Workers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4311 Accounting And Book-Keeping Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4312 Statistical, Finance And Insurance Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4313 Payroll Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4321 Stock Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4322 Production Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4323 Transport Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4411 Library Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4412 Mail Carriers And Sorting Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4413 Coding, Proof-Reading And Related Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4414 Scribes And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4415 Filing And Copying Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4416 Personnel Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('4419 Clerical Support Workers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5111 Travel Attendants And Travel Stewards');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5112 Transport Conductors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5113 Travel Guides');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5121 Cooks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5131 Waiters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5132 Waiters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5141 Hairdressers, Beauticians And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5142 Hairdressers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5151 Building And Housekeeping Supervisors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5152 Cleaning And Housekeeping Supervisors In Offices, Hotels And Other Establishments');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5153 Domestic Housekeepers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5161 Other Personal Services Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5162 Astrologers, Fortune-Tellers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5163 Companions And Valets');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5164 Undertakers And Embalmers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5165 Pet Groomers And Animal Care Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5169 Driving Instructors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5211 Street And Market Salespersons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5212 Stall And Market Salespersons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5221 Shop Salespersons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5222 Shopkeepers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5223 Shop Supervisors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5231 Cashiers And Ticket Clerks');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5241 Other Sales Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5242 Fashion And Other Models');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5243 Sales Demonstrators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5244 Door-To-Door Salespersons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5245 Contact Centre Salespersons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5246 Service Station And Pump Attendants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5249 Food Counter Attendants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5311 Child Care Workers And Teachers\' Aides');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5312 Child Care Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5321 Personal Care Workers In Health Services');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5322 Health Care Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5329 Home-Based Personal Care Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5411 Protective Services Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5412 Fire Fighters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5413 Low Rank Police Officers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5414 Prison Guards');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5415 Security Guards');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('5419 Immigration/ Customs Officers And Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6111 Market Gardeners And Crop Growers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6112 Field Crop Growers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6113 Shrub Crop Growers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6114 Gardeners, Horticultural And Nursery Growers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6115 Mixed Crop Growers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6121 Animal Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6122 Livestock And Dairy Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6123 Poultry Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6129 Apiarists And Sericulturists');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6131 Mixed Crop And Animal Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6211 Skilled Forestry And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6221 Skilled Fishery Workers, Hunters And Trappers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6222 Fishery And Aquaculture Producers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6223 Skilled Inland And Coastal Waters Fishery Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6224 Skilled Deep-Sea Fishery Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6311 Subsistence Crop Farmers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6321 Subsistence Livestock Farmers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6331 Subsistence Mixed Crop And Livestock Farmers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('6341 Subsistence Fisherman, Hunters, Trappers And Gatherers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7111 Building Frame And Related Trades Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7112 House Builders And Construction Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7113 Bricklayers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7114 Stonemasons, Stone Cutters, Splitters And Carvers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7115 Concrete Placers, Concrete Finishers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7119 Carpenters And Joiners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7121 Building Finishers And Related Trades Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7122 Roofers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7123 Floor Layers And Tile Setters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7124 Plasterers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7125 Insulation Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7126 Glaziers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7127 Plumbers And Pipe Fitters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7131 Painters, Building Structure Cleaners And Related Trades Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7132 Painters And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7133 Spray Painters And Varnishers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7211 Sheet And Structural Metal Workers, Moulders And Welders And Related Trades Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7212 Metal Moulders And Coremakers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7213 Welders And Flame Cutters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7214 Sheet-Metal Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7215 Structural-Metal Preparers And Erectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7221 Blacksmiths, Toolmakers And Related Trades Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7222 Blacksmiths, Hammersmiths And Forging-Press Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7223 Toolmakers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7224 Metal Working Machine Tool Setters And Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7231 Machinery Mechanics And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7232 Motor Vehicle Mechanics And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7233 Aircraft Engine Mechanics And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7234 Agricultural And Industrial Machinery Mechanics And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7239 Bicycle And Related Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7311 Handicraft Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7312 Precision Instrument Makers And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7313 Musical Instrument Makers And Tuners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7314 Jewellery And Precious Metal Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7315 Potters And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7316 Glass Makers, Cutters, Grinders And Finishers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7317 Sign Writers, Decorative Painters, Engravers And Etchers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7318 Handicraft Workers In Wood, Basketry And Related Materials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7319 Handicraft Workers In Textile, Leather And Related Materials');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7321 Pre-Press Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7322 Printers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7323 Print Finishing And Binding Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7324 Printing And Photo Engravers And Etchers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7411 Building And Related Electricians');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7412 Electrical Mechanics And Fitters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7413 Electrical Line Installers And Repairers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7421 Electronics Mechanics And Services');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7422 Information And Communications Technology Installers And Services');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7511 Meat And Fish Processing Workers And Related Food Preparers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7512 Bakers, Pastry And Pasta-Cooks, And Confectionery Makers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7513 Dairy-Product Makers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7514 Fruit, Vegetable And Related Preservers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7515 Food And Beverage Tasters And Graders');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7516 Tobacco Preparers And Tobacco Product Makers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7611 Wood Treaters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7612 Cabinet-Makers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7613 Woodworking-Machine Tool Setters And Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7621 Tailors, Dressmakers, Furriers And Hatters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7622 Garment And Related Pattern-Makers And Cutters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7623 Shoemakers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7624 Upholsterers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7625 Pelt Dressers, Tanners And Fellmongers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7631 Underwater Divers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7632 Shotfirers And Blasters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7633 Product Graders And Testers (Excluding Foods And Beverages)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7634 Fumigators And Pest And Weed Controllers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('7639 Other Related Craft Workers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8111 Miners And Quarry Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8112 Mineral And Stone Processing Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8113 Well Drillers And Borers And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8114 Cement, Stone And Other Mineral Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8121 Metal Processing Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8122 Metal Finishing, Plating And Coating Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8131 Chemical Products Plant And Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8132 Photographic Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8141 Rubber Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8142 Plastic Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8143 Paper Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8151 Fibre Preparing, Spinning And Winding Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8152 Weaving And Knitting Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8153 Sewing Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8154 Bleaching, Dyeing And Fabric Cleaning Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8155 Fur And Leather Preparing Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8156 Shoemaking And Related Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8157 Laundry Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8159 Textile, Fur And Leather Products Machine Operators Not Elesewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8161 Food And Related Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8171 Pulp And Papermaking Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8172 Wood Processing Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8173 Wood Products Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8181 Glass And Ceramics Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8182 Steam Engine And Boiler Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8183 Packing, Bottling And Labelling Machine Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8189 Stationary Plant And Machine Operators Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8211 Mechanical Machinery Assemblers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8212 Electrical And Electronic Equipment Assemblers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8213 Leather, Metal, Rubber And Plastic Products Assemblers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8219 Assemblers Not Elsewhere Classified');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8221 Machine-Tool Setter-Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8311 Locomotive Engine Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8312 Railway Brake, Signal And Switch Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8321 Motorcycle Riders (Drivers)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8322 Car, Taxi And Van Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8331 Bus And Tram Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8332 Heavy Truck And Lorry Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8341 Mobile Farm And Forestry Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8342 Earth-Moving And Related Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8343 Crane, Hoist And Related Plant Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8344 Lifting Truck Operators');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('8351 Ships Deck Crews And Related Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9111 Domestic, Hotel And Office Cleaners And Helpers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9112 Domestic Cleaners And Helpers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9121 Vehicle, Window, Laundry And Other Hand Cleaning Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9122 Hand Launderers And Ironers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9123 Vehicle Cleaners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9129 Surface And Window Cleaners');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9211 Agricultural, Forestry, Farming And Fishery Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9212 Crop Farm Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9213 Livestock Farm Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9214 Mixed Crop And Livestock Farm Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9215 Garden And Horticultural Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9216 Forestry Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9219 Fishery And Aquaculture Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9311 Mining And Construction Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9312 Mining And Quarrying Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9313 Civil Engineering Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9321 Manufacturing Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9329 Manufacturing Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9331 Transport And Storage Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9332 Hand Or Pedal Vehicle Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9333 Animal-Drawn Machinery And Vehicle Drivers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9334 Transport And Storage Labourers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9411 Food Preparation Assistants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9412 Fast Food Preparers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9511 Street And Related Service Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9521 Street Vendors (Excluding Food)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9611 Garbage Collectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9612 Garbage Collectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9613 Refuse And Recyclable Waste Sorters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9621 Other Elementary Workers');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9622 Messengers, Package Deliverers And Luggage Porters');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9623 Odd-Job Persons');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9624 Meter Readers And Vending-Machine Collectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9625 Water And Firewood Collectors');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('9629 Attendants');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0111 Professional Duty Officers (Malaysian Army)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0121 General Duty Officers (Malaysian Army)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0131 Personnel Of Other Ranks (Malaysian Army)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0211 General Duty Officers (Royal Malaysian Navy)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0221 Personnel Of Other Ranks (Royal Malaysian Navy)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0311 General Duty Officers (Royal Malaysian Air Force)');
INSERT INTO ref_tcrep_employ_role (val) VALUES ('0321 Personnel Of Other Ranks (Royal Malaysian Air Force)');


DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_employ_industry;

CREATE TABLE wp_career_fair.ref_tcrep_employ_industry 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_employ_industry (val) VALUES ('A -  Agriculture, forestry and fishing');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('B -  Mining and quarrying');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('C -  Manufacturing');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('D -  Electricity, gas, steam and air conditioning supply');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('E -  Water supply; sewerage, waste management and remediation activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('F - Construction');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('G - Wholesale and retail trade; repair of motor vehicles and motorcycles');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('H - Transportation and storage');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('I -  Accommodation and food service activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('J -  Information and communication');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('K -  Financial and insurance/takaful activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('L -  Real estate activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('M -  Professional, scientific and technical activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('N -  Administrative and support service activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('O -  Public administration and defence; compulsory social security');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('P -  Education');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('Q -  Human health and social work activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('R - Arts, entertainment and recreation');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('S -  Other service activities');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('T -  Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use');
INSERT INTO ref_tcrep_employ_industry (val) VALUES ('U -  Activities of extraterritorial organizations and bodies');



DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_qualification;

CREATE TABLE wp_career_fair.ref_tcrep_qualification 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_qualification (val) VALUES ('No formal education');
INSERT INTO ref_tcrep_qualification (val) VALUES ('UPSR Level');
INSERT INTO ref_tcrep_qualification (val) VALUES ('PMR/PT3 Level');
INSERT INTO ref_tcrep_qualification (val) VALUES ('SKM Level 1 & 2');
INSERT INTO ref_tcrep_qualification (val) VALUES ('SPM Level');
INSERT INTO ref_tcrep_qualification (val) VALUES ('STPM Level / Matriculation / Foundation / Pre-University Program');
INSERT INTO ref_tcrep_qualification (val) VALUES ('SKM Level 3');
INSERT INTO ref_tcrep_qualification (val) VALUES ('Diploma / SKM Level 4');
INSERT INTO ref_tcrep_qualification (val) VALUES ('Advanced Diploma / SKM Level 5');
INSERT INTO ref_tcrep_qualification (val) VALUES ('Bachelor’s Degree / Graduate Diploma / Graduate Certificate');
INSERT INTO ref_tcrep_qualification (val) VALUES ('Master’s Degree (by Research or Mixed Mode & Coursework) / Postgraduate Diploma / Postgraduate Certificate');
INSERT INTO ref_tcrep_qualification (val) VALUES ('PhD / Doctoral Degree');
INSERT INTO ref_tcrep_qualification (val) VALUES ('Others (Please specify in field below)');




DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_field_study;

CREATE TABLE wp_career_fair.ref_tcrep_field_study 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_field_study (val) VALUES ('0000 Generic programmes and qualifications not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0011 Basic programmes and qualifications');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0021 Literacy and numeracy');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0031 Personal skills');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0099 Generic programmes and qualifications not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0110 Education not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0111 Education science');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0112 Training for pre-school teachers');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0113 Educator training without subject specialisation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0114 Educator training with subject specialisation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0119 Programmes and qualifications involving education not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0188 Inter-disciplinary programmes and qualifications involving education');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0200 Arts and humanities not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0211 Audio-visual techniques and media production');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0212 Fashion, interior and industrial design');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0213 Fine arts');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0214 Craft skills');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0215 Music and performing arts');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0216 Film, television and screen studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0219 Arts not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0221 Religion and theology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0222 History and archaeology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0223 Philosophy and ethics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0224 Islamic studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0229 Humanities (except languages) not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0231 Language acquisition');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0232 Literature and linguistics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0233 National language');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0239 Languages not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0288 Inter-disciplinary programmes and qualifications involving arts and humanities');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0299 Arts and humanities not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0300 Social sciences, journalism and information not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0311 Economics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0312 ical Sciences and Public Policy');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0313 Psychology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0314 Sociology and cultural studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0319 Social and behavioural sciences not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0321 Journalism and reporting');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0322 Library, information and archival studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0323 Media and communication');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0329 Journalism, information and communication not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0388 Inter-disciplinary programmes and qualifications involving social sciences, journalism and information');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0399 Social sciences, journalism and information not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0400 Business, administration and law not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0411 Accounting, auditing and taxation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0412 Finance, banking and insurance');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0413 Islamic banking and finance');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0414 Management and administration');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0415 Marketing and advertising');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0416 Secretarial and office studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0417 Work skills');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0419 Business and administration not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0421 Law');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0488 Inter-disciplinary programmes and qualifications involving business, administration and law');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0499 Business, administration and law not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0500 Natural sciences, mathematics and statistics not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0511 Biology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0512 Biochemistry');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0519 Biological and related sciences not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0521 Environmental sciences');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0522 Natural environments and wildlife');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0529 Environment not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0531 Chemistry');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0532 Earth sciences');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0533 Physics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0539 Physical sciences not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0540 Mathematics and statistics not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0541 Mathematics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0542 Statistics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0588 Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0599 Natural sciences, mathematics and statistics not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0610 Information and communication technologies (ICTs) not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0611 Information technology and information system');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0612 Software engineering');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0613 Computer science');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0614 Computer use');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0619 Information and communication technologies (ICTs) not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('"0688 Inter-disciplinary programmes and qualifications involving information and');
INSERT INTO ref_tcrep_field_study (val) VALUES ('communication technologies"');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0700 Engineering, manufacturing and construction not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0711 Chemical engineering and processes');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0712 Electricity and energy');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0713 Electronics and automation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0714 Mechanics and metal trades');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0715 Motor vehicles, ships and aircraft');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0716 Civil engineering');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0717 Environmental protection technology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0719 Engineering and engineering trades not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0721 Food processing');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0722 Materials (glass, paper, plastic and wood)');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0723 Textiles (clothes, footwear and leather)');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0724 Mining and extraction');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0729 Manufacturing and processing not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0731 Architecture');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0732 Urban and regional planning');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0733 Building and construction');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0734 Surveying');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0741 Engineering technology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('"0788 Inter-disciplinary programmes and');
INSERT INTO ref_tcrep_field_study (val) VALUES ('qualifications involving engineering, manufacturing and construction"');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0799 Engineering, manufacturing and construction not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0800 Agriculture, forestry, fisheries and veterinary not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0811 Crop and livestock production');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0812 Horticulture');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0819 Agriculture not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0821 Forestry');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0831 Fisheries');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0841 Veterinary');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0888 Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0899 Agriculture, forestry, fisheries and veterinary not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0900 Health and welfare not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0911 Dental studies');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0912 Medicine');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0913 Nursing, midwifery and medical assistance');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0914 Medical diagnostic and treatment technology');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0915 Therapy and rehabilitation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0916 Pharmacy');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0917 Traditional and complementary medicine and therapy');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0919 Health not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0921 Care of elderly and of disabled adults');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0922 Child care and youth services');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0923 Social work and counselling');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0929 Welfare not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0988 Inter-disciplinary programmes and qualifications involving health and welfare');
INSERT INTO ref_tcrep_field_study (val) VALUES ('0999 Health and welfare not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1000 Services not further defined');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1011 Domestic services');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1012 Hair and beauty services');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1013 Hotel, restaurants and catering');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1014 Sports');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1015 Travel, tourism and leisure');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1019 Personal services not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1021 Community sanitation');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1022 Occupational health and safety');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1029 Hygiene and occupational health services not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1031 Military and defence');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1032 Protection of persons and property');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1039 Security services not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1041 Transport services');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1088 Inter-disciplinary programmes and qualifications involving services');
INSERT INTO ref_tcrep_field_study (val) VALUES ('1099 Services not elsewhere classified');
INSERT INTO ref_tcrep_field_study (val) VALUES ('9999 Field unknown');

DROP TABLE IF EXISTS wp_career_fair.ref_tcrep_preferred_job_location;

CREATE TABLE wp_career_fair.ref_tcrep_preferred_job_location 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Federal Territory/ Kuala Lumpur');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Federal territory/ Labuan');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Federal Territory/ Putrajaya');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Johor');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Kedah');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Kelantan');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Melaka');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Negeri Sembilan');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Pahang');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Penang');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Perak');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Perlis');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Sabah');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Sarawak');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Selangor');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Terengganu');
INSERT INTO ref_tcrep_preferred_job_location (val) VALUES ('Others');
