INSERT INTO ref_university (val, country_id)
("AIMST University", 1),
("Admal Aviation College", 1),
("Advance Tertiary College (ATC) Kuala Lumpur", 1),
("AeU - Asia e University", 1),
("Asia Pacific Institute of Information Technology (APIIT)", 1),
("Al-Madinah International University", 1),
("ALAM - Akademi Laut Malaysia", 1),
("AMU - Asia Metropolitan University", 1),
("Asia Pacific University of Technology & Innovation (APU)", 1),
("Arte Academy", 1),
("Aviation Management College", 1),
("Asean Culinary Academy", 1),
("ALFA International College", 1),
("ATI College", 1),
("Advance Tertiary College (ATC) Penang", 1),
("Allied Aeronautics Training Centre", 1),
("Al-Maktoum College", 1),
("Asia School of Business (ASB)", 1),
("Academi GA", 1),
("Binary University of Management and Entrepreneurship", 1),
("BERJAYA University College of Hospitality", 1),
("BCM - Bible College of Malaysia", 1),
("Brickfields Asia College (BAC) Kuala Lumpur", 1),
("Brickfields Asia College (BAC) Petaling Jaya", 1),
("British Council Malaysia", 1),
("British Council - The Curve", 1),
("British Council - Penang", 1),
("Curtin University, Malaysia", 1),
("City University Malaysia", 1),
("Cilantro Culinary Academy", 1),
("Claz'room College", 1),
("Crescendo International College", 1),
("Consist College", 1),
("Chartered Institute of Management Accountants (CIMA)", 1),
("DRB-Hicom University of Automotive Malaysia", 1),
("Dasien Academy of Art", 1),
("Disted College", 1),
("Despark College", 1),
("East West International College", 1),
("Erican College", 1),
("Ecole De Patisserie", 1),
("Equator College", 1),
("Edinburgh Napier University", 1),
("First City University College", 1),
("Flamingo International College", 1),
("FTMS College", 1),
("Famous Chef Professional Baking & Culinary Academy", 1),
("Geospatial Science and Technology College (GSTC)", 1),
("GlobalNxt University", 1),
("Geomatika College International", 1),
("GMI - German-Malaysian Institute", 1),
("HELP University", 1),
("HELP CAT - HELP College of Arts and Technology", 1),
("Han Chiang University College of Communication", 1),
("HMA - HM Aerospace", 1),
("Heriot-Watt University Malaysia", 1),
("Infrastructure University Kuala Lumpur (IUKL)", 1),
("INTEC Education College", 1),
("INCEIF - International Centre for Education in Islamic Finance", 1),
("IMU - International Medical University", 1),
("IUCTT - International University College of Technology Twintech", 1),
("INTI International University", 1),
("IACT College", 1),
("IMPERIA Institute of Technology", 1),
("ICOM - International College Of Music", 1),
("International University of Malaya-Wales (IUMW)", 1),
("ICYM - International College of Yayasan Melaka", 1),
("IMC - International Medical College", 1),
("IBS College", 1),
("International Islamic College (IIC)", 1),
("Inter Excel Tourism Academy (IETA)", 1),
("Institute of Chartered Accountants in England and Wales", 1),
("Kolej Yayasan UEM (KYUEM)", 1),
("KDU University College", 1),
("KUIS - Selangor International Islamic University College", 1),
("KLT - Kolej Laila Taib", 1),
("KTS - Kolej TAFE Seremban", 1),
("KUIM - Islamic University College of Melaka", 1),
("KPJ Healthcare University College", 1),
("KFCH International College", 1),
("KTT - Kolej Teknologi Timur", 1),
("KTAC - Cybernetics International College of Technology", 1),
("Kolej Yayasan Sabah", 1),
("Kolej Teknologi Darulnaim", 1),
("KLIA Professional & Management College", 1),
("KYS Business School (KYSB)", 1),
("Kuala Lumpur Metropolitan University College (KLMUC)", 1),
("Kolej Universiti Poly-Tech MARA (KUPTM)", 1),
("KDU Penang University College", 1),
("Kings College Malaysia", 1),
("LimKokWing University", 1),
("Linton University College", 1),
("Life College Malaysia", 1),
("Lincoln University College (LUC)", 1),
("MSU - Management & Science University", 1),
("Medic ED Consultant Sdn Bhd", 1),
("MAHSA University", 1),
("MUST - Malaysia University of Science and Technology", 1),
("Monash University Malaysia", 1),
("MMU - Multimedia University", 1),
("Manipal International University (MIU) Nilai", 1),
("MMMC - Melaka Manipal Medical College", 1),
("MFA - Malaysian Flying Academy", 1),
("Methodist College Kuala Lumpur (MCKL)", 1),
("Malaysian Institute of Art (MIA)", 1),
("Malvern International Academy", 1),
("Mantissa College", 1),
("MAHSA Prima International College", 1),
("Meritus University", 1),
("Metropoint College", 1),
("Nilai University", 1),
("NMIT - Netherlands Maritime Institute of Technology", 1),
("NuMED - Newcastle University Medicine Malaysia", 1),
("New Era University College", 1),
("North Borneo University College (NBUC)", 1),
("Naza College of Technology and Business", 1),
("OUM - Open University Malaysia", 1),
("Olympia College", 1),
("Optopreneur College", 1),
("PIC - Putra International College", 1),
("Perdana University", 1),
("PIDC - Penang International Dental College", 1),
("PTPL - Pusat Teknologi & Pengurusan Lanjutan College", 1),
("PIIC - Putra Intelek International College", 1),
("Portman College", 1),
("Putra Business School", 1),
("Point College", 1),
("President's College", 1),
("Pintar College", 1),
("Peninsula College", 1),
("QIU - Quest International University Perak", 1),
("Raffles University", 1),
("Ramsay Sime Darby Healthcare College", 1),
("Raffles College of Higher Education", 1),
("RCSI & UCD Malaysia Campus (RUMC) - formerly known as Penang Medical College", 1),
("RENG College of Technology and Design", 1),
("Reliance College", 1),
("Ranaco Education and Training Institute (RETI)", 1),
("SEGi University & Colleges", 1),
("Stamford College", 1),
("Swinburne University of Technology Sarawak Campus", 1),
("Sunway University", 1),
("Southern University College", 1),
("Saito University College", 1),
("Sunway College", 1),
("Sentral College Penang", 1),
("SPACE College (Kolej SPACE)", 1),
("Silverspoon International College (SSiC)", 1),
("Sunway Le Cordon Bleu", 1),
("SEGi University & Colleges Penang", 1),
("SEGi University & Colleges Sarawak", 1),
("SEGi University & Colleges Kuala Lumpur", 1),
("SEGi University & Colleges Subang Jaya", 1),
("SPACE - School of Professional and Continuing Education", 1),
("Selangor Business School (SBS)", 1),
("TAR UC - Tunku Abdul Rahman University College", 1),
("Taylor's University", 1),
("The One Academy", 1),
("TOC - The Otomotif College", 1),
("TMC College", 1),
("Travex International College", 1),
("TAJ International College", 1),
("TAR UC - Tunku Abdul Rahman University College Johor Branch Campus", 1),
("TAR UC - Tunku Abdul Rahman University College Pahang Faculty Branch", 1),
("TAR UC - Tunku Abdul Rahman University College Penang Branch Campus", 1),
("TAR UC - Tunku Abdul Rahman University College Perak Branch Campus", 1),
("TAR UC - Tunku Abdul Rahman University College Sabah Faculty Branch", 1),
("Taylor's College", 1),
("Tung Shin Academy of Nursing", 1),
("Universiti Teknologi PETRONAS (UTP)", 1),
("Universiti Kebangsaan Malaysia (UKM)", 1),
("University of Southampton Malaysia", 1),
("University College of Technology Sarawak (UCTS)", 1),
("University of Nottingham Malaysia Campus", 1),
("UM - University of Malaya", 1),
("UUM - Universiti Utara Malaysia", 1),
("Universiti Tun Hussein Onn Malaysia", 1),
("UniRazak - Universiti Tun Abdul Razak", 1),
("UiTM - Universiti Teknologi Mara", 1),
("UTM - Universiti Teknologi Malaysia", 1),
("UTeM - Universiti Teknikal Malaysia Melaka", 1),
("Universiti Sultan Zainal Abidin", 1),
("UNISEL - Universiti Selangor", 1),
("USM - Universiti Sains Malaysia", 1),
("USIM - Universiti Sains Islam Malaysia", 1),
("UPM - Universiti Putra Malaysia", 1),
("UPSI - Universiti Pendidikan Sultan Idris", 1),
("UMT - Universiti Malaysia Terengganu", 1),
("UNIMAS - Universiti Malaysia Sarawak", 1),
("UMS - Universiti Malaysia Sabah", 1),
("UNIMAP - Universiti Malaysia Perlis", 1),
("UMP - Universiti Malaysia Pahang", 1),
("Universiti Malaysia Kelantan", 1),
("UniKL - Universiti Kuala Lumpur", 1),
("UCSI University Malaysia", 1),
("UPNM - Universiti Pertahanan Nasional Malaysia", 1),
("UNITAR International University", 1),
("University College TATI (UC TATI)", 1),
("Universiti Tenaga Nasional (UNITEN)", 1),
("UoC - University of Cyberjaya", 1),
("Universiti Islam Antarabangsa Sultan Abdul Halim Mu'adzam Shah (UniSHAMS)", 1),
("University of Reading Malaysia", 1),
("UniMy - University Malaysia of Computer Science & Engineering", 1),
("UniKL MIAT - Universiti Kuala Lumpur Malaysian Institute of Aviation Technology", 1),
("UCAM - University College of Agroscience Malaysia", 1),
("UCSI College", 1),
("UC Bestari - University College Bestari", 1),
("UNITI College", 1),
("Unikop College", 1),
("UNDO Academy", 1),
("University of London International Programmes", 1),
("Universiti Tunku Abdul Rahman (UTAR) Sungai Long", 1),
("Universiti Tunku Abdul Rahman (UTAR) Kampar", 1),
("University of Malaya Centre for Continuing Education (UMCCed)", 1),
("Universiti Sultan Azlan Shah", 1),
("VTAR Institute", 1),
("Vision College", 1),
("Victoria International College", 1),
("VUC - Veritas University College", 1),
("WOU - Wawasan Open University", 1),
("Widad University College", 1),
("WIC - Westminster International College", 1),
("Widad College", 1),
("WIM College - The Women Institute of Management", 1),
("XMUMC - Xiamen University Malaysia Campus", 1),
("YTL International College of Hotel Management", 1),
("YPC International College", 1),
("Young Aces Technical College", 1),


-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################
-- ##########################################################################################

INSERT INTO ref_university (val, country_id) VALUES("Marywood University", 840),
("Lindenwood University", 840),
("Sullivan University", 840),
("Florida State College at Jacksonville", 840),
("Xavier University", 840),
("Tusculum College", 840),
("Claremont School of Theology", 840),
("Columbia College (SC)", 840),
("Chabot-Las Positas Community College District", 840),
("Keller Graduate School of Management", 840),
("Monroe College", 840),
("San Mateo County Community College District", 840),
("Los Rios Community College District", 840),
("DigiPen Institute of Technology", 840),
("University of Pittsburgh Medical Center", 840),
("Claremont Graduate University", 840),
("University of Texas Rio Grande Valley", 840),
("College of Mount Saint Vincent", 840),
("University of Arkansas System eVersity", 840),
("ECPI University", 840),
("University of Mary Washington", 840),
("Baldwin Wallace University", 840),
("California State University Channel Islands", 840),
("Brandman University", 840),
("United States Coast Guard Academy", 840),
("Athens State University", 840),
("The Scripps Research Institute", 840),
("Eastern Florida State College", 840),
("Western New England University", 840),
("King University", 840),
("Georgia Gwinnett College", 840),
("Trident University", 840),
("Alliant International University", 840),
("Mississippi Valley State University", 840),
("Roosevelt University", 840),
("ITT Technical Institute", 840),
("Illinois Eastern Community Colleges", 840),
("Park University", 840),
("Icahn School of Medicine at Mount Sinai", 840),
("Utah Valley Uniersity", 840),
("Wisconsin Lutheran College", 840),
("Riverside Community College District", 840),
("Wake Forest Baptist Health", 840),
("University of Massachusetts Boston", 840),
("Florida Polytechnic University", 840),
("Wagner College", 840),
("Wilmington University", 840),
("International Technological University", 840),
("Young Harris College", 840),
("University of Findlay", 840),
("Philadelphia College of Osteopathic Medicine", 840),
("Yosemite Community College District", 840),
("Coastal Alabama Community College", 840),
("Purdue University Northwest", 840),
("Columbia Basin College", 840),
("Seattle Colleges", 840),
("Lipscomb University", 840),
("Tiffin University", 840),
("Troy University", 840),
("42 US", 840),
("California Baptist University", 840),
("Stevenson University", 840),
("Marine Biological Laboratory", 840),
("Maryville University", 840),
("The Art Institutes", 840),
("University of Mississippi Medical Center", 840),
("University of Central Oklahoma", 840),
("Hallmark University", 840),
("Keiser University", 840),
("St. Johns River State College", 840),
("Indian River State College", 840),
("Barnard College", 840),
("Thomas Edison State University", 840),
("California Southern University", 840),
("University of La Verne", 840),
("Washington &amp; Jefferson College", 840),
("University of the People", 840),
("Touro College", 840),
("New Jersey City University", 840),
("Lander University", 840),
("SUNY Maritime College", 840),
("Lesley University", 840),
("Laurus College", 840),
("National Park College", 840),
("Oklahoma Christian University", 840),
("San Diego Christian College", 840),
("SANS Technology Institute", 840),
("Pasco-Hernando State College", 840),
("New College of Florida", 840),
("Grand Canyon University", 840),
("Cold Spring Harbor Laboratory", 840),
("Albany State University", 840),
("Lasell College", 840),
("Contra Costa Community College District", 840),
("Mount St. Mary's University", 840),
("Robert Morris University Illinois", 840),
("Northwest Florida State College", 840),
("West Virginia Wesleyan College", 840),
("Utica College", 840),
("Career College of Northern Nevada", 840),
("University of North Georgia", 840),
("The Principia", 840),
("Lynn University", 840),
("Colorado Community College System", 840),
("Valencia College", 840),
("St. Petersburg College", 840),
("Globe University &amp; Minnesota School of Business", 840),
("Everest College", 840),
("Southwest Research Institute", 840),
("American Public University System", 840),
("Full Sail University", 840),
("YTI Career Institute", 840),
("Defense Language Institute Foreign Language Center", 840),
("Columbus State University", 840),
("Morehead State University", 840),
("Colorado State University - Global Campus", 840),
("North Dakota University System", 840),
("University of Houston-Downtown", 840),
("Stratford University", 840),
("California Polytechnic State University, Pomona", 840),
("Baker College", 840),
("The College of New Jersey", 840),
("Abilene Christian University", 840),
("Adelphi University", 840),
("Agnes Scott College", 840),
("Aiken Technical College", 840),
("Air Force Institute of Technology", 840),
("Alabama A&M University", 840),
("Alabama State University", 840),
("Alamo Colleges", 840),
("Albertson College of Idaho", 840),
("Albion College", 840),
("Alfred University", 840),
("Allegheny College", 840),
("Allentown College of Saint Francis de Sales", 840),
("Alma College", 840),
("Alverno College", 840),
("Ambassador University", 840),
("American Coastline University", 840),
("American International College", 840),
("American University", 840),
("Amherst College", 840),
("Andrews University", 840),
("Angelo State University", 840),
("Anne Arundel Community College", 840),
("Antioch New England", 840),
("Antioch University", 840),
("Antioch University - Los Angeles", 840),
("Antioch University - Seattle", 840),
("Appalachian State University", 840),
("Aquinas College", 840),
("Arcadia College", 840),
("Arizona State University", 840),
("Arizona Western College", 840),
("Arkansas State University", 840),
("Arkansas Tech University", 840),
("Armstrong State College", 840),
("Ashland University", 840),
("Assumption College", 840),
("Auburn University", 840),
("Auburn University at Montgomery", 840),
("Augsburg College", 840),
("Augustana College (IL)", 840),
("Augustana College (SD)", 840),
("Augusta University", 840),
("Aurora University", 840),
("Austin College", 840),
("Austin Community College", 840),
("Austin Peay State University", 840),
("Averett College", 840),
("Avila College", 840),
("Azusa Pacific University", 840),
("Babson College", 840),
("Baker University", 840),
("Ball State University", 840),
("Baptist Bible College", 840),
("Bard College", 840),
("Barry University", 840),
("Bastyr University", 840),
("Bates College", 840),
("Baylor College of Medicine", 840),
("Baylor University", 840),
("Bellevue University", 840),
("Belmont University", 840),
("Beloit College", 840),
("Bemidji State University", 840),
("Benedictine College", 840),
("Bennington College", 840),
("Bentley College", 840),
("Berea College", 840),
("Berklee College of Music", 840),
("Bethany College", 840),
("Bethel College (KS)", 840),
("Bethel University", 840),
("Biola University", 840),
("Birmingham-Southern College", 840),
("Black Hills State University", 840),
("Bloomsburg University of Pennsylvania", 840),
("Bluffton College", 840),
("Bob Jones University", 840),
("Boise State University", 840),
("Boston College", 840),
("Boston Graduate School of Psychoanalysis", 840),
("Boston University", 840),
("Bowdoin College", 840),
("Bowie State University", 840),
("Bowling Green State University", 840),
("Bradley University", 840),
("Brandeis University", 840),
("Brenau University", 840),
("Briar Cliff College", 840),
("Bridgewater College", 840),
("Brigham Young University", 840),
("Brigham Young University - Idaho", 840),
("Brigham Young University Hawaii", 840),
("Broward College", 840),
("Brown University", 840),
("Bryant College", 840),
("Bryn Mawr College", 840),
("Bucknell University", 840),
("Buena Vista University", 840),
("Butler University", 840),
("California Coast University", 840),
("California Institute of Technology", 840),
("California Lutheran University", 840),
("California Maritime Academy", 840),
("California National University", 840),
("California Polytechnic State University, San Luis Obispo", 840),
("California State University, Bakersfield", 840),
("California State University, Chico", 840),
("California State University, Dominguez Hills", 840),
("California State University, Fresno", 840),
("California State University, Fullerton", 840),
("California State University, Hayward", 840),
("California State University, Long Beach", 840),
("California State University, Los Angeles", 840),
("California State University, Monterey Bay", 840),
("California State University, Northridge", 840),
("California State University, Sacramento", 840),
("California State University, San Bernardino", 840),
("California State University, San Marcos", 840),
("California State University, Stanislaus", 840),
("California State University System", 840),
("California University of Pennsylvania", 840),
("Calvin College", 840),
("Cameron University", 840),
("Campbellsville College", 840),
("Campbell University", 840),
("Canisius College", 840),
("Capella University", 840),
("Capitol Technology University", 840),
("Carleton College", 840),
("Carlow College", 840),
("Carnegie Mellon University", 840),
("Carroll College", 840),
("Carroll University", 840),
("Carson-Newman College", 840),
("Carthage College", 840),
("Case Western Reserve University", 840),
("Castleton State University", 840),
("Catholic University of America", 840),
("Cedarville College", 840),
("Centenary College of Louisiana", 840),
("Central College", 840),
("Central Connecticut State University", 840),
("Central Methodist College", 840),
("Central Michigan University", 840),
("Central Washington University", 840),
("Centre College", 840),
("Chadron State College", 840),
("Champlain College", 840),
("Chapman University", 840),
("Chatham College", 840),
("Chesapeake College", 840),
("Cheyney University", 840),
("Chicago School of Professional Psychology", 840),
("Christian Brothers University", 840),
("Christian Theological Seminary", 840),
("Christopher Newport University", 840),
("City University", 840),
("City University of New York", 840),
("Claremont Graduate School", 840),
("Claremont McKenna College", 840),
("Clarion University of Pennsylvania", 840),
("Clarke College", 840),
("Clarkson University", 840),
("Clark University", 840),
("Clayton State College", 840),
("Clemson University", 840),
("Cleveland State University", 840),
("Clinch Valley College", 840),
("Coastal Carolina University", 840),
("Coast Colleges", 840),
("Coe College", 840),
("Coker College", 840),
("Colby College", 840),
("Colgate University", 840),
("College of Charleston", 840),
("College of Eastern Utah", 840),
("College of New Rochelle", 840),
("College of Saint Benedict", 840),
("College of Saint Catherine", 840),
("College of Saint Rose", 840),
("College of St. Francis", 840),
("College of St. Scholastica", 840),
("College of the Atlantic", 840),
("College of the Holy Cross", 840),
("College of William and Mary", 840),
("College of Wooster", 840),
("Colorado Christian University", 840),
("Colorado College", 840),
("Colorado Mesa University", 840),
("Colorado School of Mines", 840),
("Colorado State University", 840),
("Colorado Technical University", 840),
("Columbia College Chicago", 840),
("Columbia Southern University", 840),
("Columbia Union College", 840),
("Columbia University", 840),
("Community College of Baltimore County", 840),
("Concordia College - Ann Arbor", 840),
("Concordia College - Moorhead", 840),
("Concordia College - Seward", 840),
("Concordia College - St. Paul", 840),
("Connecticut College", 840),
("Connecticut State University System", 840),
("Cooper Union for the Advancement of Science and Art", 840),
("Coppin State University", 840),
("Cornell College", 840),
("Cornell University", 840),
("Corning Community College", 840),
("Creighton University", 840),
("Curry College", 840),
("Daemen College", 840),
("Dakota State University", 840),
("Dakota Wesleyan University", 840),
("Dallas Baptist University", 840),
("Dallas County Community College", 840),
("Dana College", 840),
("Daniel Webster College", 840),
("Dartmouth College", 840),
("Davenport University", 840),
("Davidson College", 840),
("Davis & Elkins College", 840),
("Daytona State College", 840),
("Delaware State University", 840),
("Delta State University", 840),
("Denison University", 840),
("DePaul University", 840),
("DePauw University", 840),
("DeVry Institute of Technology", 840),
("Dickinson College", 840),
("Dickinson State University", 840),
("Dillard University", 840),
("Dominican College", 840),
("Dordt College", 840),
("Dowling College", 840),
("Drake University", 840),
("Drew University", 840),
("Drexel University", 840),
("Drury College", 840),
("Duke University", 840),
("Duquesne University", 840),
("Earlham College", 840),
("East Carolina University", 840),
("East Central University", 840),
("Eastern Connecticut State University", 840),
("Eastern Illinois University", 840),
("Eastern Kentucky University", 840),
("Eastern Mennonite University", 840),
("Eastern Michigan University", 840),
("Eastern New Mexico University", 840),
("Eastern Oregon State College", 840),
("Eastern Washington University", 840),
("East Stroudsburg State University of Pennsylvania", 840),
("East Tennessee State University", 840),
("Edgewood College", 840),
("Edinboro University of Pennsylvania", 840),
("Elizabeth City State University", 840),
("Elizabethtown College", 840),
("Elmhurst College", 840),
("Elon College", 840),
("Embry-Riddle Aeronautical University", 840),
("Emerson College", 840),
("Emmanuel College", 840),
("Emory University", 840),
("Emporia State University", 840),
("Erie Community College", 840),
("Evergreen State College", 840),
("Fairleigh Dickinson University", 840),
("Fairmont State College", 840),
("Fayetteville State University", 840),
("Ferris State University", 840),
("Fielding Institute", 840),
("Fisk University", 840),
("Fitchburg State College", 840),
("Florida Agricultural and Mechanical University", 840),
("Florida Atlantic University", 840),
("Florida Gulf Coast University", 840),
("Florida Institute of Technology", 840),
("Florida International University", 840),
("Florida State University", 840),
("Fontbonne College", 840),
("Fordham University", 840),
("Fort Hays State University", 840),
("Fort Lewis College", 840),
("Fountainhead College of Technology", 840),
("Franklin and Marshall College", 840),
("Franklin Pierce Law Center", 840),
("Franklin University", 840),
("Frederick Community College", 840),
("Fresno Pacific University", 840),
("Friends University", 840),
("Frostburg State University", 840),
("Fuller Theological Seminary", 840),
("Furman University", 840),
("Gallaudet University", 840),
("Gannon University", 840),
("Geneva College", 840),
("George Fox College", 840),
("George Mason University", 840),
("Georgetown University", 840),
("George Washington University", 840),
("Georgia College", 840),
("Georgia Institute of Technology", 840),
("Georgian Court College", 840),
("Georgia Southern University", 840),
("Georgia Southwestern State University", 840),
("Georgia State University", 840),
("Gettysburg College", 840),
("GMI Engineering and Management Institute", 840),
("Golden Gate University", 840),
("Goldey-Beacom College", 840),
("Gonzaga University", 840),
("Goshen College", 840),
("Goucher College", 840),
("Governors State University", 840),
("Grace College", 840),
("Graceland College", 840),
("Grand Valley State University", 840),
("Greenleaf University", 840),
("Grinnell College", 840),
("Guilford College", 840),
("Gustavus Adolphus College", 840),
("Hagerstown Community College", 840),
("Hamilton College", 840),
("Hamline University", 840),
("Hampden-Sydney College", 840),
("Hampshire College", 840),
("Hampton University", 840),
("Hanover College", 840),
("Harding University", 840),
("Harford Community College", 840),
("Hartwick College", 840),
("Harvard University", 840),
("Harvey Mudd College", 840),
("Haskell Indian Nations University", 840),
("Hastings College", 840),
("Haverford College in Pennsylvania", 840),
("Hawaii Pacific University", 840),
("Heidelberg College", 840),
("Hendrix College", 840),
("Hesston College", 840),
("High Point University", 840),
("Hillsdale College", 840),
("Hiram College", 840),
("Hobart and William Smith Colleges", 840),
("Hofstra University", 840),
("Hollins College", 840),
("Hood College", 840),
("Hope College", 840),
("Howard Community College", 840),
("Howard University", 840),
("Humboldt State University", 840),
("Hunter College", 840),
("Huntingdon College", 840),
("Huntington University", 840),
("ICI University", 840),
("Idaho State University", 840),
("Illinois Benedictine College", 840),
("Illinois Institute of Technology", 840),
("Illinois State University", 840),
("Indiana Institute of Technology", 840),
("Indiana State University", 840),
("Indiana University", 840),
("Indiana University at Bloomington", 840),
("Indiana University at South Bend", 840),
("Indiana University of Pennsylvania", 840),
("Indiana University/Purdue University at Columbus", 840),
("Indiana University/Purdue University at Fort Wayne", 840),
("Indiana University/Purdue University at Indianapolis", 840),
("Indiana University Southeast", 840),
("Indiana Wesleyan University, Marion", 840),
("Institute for World Politics", 840),
("Iona College", 840),
("Iowa State University", 840),
("Irvine Valley College", 840),
("Ithaca College", 840),
("Jackson State University", 840),
("Jacksonville State University", 840),
("Jacksonville University", 840),
("James Madison University", 840),
("John Brown University", 840),
("John F. Kennedy University", 840),
("Johns Hopkins University", 840),
("Johns Hopkins University Applied Physics Laboratory", 840),
("Johnson & Wales University", 840),
("Johnson Bible College", 840),
("Johnson C. Smith University", 840),
("Jones College", 840),
("Judson College", 840),
("Juniata College", 840),
("Kalamazoo College", 840),
("Kansas State University", 840),
("Kansas Wesleyan University", 840),
("Kaplan University", 840),
("Kean College", 840),
("Keene State College", 840),
("Kennesaw State University", 840),
("Kent State University", 840),
("Kentucky Community & Technical College System", 840),
("Kenyon College", 840),
("Kettering University", 840),
("King's College", 840),
("Knox College", 840),
("Kutztown University of Pennsylvania", 840),
("Lafayette College", 840),
("LaGrange College", 840),
("Lake Forest College", 840),
("Lake Superior College", 840),
("Lake Superior State University", 840),
("Lamar University", 840),
("Langston University", 840),
("LaSalle University", 840),
("La Sierra University", 840),
("Lawrence Technological University", 840),
("Lawrence University", 840),
("Lebanon Valley College", 840),
("Lehigh University", 840),
("Le Moyne College", 840),
("Lenoir Community College", 840),
("Lenoir-Rhyne College", 840),
("LeTourneau University", 840),
("Lewis & Clark College", 840),
("Lewis-Clark State College", 840),
("Lewis University", 840),
("Liberty University", 840),
("Lincoln University", 840),
("Linfield College", 840),
("Lock Haven University", 840),
("Loma Linda University", 840),
("Long Island University", 840),
("Longwood University", 840),
("Loras College", 840),
("Los Angeles Community College District", 840),
("Louisiana College", 840),
("Louisiana State University", 840),
("Louisiana State University at Alexandria", 840),
("Louisiana Tech University", 840),
("Loyola College", 840),
("Loyola Marymount University", 840),
("Loyola University Chicago", 840),
("Luther College", 840),
("Luther Seminary", 840),
("Lycoming College", 840),
("Lynchburg College", 840),
("Lyndon State College", 840),
("Lyon College", 840),
("Macalester College", 840),
("Maharishi University of Management", 840),
("Malone College", 840),
("Manhattan College", 840),
("Mansfield University of Pennsylvania", 840),
("Maricopa County Community College District", 840),
("Marietta College", 840),
("Marist College", 840),
("Marlboro College", 840),
("Marquette University", 840),
("Marshall University", 840),
("Mary Baldwin College", 840),
("Marymount Manhattan College", 840),
("Marymount University", 840),
("Mary Washington College", 840),
("Massachusetts Institute of Technology", 840),
("McDaniel College", 840),
("McMurry University", 840),
("McNeese State University", 840),
("Medical College of Georgia", 840),
("Medical College of Wisconsin", 840),
("Mercer County Community College", 840),
("Mercer University", 840),
("Mercy College", 840),
("Mercyhurst College", 840),
("Meredith College", 840),
("Messiah College", 840),
("Metropolitan Community College (MO)", 840),
("Metropolitan Community College (NE)", 840),
("Metropolitan State College of Denver", 840),
("Metropolitan State University", 840),
("Miami University of Ohio", 840),
("Michigan State University", 840),
("Michigan Technological University", 840),
("Mid-America Nazarene College", 840),
("Middlebury College", 840),
("Middle Georgia State College", 840),
("Middle Tennessee State University", 840),
("Midwestern State University", 840),
("Millersville University of Pennsylvania", 840),
("Milligan College", 840),
("Millikin University", 840),
("Millsaps College", 840),
("Milwaukee School of Engineering", 840),
("Minneapolis College of Art and Design", 840),
("Minnesota State University, Mankato", 840),
("Minnesota State University Moorhead", 840),
("Minot State University", 840),
("Mississippi College", 840),
("Mississippi State University", 840),
("Mississippi University for Women", 840),
("Missouri Southern State College", 840),
("Missouri University of Science and Technology", 840),
("Missouri Western State College", 840),
("Molloy College", 840),
("Monmouth College", 840),
("Monmouth University", 840),
("Montana State University - Billings", 840),
("Montana State University - Bozeman", 840),
("Montana State University - Northern", 840),
("Montana Tech", 840),
("Montclair State University", 840),
("Montgomery College", 840),
("Montreat College", 840),
("Moravian College", 840),
("Morgan State University", 840),
("Mott Community College", 840),
("Mount Holyoke College", 840),
("Mount Saint Joseph College", 840),
("Mount Saint Mary College", 840),
("Mount Senario College", 840),
("Mount Union College", 840),
("Murray State University", 840),
("Muskingum College", 840),
("Nashville State Community College", 840),
("National Defense University", 840),
("National-Louis University", 840),
("National Radio Astronomy Observatory", 840),
("National Technological University", 840),
("National University", 840),
("Naval Postgraduate School", 840),
("Nazareth College", 840),
("Nevada System of Higher Education", 840),
("Newberry College", 840),
("New College of California", 840),
("New England Institute of Technology", 840),
("New Hampshire College", 840),
("New Jersey Institute of Technology", 840),
("New Mexico Highlands University", 840),
("New Mexico Institute of Mining & Technology", 840),
("New Mexico State University", 840),
("New York Institute of Technology", 840),
("New York University", 840),
("Niagara University", 840),
("Nicholls State University", 840),
("Norfolk State University", 840),
("North American University", 840),
("Northampton Community College", 840),
("North Carolina A&T State University", 840),
("North Carolina Central University", 840),
("North Carolina State University", 840),
("North Carolina Wesleyan College", 840),
("North Central Bible College", 840),
("North Dakota State University", 840),
("Northeastern Louisiana University", 840),
("Northeastern State University", 840),
("Northeastern University", 840),
("Northern Arizona University", 840),
("Northern Illinois University", 840),
("Northern Kentucky University", 840),
("Northern Michigan University", 840),
("Northern State University", 840),
("Northland College", 840),
("North Park College and Theological Seminary", 840),
("Northwestern College of Iowa", 840),
("Northwestern State University", 840),
("Northwestern University", 840),
("Northwest Missouri State University", 840),
("Northwest Nazarene College", 840),
("Norwich University", 840),
("Nova Southeastern University", 840),
("Oakland University", 840),
("Oakwood University", 840),
("Oberlin College", 840),
("Occidental College", 840),
("Ohio Dominican College", 840),
("Ohio Northern University", 840),
("Ohio State University, Columbus", 840),
("Ohio University", 840),
("Ohio Wesleyan University", 840),
("Oklahoma Baptist University", 840),
("Oklahoma City University", 840),
("Oklahoma State University", 840),
("Old Dominion University", 840),
("Olivet Nazarene University", 840),
("Oral Roberts University", 840),
("Oregon Graduate Institute of Science and Technology", 840),
("Oregon Health Sciences University", 840),
("Oregon Institute of Technology", 840),
("Oregon State University", 840),
("Otterbein College", 840),
("Our Lady of the Lake University", 840),
("Pace University", 840),
("Pacific Lutheran University", 840),
("Pacific Union College", 840),
("Pacific University", 840),
("Pacific Western University", 840),
("Palm Beach Atlantic College", 840),
("Palm Beach State College", 840),
("Peace College", 840),
("Pembroke State University", 840),
("Pennsylvania College of Technology", 840),
("Pennsylvania State University", 840),
("Pennsylvania State University - Schuylkill Campus", 840),
("Pensacola Christian College", 840),
("Pensacola State College", 840),
("Pepperdine University", 840),
("Peru State College", 840),
("Philadelphia University", 840),
("Phillips University", 840),
("Pittsburg State University", 840),
("Pitzer College", 840),
("Platt College", 840),
("Plymouth State College", 840),
("Polytechnic University of New York", 840),
("Polytechnic University of Puerto Rico", 840),
("Pomona College", 840),
("Portland Community College", 840),
("Portland State University", 840),
("Prairie View A&M University", 840),
("Pratt Institute", 840),
("Presbyterian College", 840),
("Prescott College", 840),
("Princeton University", 840),
("Providence College", 840),
("Purdue University", 840),
("Purdue University Calumet", 840),
("Purdue University North Central", 840),
("Quincy University", 840),
("Quinnipiac College", 840),
("Radford University", 840),
("Ramapo College", 840),
("Randolph-Macon College", 840),
("Randolph-Macon Woman's College", 840),
("Reed College", 840),
("Regent University", 840),
("Regis University", 840),
("Rensselaer Polytechnic Institute", 840),
("Rhode Island College", 840),
("Rhodes College", 840),
("Rice University", 840),
("Richard Stockton College of New Jersey", 840),
("Rider University", 840),
("Ripon College", 840),
("Rivier College", 840),
("Roanoke College", 840),
("Robert Morris University", 840),
("Rochester Institute of Technology", 840),
("Rockefeller University", 840),
("Rockford College", 840),
("Rockhurst College", 840),
("Rocky Mountain College", 840),
("Roger Williams University", 840),
("Rollins College", 840),
("Rosary College", 840),
("Rose-Hulman Institute of Technology", 840),
("Rowan College", 840),
("Rutgers University", 840),
("Rutgers University, Camden", 840),
("Rutgers University, Newark", 840),
("Sacred Heart University", 840),
("Sage Colleges", 840),
("Saginaw Valley State University", 840),
("Saint Anselm College", 840),
("Saint Cloud State University", 840),
("Saint Edward's University", 840),
("Saint Francis College", 840),
("Saint John's University (MN)", 840),
("Saint John's University (NY)", 840),
("Saint Joseph's College (IN)", 840),
("Saint Joseph's University", 840),
("Saint Leo University", 840),
("Saint Louis University", 840),
("Saint Mary College", 840),
("Saint Mary's College (IN)", 840),
("Saint Mary's College of California", 840),
("Saint Mary's University of Minnesota", 840),
("Saint Michael's College", 840),
("Saint Olaf College", 840),
("Saint Vincent College", 840),
("Saint Xavier University", 840),
("Salisbury University", 840),
("Salish Kootenai College", 840),
("Samford University", 840),
("Sam Houston State University", 840),
("San Diego State University", 840),
("San Francisco State University", 840),
("San Jose State University", 840),
("Santa Clara University", 840),
("Sarah Lawrence College", 840),
("School of the Art Institute of Chicago", 840),
("Seattle Central College", 840),
("Seattle Pacific University", 840),
("Seattle University", 840),
("Seton Hall University", 840),
("Sewanee, University of the South", 840),
("Shawnee State University", 840),
("Shenandoah University", 840),
("Shippensburg University of Pennsylvania", 840),
("Shorter College", 840),
("Simmons College", 840),
("Simon's Rock College", 840),
("Simpson College", 840),
("Sinclair Community College", 840),
("Skidmore College", 840),
("Slippery Rock University of Pennsylvania", 840),
("Smith College", 840),
("Sonoma State University", 840),
("South Dakota School of Mines and Technology", 840),
("South Dakota State University", 840),
("Southeastern Louisiana University", 840),
("Southeast Missouri State University", 840),
("Southern College", 840),
("Southern College of Technology", 840),
("Southern Connecticut State University", 840),
("Southern Illinois University-Carbondale", 840),
("Southern Illinois University-Edwardsville", 840),
("Southern Methodist University", 840),
("Southern Nazarene University", 840),
("Southern New Hampshire University", 840),
("Southern Oregon State College", 840),
("Southern University and A&M College", 840),
("Southern Utah University", 840),
("South Texas College of Law", 840),
("Southwest Baptist University", 840),
("Southwestern Adventist College", 840),
("Southwestern Assemblies of God University", 840),
("Southwestern College (KS)", 840),
("Southwestern University", 840),
("Southwest Missouri State University", 840),
("Southwest Texas State University", 840),
("Spelman College", 840),
("Spring Arbor College", 840),
("Spring Hill College", 840),
("St. Ambrose University", 840),
("St. Andrews Presbyterian College", 840),
("Stanford University", 840),
("State University of New York at Albany", 840),
("State University of New York at Binghamton", 840),
("State University of New York at Buffalo", 840),
("State University of New York at Farmingdale", 840),
("State University of New York at Fredonia", 840),
("State University of New York at Oswego", 840),
("State University of New York at Plattsburgh", 840),
("State University of New York at Stony Brook", 840),
("Academic medical center at State University of New York at Stony Brook", 840),
("State University of New York College at Brockport", 840),
("State University of New York College at Buffalo", 840),
("State University of New York College at Cortland", 840),
("State University of New York College at Geneseo", 840),
("State University of New York College at New Paltz", 840),
("State University of New York College at Potsdam", 840),
("State University of New York College of Agriculture and Technology at Cobleskill", 840),
("State University of New York College of Environmental Science and Forestry", 840),
("State University of New York College of Technology at Alfred", 840),
("State University of New York Polytechnic Institute", 840),
("State University of New York System", 840),
("St. Bonaventure University", 840),
("Stephen F. Austin State University", 840),
("Stephens College", 840),
("Stetson University", 840),
("Stevens Institute of Technology", 840),
("St. John's College - Annapolis", 840),
("St. John's College - Santa Fe", 840),
("St. Joseph College (CT)", 840),
("St. Joseph's College (ME)", 840),
("St. Lawrence University", 840),
("St. Louis College of Pharmacy", 840),
("St. Martin's College", 840),
("St. Mary's College of Maryland", 840),
("Strayer College", 840),
("St. Thomas University (FL)", 840),
("Suffolk University", 840),
("Sul Ross State University", 840),
("Summit University of Louisiana", 840),
("Susquehanna University", 840),
("Swarthmore College", 840),
("Sweet Briar College", 840),
("Syracuse University", 840),
("Tabor College", 840),
("Tarleton State University", 840),
("Taylor University", 840),
("Temple University", 840),
("Tennessee State University", 840),
("Tennessee Technological University", 840),
("Terrant County College", 840),
("Texas A&M International University", 840),
("Texas A&M University - College Station", 840),
("Texas A&M University - Commerce", 840),
("Texas A&M University - Corpus Christi", 840),
("Texas A&M University - Kingsville", 840),
("Texas Christian University", 840),
("Texas Southern University", 840),
("Texas State University", 840),
("Texas Tech University", 840),
("Texas Tech University-Health Sciences Center", 840),
("Texas Woman's University", 840),
("The Citadel", 840),
("The Jewish Theological Seminary", 840),
("Thomas College", 840),
("Thomas Jefferson University", 840),
("Thomas More College", 840),
("Thunderbird School of Global Management", 840),
("Towson University", 840),
("Transylvania University", 840),
("Trenton State College", 840),
("Trine University", 840),
("Trinity College (CT)", 840),
("Trinity College (DC)", 840),
("Trinity University", 840),
("Troy State University", 840),
("Truman State University", 840),
("Tucson University", 840),
("Tufts University", 840),
("Tulane University", 840),
("Tuskegee University", 840),
("Uniformed Services University of the Health Sciences", 840),
("Union College", 840),
("Union Institute", 840),
("Union University", 840),
("United States Air Force Academy", 840),
("United States International University", 840),
("United States Merchant Marine Academy", 840),
("United States Military Academy", 840),
("United States Naval Academy", 840),
("University of Advancing Technology", 840),
("University of Akron", 840),
("University of Alabama at Birmingham", 840),
("University of Alabama at Huntsville", 840),
("University of Alabama at Tuscaloosa", 840),
("University of Alaska", 840),
("University of Alaska - Anchorage", 840),
("University of Alaska - Fairbanks", 840),
("University of Alaska - Southeast", 840),
("University of Arizona", 840),
("University of Arkansas - Fayetteville", 840),
("University of Arkansas - Fort Smith", 840),
("University of Arkansas for Medical Sciences", 840),
("University of Arkansas - Little Rock", 840),
("University of Arkansas - Monticello", 840),
("University of Baltimore", 840),
("University of Bridgeport", 840),
("University of California, Berkeley", 840),
("University of California, Davis", 840),
("University of California, Irvine", 840),
("University of California, Los Angeles", 840),
("University of California, Merced", 840),
("University of California, Riverside", 840),
("University of California, San Diego", 840),
("University of California, San Francisco", 840),
("University of California, Santa Barbara", 840),
("University of California, Santa Cruz", 840),
("University of Central Arkansas", 840),
("University of Central Florida", 840),
("University of Central Missouri", 840),
("University of Charleston", 840),
("University of Chicago", 840),
("University of Cincinnati", 840),
("University of Colorado at Boulder", 840),
("University of Colorado at Colorado Springs", 840),
("University of Colorado at Denver", 840),
("University of Colorado Health Sciences Center", 840),
("University of Connecticut", 840),
("University of Dallas", 840),
("University of Dayton", 840),
("University of Delaware", 840),
("University of Denver", 840),
("University of Detroit Mercy", 840),
("University of Dubuque", 840),
("University of Evansville", 840),
("University of Florida", 840),
("University of Georgia", 840),
("University of Great Falls", 840),
("University of Guam", 840),
("University of Hartford", 840),
("University of Hawaii at Hilo", 840),
("University of Hawaii at Manoa", 840),
("University of Hawaii System", 840),
("University of Houston", 840),
("University of Idaho", 840),
("University of Illinois at Chicago", 840),
("University of Illinois at Springfield", 840),
("University of Illinois at Urbana-Champaign", 840),
("University of Indianapolis", 840),
("University of Iowa", 840),
("University of Jamestown", 840),
("University of Kansas", 840),
("University of Kansas School of Medicine", 840),
("University of Kentucky", 840),
("University of Louisiana at Lafeyette", 840),
("University of Louisiana at Monroe", 840),
("University of Louisville", 840),
("University of Maine", 840),
("University of Maine at Farmington", 840),
("University of Maine at Fort Kent", 840),
("University of Maine at Machias", 840),
("University of Maine at Presque Island", 840),
("University of Maine System", 840),
("University of Maryland, Baltimore", 840),
("University of Maryland, Baltimore County", 840),
("University of Maryland, College Park", 840),
("University of Maryland Eastern Shore", 840),
("University of Maryland - University College", 840),
("University of Massachusetts at Amherst", 840),
("University of Massachusetts at Dartmouth", 840),
("University of Massachusetts at Lowell", 840),
("University of Memphis", 840),
("University of Miami", 840),
("University of Michigan - Ann Arbor", 840),
("University of Michigan - Dearborn", 840),
("University of Minnesota", 840),
("University of Minnesota - Crookston", 840),
("University of Minnesota - Duluth", 840),
("University of Minnesota - Morris", 840),
("University of Minnesota - Twin Cities", 840),
("University of Mississippi", 840),
("University of Missouri - Columbia", 840),
("University of Missouri - Kansas City", 840),
("University of Missouri - Rolla", 840),
("University of Missouri - Saint Louis", 840),
("University of Montana", 840),
("University of Nebraska, Kearney", 840),
("University of Nebraska, Lincoln", 840),
("University of Nebraska, Omaha", 840),
("University of Nevada, Las Vegas", 840),
("University of Nevada, Reno", 840),
("University of New England", 840),
("University of New Hampshire, Durham", 840),
("University of New Haven", 840),
("University of New Mexico", 840),
("University of New Orleans", 840),
("University of North Carolina at Asheville", 840),
("University of North Carolina at Chapel Hill", 840),
("University of North Carolina at Charlotte", 840),
("University of North Carolina at Greensboro", 840),
("University of North Carolina at Wilmington", 840),
("University of North Dakota", 840),
("University of Northern Colorado", 840),
("University of Northern Iowa", 840),
("University of North Florida", 840),
("University of North Texas", 840),
("University of North Texas Health Science Center", 840),
("University of Notre Dame", 840),
("University of Oklahoma", 840),
("University of Oregon", 840),
("University of Pennsylvania", 840),
("University of Phoenix", 840),
("University of Pittsburgh", 840),
("University of Pittsburgh at Johnstown", 840),
("University of Portland", 840),
("University of Puerto Rico", 840),
("University of Puget Sound", 840),
("University of Redlands", 840),
("University of Rhode Island", 840),
("University of Richmond", 840),
("University of Rochester", 840),
("University of Saint Thomas (MN)", 840),
("University of Saint Thomas (TX)", 840),
("University of San Diego", 840),
("University of San Francisco", 840),
("University of Science & Arts of Oklahoma", 840),
("University of Scranton", 840),
("University of Sioux Falls", 840),
("University of South Alabama", 840),
("University of South Carolina", 840),
("University of South Carolina - Aiken", 840),
("University of South Dakota", 840),
("University of Southern California", 840),
("University of Southern Indiana", 840),
("University of Southern Maine", 840),
("University of Southern Mississippi", 840),
("University of South Florida", 840),
("University of Southwestern Louisiana", 840),
("University of Tampa", 840),
("University of Tennessee at Chattanooga", 840),
("University of Tennessee, Knoxville", 840),
("University of Tennessee, Martin", 840),
("University of Texas at Arlington", 840),
("University of Texas at Austin", 840),
("University of Texas at Brownsville", 840),
("University of Texas at Dallas", 840),
("University of Texas at El Paso", 840),
("University of Texas at San Antonio", 840),
("University of Texas at Tyler", 840),
("University of Texas Medical Branch", 840),
("University of Texas - Pan American", 840),
("University of Texas Southwestern Medical Center", 840),
("University of the District of Columbia", 840),
("University of the Incarnate Word", 840),
("University of the Ozarks", 840),
("University of the Pacific", 840),
("University of the Virgin Islands", 840),
("University of Toledo", 840),
("University of Tulsa", 840),
("University of Utah", 840),
("University of Vermont", 840),
("University of Virginia, Charlottesville", 840),
("University of Washington", 840),
("University of West Alabama", 840),
("University of West Florida", 840),
("University of Wisconsin - Eau Claire", 840),
("University of Wisconsin - Green Bay", 840),
("University of Wisconsin - LaCrosse", 840),
("University of Wisconsin - Madison", 840),
("University of Wisconsin - Milwaukee", 840),
("University of Wisconsin - Oshkosh", 840),
("University of Wisconsin - Parkside", 840),
("University of Wisconsin - Platteville", 840),
("University of Wisconsin - River Falls", 840),
("University of Wisconsin - Stevens Point", 840),
("University of Wisconsin - Stout", 840),
("University of Wisconsin - Superior", 840),
("University of Wisconsin System", 840),
("University of Wisconsin - Whitewater", 840),
("University of Wyoming", 840),
("Upper Iowa University", 840),
("Ursinus College", 840),
("Utah State University", 840),
("Utah Valley State College", 840),
("Valdosta State University", 840),
("Valley City State University", 840),
("Valparaiso University", 840),
("Vance-Granville Community College", 840),
("Vanderbilt University", 840),
("Vassar College", 840),
("Vermont Technical College", 840),
("Villa Julie College", 840),
("Villanova University", 840),
("Virginia Commonwealth University", 840),
("Virginia Community College System", 840),
("Virginia Intermont College", 840),
("Virginia Military Institute", 840),
("Virginia Polytechnic Institute and State University", 840),
("Virginia State University", 840),
("Virginia Wesleyan College", 840),
("Wabash College", 840),
("Wake Forest University", 840),
("Walden University", 840),
("Walla Walla University", 840),
("Walsh College", 840),
("Warren Wilson College", 840),
("Wartburg College", 840),
("Washburn University", 840),
("Washington & Lee University", 840),
("Washington Bible College/Capital Bible Seminary", 840),
("Washington College", 840),
("Washington State University", 840),
("Washington State University at Tri-Cities", 840),
("Washington State University at Vancouver", 840),
("Washington University, Saint Louis", 840),
("Waubonsee Community College", 840),
("Waynesburg College", 840),
("Wayne State University", 840),
("Weber State University", 840),
("Webster University", 840),
("Wellesley College", 840),
("Wells College", 840),
("Wentworth Institute of Technology", 840),
("Wesleyan University", 840),
("Wesley College", 840),
("West Chester University of Pennsylvania", 840),
("West Coast University", 840),
("Western Carolina University", 840),
("Western Connecticut State University", 840),
("Western Governors University", 840),
("Western Illinois University", 840),
("Western Kentucky University", 840),
("Western Michigan University", 840),
("Western Montana College", 840),
("Western New England College", 840),
("Western New Mexico University", 840),
("Western State Colorado University", 840),
("Western Washington University", 840),
("Westfield State College", 840),
("West Georgia College", 840),
("West Liberty State College", 840),
("Westminster College", 840),
("Westminster College of Salt Lake City", 840),
("Westminster Theological Seminary", 840),
("Westmont College", 840),
("West Texas A&M University", 840),
("West Virginia University", 840),
("West Virginia University at Parkersburg", 840),
("Wheaton College", 840),
("Wheaton College, Norton MA", 840),
("Wheeling Jesuit College", 840),
("Whitman College", 840),
("Whittier College", 840),
("Whitworth College", 840),
("Wichita State University", 840),
("Widener University", 840),
("Wilberforce University", 840),
("Wilkes University", 840),
("Willamette University", 840),
("William Howard Taft University", 840),
("William Jewell College", 840),
("William Mitchell College of Law", 840),
("William Paterson University", 840),
("William Penn College", 840),
("Williams College", 840),
("William Woods University", 840),
("Wilmington College", 840),
("Winona State University", 840),
("Winthrop University", 840),
("Wittenberg University", 840),
("Wofford College", 840),
("Woodbury University", 840),
("Worcester Polytechnic Institute", 840),
("Wright State University", 840),
("Xavier University of Louisiana", 840),
("Yale University", 840),
("Yeshiva University", 840),
("York College of Pennsylvania", 840),
("Youngstown State University", 840),
("Alabama Southern Community College", 840),
("Bevill State Community College", 840),
("Bishop State Community College", 840),
("Central Alabama Community College", 840),
("Chattahoochee Valley Community College", 840),
("Enterprise State Community College", 840),
("Gadsden State Community College", 840),
("George C Wallace State Community College-Dothan", 840),
("George C Wallace State Community College-Hanceville", 840),
("George C Wallace State Community College-Selma", 840),
("H Councill Trenholm State Technical College", 840),
("James H Faulkner State Community College", 840),
("Jefferson Davis Community College", 840),
("Jefferson State Community College", 840),
("J F Drake State Community and Technical College", 840),
("Calhoun Community College", 840),
("Lurleen B Wallace Community College", 840),
("Marion Military Institute", 840),
("Northeast Alabama Community College", 840),
("Northwest-Shoals Community College", 840),
("Shelton State Community College", 840),
("Snead State Community College", 840),
("Southern Union State Community College", 840),
("Ilisagvik College", 840),
("Prince William Sound College", 840),
("Central Arizona College", 840),
("Chandler-Gilbert Community College", 840),
("Cochise College", 840),
("Coconino Community College", 840),
("Eastern Arizona College", 840),
("Estrella Mountain Community College", 840),
("GateWay Community College", 840),
("Glendale Community College", 840),
("Mesa Community College", 840),
("Mohave Community College", 840),
("Northland Pioneer College", 840),
("Paradise Valley Community College", 840),
("Phoenix College", 840),
("Pima Community College", 840),
("Rio Salado College", 840),
("Scottsdale Community College", 840),
("South Mountain Community College", 840),
("Tohono O'Odham Community College", 840),
("Yavapai College", 840),
("Arkansas Northeastern College", 840),
("Arkansas State University-Beebe", 840),
("Arkansas State University-Mountain Home", 840),
("Arkansas State University-Newport", 840),
("Black River Technical College", 840),
("College of the Ouachitas", 840),
("Cossatot Community College of the University of Arkansas", 840),
("East Arkansas Community College", 840),
("Mid-South Community College", 840),
("National Park Community College", 840),
("North Arkansas College", 840),
("NorthWest Arkansas Community College", 840),
("Ozarka College", 840),
("Phillips Community College of the University of Arkansas", 840),
("Pulaski Technical College", 840),
("Rich Mountain Community College", 840),
("South Arkansas Community College", 840),
("Southeast Arkansas College", 840),
("Southern Arkansas University Tech", 840),
("University of Arkansas Community College-Batesville", 840),
("University of Arkansas Community College-Hope", 840),
("University of Arkansas Community College-Morrilton", 840),
("Allan Hancock College", 840),
("American River College", 840),
("Antelope Valley College", 840),
("Bakersfield College", 840),
("Barstow Community College", 840),
("Berkeley City College", 840),
("Butte College", 840),
("Cabrillo College", 840),
("Canada College", 840),
("Carrington College California-Sacramento", 840),
("Cerritos College", 840),
("Cerro Coso Community College", 840),
("Chabot College", 840),
("Chaffey College", 840),
("Citrus College", 840),
("City College of San Francisco", 840),
("Coastline Community College", 840),
("College of Alameda", 840),
("College of Marin", 840),
("College of San Mateo", 840),
("College of the Canyons", 840),
("College of the Desert", 840),
("College of the Redwoods", 840),
("College of the Sequoias", 840),
("College of the Siskiyous", 840),
("Columbia College (MO)", 840),
("Columbia College (CA)", 840),
("Contra Costa College", 840),
("Copper Mountain Community College", 840),
("Cosumnes River College", 840),
("Crafton Hills College", 840),
("Cuesta College", 840),
("Cuyamaca College", 840),
("Cypress College", 840),
("De Anza College", 840),
("Diablo Valley College", 840),
("East Los Angeles College", 840),
("El Camino College-Compton Center", 840),
("El Camino Community College District", 840),
("Evergreen Valley College", 840),
("Feather River Community College District", 840),
("Folsom Lake College", 840),
("Foothill College", 840),
("Fresno City College", 840),
("Fullerton College", 840),
("Gavilan College", 840),
("Golden West College", 840),
("Grossmont College", 840),
("Hartnell College", 840),
("Imperial Valley College", 840),
("Lake Tahoe Community College", 840),
("Laney College", 840),
("Las Positas College", 840),
("Lassen Community College", 840),
("Long Beach City College", 840),
("Los Angeles City College", 840),
("Los Angeles County College of Nursing and Allied Health", 840),
("Los Angeles Harbor College", 840),
("Los Angeles Mission College", 840),
("Los Angeles Pierce College", 840),
("Los Angeles Southwest College", 840),
("Los Angeles Trade Technical College", 840),
("Los Angeles Valley College", 840),
("Los Medanos College", 840),
("Mendocino College", 840),
("Merced College", 840),
("Merritt College", 840),
("MiraCosta College", 840),
("Mission College", 840),
("Modesto Junior College", 840),
("Monterey Peninsula College", 840),
("Moorpark College", 840),
("Moreno Valley College", 840),
("MTI College", 840),
("Mt. San Antonio College", 840),
("Mt. San Jacinto Community College District", 840),
("Napa Valley College", 840),
("Norco College", 840),
("Ohlone College", 840),
("Orange Coast College", 840),
("Oxnard College", 840),
("Palomar College", 840),
("Palo Verde College", 840),
("Pasadena City College", 840),
("Porterville College", 840),
("Reedley College", 840),
("Rio Hondo College", 840),
("Riverside City College", 840),
("Sacramento City College", 840),
("Saddleback College", 840),
("San Bernardino Valley College", 840),
("San Diego City College", 840),
("San Diego Mesa College", 840),
("San Diego Miramar College", 840),
("San Joaquin Delta College", 840),
("San Joaquin Valley College-Visalia", 840),
("San Jose City College", 840),
("Santa Ana College", 840),
("Santa Barbara City College", 840),
("Santa Monica College", 840),
("Santa Rosa Junior College", 840),
("Santiago Canyon College", 840),
("Shasta College", 840),
("Sierra College", 840),
("Skyline College", 840),
("Solano Community College", 840),
("Southwestern College (CA)", 840),
("Taft College", 840),
("Ventura College", 840),
("Victor Valley College", 840),
("West Hills College-Coalinga", 840),
("West Los Angeles College", 840),
("West Valley College", 840),
("Woodland Community College", 840),
("Yuba College", 840),
("Aims Community College", 840),
("Arapahoe Community College", 840),
("Colorado Northwestern Community College", 840),
("Community College of Aurora", 840),
("Community College of Denver", 840),
("Front Range Community College", 840),
("Lamar Community College", 840),
("Morgan Community College", 840),
("Northeastern Junior College", 840),
("Otero Junior College", 840),
("Pikes Peak Community College", 840),
("Pueblo Community College", 840),
("Red Rocks Community College", 840),
("Trinidad State Junior College", 840),
("Asnuntuck Community College", 840),
("Capital Community College", 840),
("Housatonic Community College", 840),
("Manchester Community College", 840),
("Middlesex Community College", 840),
("Naugatuck Valley Community College", 840),
("Northwestern Connecticut Community College", 840),
("Norwalk Community College", 840),
("Quinebaug Valley Community College", 840),
("Three Rivers Community College", 840),
("Tunxis Community College", 840),
("Delaware College of Art and Design", 840),
("Delaware Technical Community College-Owens", 840),
("Delaware Technical Community College-Stanton/Wilmington", 840),
("Delaware Technical Community College-Terry", 840),
("Florida Keys Community College", 840),
("Hillsborough Community College", 840),
("North Florida Community College", 840),
("Pasco-Hernando Community College", 840),
("Tallahassee Community College", 840),
("Albany Technical College", 840),
("Altamaha Technical College", 840),
("Andrew College", 840),
("Athens Technical College", 840),
("Atlanta Technical College", 840),
("Augusta Technical College", 840),
("Bainbridge State College", 840),
("Central Georgia Technical College", 840),
("Chattahoochee Technical College", 840),
("Columbus Technical College", 840),
("Darton State College", 840),
("Georgia Highlands College", 840),
("Georgia Military College", 840),
("Georgia Northwestern Technical College", 840),
("Georgia Perimeter College", 840),
("Georgia Piedmont Technical College", 840),
("Gwinnett Technical College", 840),
("Lanier Technical College", 840),
("Moultrie Technical College", 840),
("North Georgia Technical College", 840),
("Ogeechee Technical College", 840),
("Okefenokee Technical College", 840),
("Savannah Technical College", 840),
("Southeastern Technical College", 840),
("Southern Crescent Technical College", 840),
("South Georgia Technical College", 840),
("Southwest Georgia Technical College", 840),
("West Georgia Technical College", 840),
("Wiregrass Georgia Technical College", 840),
("Hawaii Community College", 840),
("Honolulu Community College", 840),
("Kapiolani Community College", 840),
("Kauai Community College", 840),
("Leeward Community College", 840),
("Windward Community College", 840),
("College of Southern Idaho", 840),
("College of Western Idaho", 840),
("Eastern Idaho Technical College", 840),
("North Idaho College", 840),
("Black Hawk College", 840),
("Carl Sandburg College", 840),
("City Colleges of Chicago-Harold Washington College", 840),
("City Colleges of Chicago-Harry S Truman College", 840),
("City Colleges of Chicago-Kennedy-King College", 840),
("City Colleges of Chicago-Malcolm X College", 840),
("City Colleges of Chicago-Olive-Harvey College", 840),
("City Colleges of Chicago-Richard J Daley College", 840),
("City Colleges of Chicago-Wilbur Wright College", 840),
("College of DuPage", 840),
("College of Lake County", 840),
("Danville Area Community College", 840),
("Elgin Community College", 840),
("Fox College", 840),
("Harper College", 840),
("Heartland Community College", 840),
("Highland Community College", 840),
("Illinois Central College", 840),
("Illinois Valley Community College", 840),
("John A Logan College", 840),
("John Wood Community College", 840),
("Joliet Junior College", 840),
("Kankakee Community College", 840),
("Kaskaskia College", 840),
("Kishwaukee College", 840),
("Lake Land College", 840),
("Le Cordon Bleu College of Culinary Arts-Chicago", 840),
("Lewis and Clark Community College", 840),
("Lincoln Land Community College", 840),
("MacCormac College", 840),
("McHenry County College", 840),
("Moraine Valley Community College", 840),
("Morton College", 840),
("Northwestern College-Chicago Campus", 840),
("Oakton Community College", 840),
("Parkland College", 840),
("Prairie State College", 840),
("Rend Lake College", 840),
("Richland Community College", 840),
("Rock Valley College", 840),
("Sauk Valley Community College", 840),
("Shawnee Community College", 840),
("Southeastern Illinois College", 840),
("South Suburban College", 840),
("Southwestern Illinois College", 840),
("Spoon River College", 840),
("Triton College", 840),
("Ancilla College", 840),
("Ivy Tech Community College", 840),
("Des Moines Area Community College", 840),
("Eastern Iowa Community College District", 840),
("Hawkeye Community College", 840),
("Indian Hills Community College", 840),
("Iowa Central Community College", 840),
("Iowa Lakes Community College", 840),
("Iowa Western Community College", 840),
("Kirkwood Community College", 840),
("Marshalltown Community College", 840),
("Northeast Iowa Community College", 840),
("North Iowa Area Community College", 840),
("Northwest Iowa Community College", 840),
("Southeastern Community College", 840),
("Southwestern Community College", 840),
("Western Iowa Tech Community College", 840),
("Allen County Community College", 840),
("Barton County Community College", 840),
("Butler Community College", 840),
("Cloud County Community College", 840),
("Coffeyville Community College", 840),
("Colby Community College", 840),
("Cowley County Community College", 840),
("Dodge City Community College", 840),
("Flint Hills Technical College", 840),
("Fort Scott Community College", 840),
("Garden City Community College", 840),
("Hutchinson Community College", 840),
("Independence Community College", 840),
("Johnson County Community College", 840),
("Kansas City Kansas Community College", 840),
("Labette Community College", 840),
("Manhattan Area Technical College", 840),
("Neosho County Community College", 840),
("North Central Kansas Technical College", 840),
("Northwest Kansas Technical College", 840),
("Pratt Community College", 840),
("Seward County Community College and Area Technical School", 840),
("Wichita Area Technical College", 840),
("Ashland Community and Technical College", 840),
("Big Sandy Community and Technical College", 840),
("Bluegrass Community and Technical College", 840),
("Elizabethtown Community and Technical College", 840),
("Galen College of Nursing-Louisville", 840),
("Gateway Community and Technical College", 840),
("Hazard Community and Technical College", 840),
("Henderson Community College", 840),
("Hopkinsville Community College", 840),
("Jefferson Community and Technical College", 840),
("Madisonville Community College", 840),
("Maysville Community and Technical College", 840),
("Owensboro Community and Technical College", 840),
("Somerset Community College", 840),
("Southcentral Kentucky Community and Technical College", 840),
("Southeast Kentucky Community and Technical College", 840),
("West Kentucky Community and Technical College", 840),
("Baton Rouge Community College", 840),
("Bossier Parish Community College", 840),
("Delgado Community College", 840),
("L E Fletcher Technical Community College", 840),
("Louisiana Delta Community College", 840),
("Louisiana State University-Eunice", 840),
("Nunez Community College", 840),
("River Parishes Community College", 840),
("Southern University at Shreveport", 840),
("South Louisiana Community College", 840),
("SOWELA Technical Community College", 840),
("Central Maine Community College", 840),
("Central Maine Medical Center College of Nursing and Health Professions", 840),
("Eastern Maine Community College", 840),
("Kennebec Valley Community College", 840),
("Northern Maine Community College", 840),
("Southern Maine Community College", 840),
("Washington County Community College", 840),
("York County Community College", 840),
("Allegany College of Maryland", 840),
("Baltimore City Community College", 840),
("Carroll Community College", 840),
("Cecil College", 840),
("College of Southern Maryland", 840),
("Garrett College", 840),
("Prince George's Community College", 840),
("Wor-Wic Community College", 840),
("Berkshire Community College", 840),
("Bristol Community College", 840),
("Bunker Hill Community College", 840),
("Cape Cod Community College", 840),
("Greenfield Community College", 840),
("Holyoke Community College", 840),
("Massachusetts Bay Community College", 840),
("Massasoit Community College", 840),
("Mount Wachusett Community College", 840),
("Northern Essex Community College", 840),
("North Shore Community College", 840),
("Quincy College", 840),
("Quinsigamond Community College", 840),
("Roxbury Community College", 840),
("Springfield Technical Community College", 840),
("Urban College of Boston", 840),
("Alpena Community College", 840),
("Bay de Noc Community College", 840),
("Bay Mills Community College", 840),
("Delta College", 840),
("Glen Oaks Community College", 840),
("Gogebic Community College", 840),
("Grand Rapids Community College", 840),
("Henry Ford College", 840),
("Jackson College", 840),
("Kalamazoo Valley Community College", 840),
("Kellogg Community College", 840),
("Keweenaw Bay Ojibwa Community College", 840),
("Kirtland Community College", 840),
("Lake Michigan College", 840),
("Lansing Community College", 840),
("Macomb Community College", 840),
("Mid Michigan Community College", 840),
("Monroe County Community College", 840),
("Montcalm Community College", 840),
("Muskegon Community College", 840),
("North Central Michigan College", 840),
("Oakland Community College", 840),
("Saginaw Chippewa Tribal College", 840),
("Schoolcraft College", 840),
("Southwestern Michigan College", 840),
("St. Clair County Community College", 840),
("Washtenaw Community College", 840),
("Wayne County Community College District", 840),
("West Shore Community College", 840),
("Alexandria Technical & Community College", 840),
("Anoka-Ramsey Community College", 840),
("Anoka Technical College", 840),
("Central Lakes College-Brainerd", 840),
("Century College", 840),
("Dakota County Technical College", 840),
("Fond du Lac Tribal and Community College", 840),
("Hennepin Technical College", 840),
("Hibbing Community College", 840),
("Inver Hills Community College", 840),
("Itasca Community College", 840),
("Leech Lake Tribal College", 840),
("Mesabi Range Community and Technical College", 840),
("Minneapolis Community and Technical College", 840),
("Minnesota State College-Southeast Technical", 840),
("Minnesota State Community and Technical College", 840),
("Minnesota West Community and Technical College", 840),
("Normandale Community College", 840),
("North Hennepin Community College", 840),
("Northland Community and Technical College", 840),
("Northwest Technical College", 840),
("Pine Technical College", 840),
("Rainy River Community College", 840),
("Ridgewater College", 840),
("Riverland Community College", 840),
("Rochester Community and Technical College", 840),
("Saint Paul College", 840),
("South Central College", 840),
("St Cloud Technical and Community College", 840),
("Vermilion Community College", 840),
("White Earth Tribal and Community College", 840),
("Coahoma Community College", 840),
("Copiah-Lincoln Community College", 840),
("East Central Community College", 840),
("East Mississippi Community College", 840),
("Hinds Community College", 840),
("Holmes Community College", 840),
("Itawamba Community College", 840),
("Jones County Junior College", 840),
("Meridian Community College", 840),
("Mississippi Delta Community College", 840),
("Mississippi Gulf Coast Community College", 840),
("Northeast Mississippi Community College", 840),
("Northwest Mississippi Community College", 840),
("Pearl River Community College", 840),
("Southwest Mississippi Community College", 840),
("Crowder College", 840),
("East Central College", 840),
("Jefferson College", 840),
("Linn State Technical College", 840),
("Mineral Area College", 840),
("Missouri State University", 840),
("Missouri State University-West Plains", 840),
("Moberly Area Community College", 840),
("North Central Missouri College", 840),
("Ozarks Technical Community College", 840),
("Southeast Missouri Hospital College of Nursing and Health Sciences", 840),
("State Fair Community College", 840),
("St Charles Community College", 840),
("Wentworth Military Academy & Junior College", 840),
("Aaniiih Nakoda College", 840),
("Blackfeet Community College", 840),
("Chief Dull Knife College", 840),
("Dawson Community College", 840),
("Flathead Valley Community College", 840),
("Fort Peck Community College", 840),
("Great Falls College Montana State University", 840),
("Helena College University of Montana", 840),
("Little Big Horn College", 840),
("Miles Community College", 840),
("Stone Child College", 840),
("Central Community College", 840),
("Little Priest Tribal College", 840),
("Mid-Plains Community College", 840),
("Nebraska College of Technical Agriculture", 840),
("Nebraska Indian Community College", 840),
("Northeast Community College", 840),
("Southeast Community College Area", 840),
("Western Nebraska Community College", 840),
("Truckee Meadows Community College", 840),
("Great Bay Community College", 840),
("Lakes Region Community College", 840),
("Nashua Community College", 840),
("NHTI-Concord's Community College", 840),
("River Valley Community College", 840),
("White Mountains Community College", 840),
("Assumption College for Sisters", 840),
("Atlantic Cape Community College", 840),
("Bergen Community College", 840),
("Brookdale Community College", 840),
("Burlington County College", 840),
("Camden County College", 840),
("County College of Morris", 840),
("Cumberland County College", 840),
("Essex County College", 840),
("Gloucester County College", 840),
("Hudson County Community College", 840),
("Middlesex County College", 840),
("Ocean County College", 840),
("Passaic County Community College", 840),
("Raritan Valley Community College", 840),
("Salem Community College", 840),
("Sussex County Community College", 840),
("Union County College", 840),
("Warren County Community College", 840),
("Central New Mexico Community College", 840),
("Clovis Community College", 840),
("Eastern New Mexico University-Roswell Campus", 840),
("Luna Community College", 840),
("Mesalands Community College", 840),
("New Mexico Junior College", 840),
("New Mexico Military Institute", 840),
("New Mexico State University-Alamogordo", 840),
("New Mexico State University-Carlsbad", 840),
("New Mexico State University-Dona Ana", 840),
("San Juan College", 840),
("Santa Fe Community College", 840),
("Southwestern Indian Polytechnic Institute", 840),
("Adirondack Community College", 840),
("American Academy of Dramatic Arts-New York", 840),
("ASA College", 840),
("Cayuga County Community College", 840),
("Clinton Community College", 840),
("Columbia-Greene Community College", 840),
("CUNY Borough of Manhattan Community College", 840),
("CUNY Bronx Community College", 840),
("CUNY Hostos Community College", 840),
("CUNY Kingsborough Community College", 840),
("CUNY LaGuardia Community College", 840),
("CUNY Queensborough Community College", 840),
("Dutchess Community College", 840),
("Finger Lakes Community College", 840),
("Fulton-Montgomery Community College", 840),
("Genesee Community College", 840),
("Herkimer County Community College", 840),
("Hudson Valley Community College", 840),
("Jamestown Community College", 840),
("Jefferson Community College", 840),
("Mohawk Valley Community College", 840),
("Monroe Community College", 840),
("Nassau Community College", 840),
("Niagara County Community College", 840),
("North Country Community College", 840),
("Onondaga Community College", 840),
("Orange County Community College", 840),
("Rockland Community College", 840),
("Saint Elizabeth College of Nursing", 840),
("Schenectady County Community College", 840),
("Suffolk County Community College", 840),
("Sullivan County Community College", 840),
("SUNY Broome Community College", 840),
("SUNY Westchester Community College", 840),
("Technical Career Institutes", 840),
("Tompkins Cortland Community College", 840),
("Ulster County Community College", 840),
("Alamance Community College", 840),
("Asheville-Buncombe Technical Community College", 840),
("Beaufort County Community College", 840),
("Bladen Community College", 840),
("Blue Ridge Community College", 840),
("Brunswick Community College", 840),
("Caldwell Community College and Technical Institute", 840),
("Cape Fear Community College", 840),
("Carolinas College of Health Sciences", 840),
("Carteret Community College", 840),
("Catawba Valley Community College", 840),
("Central Carolina Community College", 840),
("Central Piedmont Community College", 840),
("Cleveland Community College", 840),
("Coastal Carolina Community College", 840),
("College of the Albemarle", 840),
("Craven Community College", 840),
("Davidson County Community College", 840),
("Durham Technical Community College", 840),
("Edgecombe Community College", 840),
("Fayetteville Technical Community College", 840),
("Forsyth Technical Community College", 840),
("Gaston College", 840),
("Guilford Technical Community College", 840),
("Halifax Community College", 840),
("Haywood Community College", 840),
("Isothermal Community College", 840),
("James Sprunt Community College", 840),
("Johnston Community College", 840),
("Louisburg College", 840),
("Martin Community College", 840),
("Mayland Community College", 840),
("McDowell Technical Community College", 840),
("Mitchell Community College", 840),
("Montgomery Community College", 840),
("Nash Community College", 840),
("Pamlico Community College", 840),
("Piedmont Community College", 840),
("Pitt Community College", 840),
("Randolph Community College", 840),
("Richmond Community College", 840),
("Roanoke-Chowan Community College", 840),
("Robeson Community College", 840),
("Rockingham Community College", 840),
("Rowan-Cabarrus Community College", 840),
("Sampson Community College", 840),
("Sandhills Community College", 840),
("South Piedmont Community College", 840),
("Stanly Community College", 840),
("Surry Community College", 840),
("Tri-County Community College", 840),
("Wake Technical Community College", 840),
("Wayne Community College", 840),
("Western Piedmont Community College", 840),
("Wilkes Community College", 840),
("Wilson Community College", 840),
("Cankdeska Cikana Community College", 840),
("Dakota College at Bottineau", 840),
("Lake Region State College", 840),
("North Dakota State College of Science", 840),
("Williston State College", 840),
("Belmont College", 840),
("Central Ohio Technical College", 840),
("Chatfield College", 840),
("Cincinnati State Technical and Community College", 840),
("Clark State Community College", 840),
("Columbus State Community College", 840),
("Cuyahoga Community College District", 840),
("Davis College", 840),
("Eastern Gateway Community College", 840),
("Edison State Community College", 840),
("Hocking College", 840),
("James A Rhodes State College", 840),
("Lakeland Community College", 840),
("Lorain County Community College", 840),
("Marion Technical College", 840),
("North Central State College", 840),
("Northwest State Community College", 840),
("Ohio State University Agricultural Technical Institute", 840),
("Owens Community College", 840),
("Southern State Community College", 840),
("Stark State College", 840),
("Terra State Community College", 840),
("University of Akron Wayne College", 840),
("Washington State Community College", 840),
("Zane State College", 840),
("Carl Albert State College", 840),
("Connors State College", 840),
("Eastern Oklahoma State College", 840),
("Murray State College", 840),
("Northeastern Oklahoma A&M College", 840),
("Northern Oklahoma College", 840),
("Oklahoma City Community College", 840),
("Redlands Community College", 840),
("Rose State College", 840),
("Seminole State College", 840),
("Tulsa Community College", 840),
("Western Oklahoma State College", 840),
("Blue Mountain Community College", 840),
("Central Oregon Community College", 840),
("Chemeketa Community College", 840),
("Clackamas Community College", 840),
("Clatsop Community College", 840),
("Columbia Gorge Community College", 840),
("Klamath Community College", 840),
("Lane Community College", 840),
("Linn-Benton Community College", 840),
("Mt. Hood Community College", 840),
("Rogue Community College", 840),
("Southwestern Oregon Community College", 840),
("Tillamook Bay Community College", 840),
("Treasure Valley Community College", 840),
("Umpqua Community College", 840),
("Bucks County Community College", 840),
("Butler County Community College", 840),
("Community College of Allegheny County", 840),
("Community College of Beaver County", 840),
("Community College of Philadelphia", 840),
("Delaware County Community College", 840),
("Harcum College", 840),
("Harrisburg Area Community College-Harrisburg", 840),
("Lackawanna College", 840),
("Lehigh Carbon Community College", 840),
("Luzerne County Community College", 840),
("Manor College", 840),
("Montgomery County Community College", 840),
("Pennsylvania Highlands Community College", 840),
("Pennsylvania Institute of Technology", 840),
("Pittsburgh Technical Institute", 840),
("Reading Area Community College", 840),
("Thaddeus Stevens College of Technology", 840),
("University of Pittsburgh-Titusville", 840),
("Valley Forge Military Academy and College", 840),
("Westmoreland County Community College", 840),
("Community College of Rhode Island", 840),
("Central Carolina Technical College", 840),
("Denmark Technical College", 840),
("Florence-Darlington Technical College", 840),
("Greenville Technical College", 840),
("Horry-Georgetown Technical College", 840),
("Midlands Technical College", 840),
("Northeastern Technical College", 840),
("Orangeburg Calhoun Technical College", 840),
("Piedmont Technical College", 840),
("Spartanburg Community College", 840),
("Spartanburg Methodist College", 840),
("Technical College of the Lowcountry", 840),
("Tri-County Technical College", 840),
("Trident Technical College", 840),
("Williamsburg Technical College", 840),
("York Technical College", 840),
("Kilian Community College", 840),
("Lake Area Technical Institute", 840),
("Mitchell Technical Institute", 840),
("Sisseton Wahpeton College", 840),
("Southeast Technical Institute", 840),
("Western Dakota Technical Institute", 840),
("Chattanooga State Community College", 840),
("Cleveland State Community College", 840),
("Columbia State Community College", 840),
("Dyersburg State Community College", 840),
("Jackson State Community College", 840),
("John A Gupton College", 840),
("Motlow State Community College", 840),
("Northeast State Community College", 840),
("Pellissippi State Community College", 840),
("Roane State Community College", 840),
("Southwest Tennessee Community College", 840),
("Volunteer State Community College", 840),
("Walters State Community College", 840),
("Alvin Community College", 840),
("Amarillo College", 840),
("Angelina College", 840),
("Blinn College", 840),
("Brookhaven College", 840),
("Cedar Valley College", 840),
("Central Texas College", 840),
("Cisco College", 840),
("Clarendon College", 840),
("Coastal Bend College", 840),
("College of the Mainland", 840),
("Collin County Community College District", 840),
("Del Mar College", 840),
("Eastfield College", 840),
("El Centro College", 840),
("El Paso Community College", 840),
("Frank Phillips College", 840),
("Galveston College", 840),
("Grayson College", 840),
("Hill College", 840),
("Houston Community College", 840),
("Howard College", 840),
("Jacksonville College-Main Campus", 840),
("Kilgore College", 840),
("Lamar Institute of Technology", 840),
("Lamar State College-Orange", 840),
("Lamar State College-Port Arthur", 840),
("Laredo Community College", 840),
("Lee College", 840),
("Lone Star College System", 840),
("McLennan Community College", 840),
("Navarro College", 840),
("North Central Texas College", 840),
("Northeast Texas Community College", 840),
("North Lake College", 840),
("Northwest Vista College", 840),
("Odessa College", 840),
("Palo Alto College", 840),
("Panola College", 840),
("Paris Junior College", 840),
("Ranger College", 840),
("Richland College", 840),
("San Antonio College", 840),
("South Plains College", 840),
("Southwest Texas Junior College", 840),
("St Philip's College", 840),
("Temple College", 840),
("Texarkana College", 840),
("Texas State Technical College-Harlingen", 840),
("Texas State Technical College-Marshall", 840),
("Texas State Technical College-Waco", 840),
("Texas State Technical College-West Texas", 840),
("Trinity Valley Community College", 840),
("Tyler Junior College", 840),
("Vernon College", 840),
("Victoria College", 840),
("Weatherford College", 840),
("Western Texas College", 840),
("Wharton County Junior College", 840),
("Latter-day Saints Business College", 840),
("Salt Lake Community College", 840),
("Community College of Vermont", 840),
("Central Virginia Community College", 840),
("Dabney S Lancaster Community College", 840),
("Danville Community College", 840),
("Eastern Shore Community College", 840),
("Germanna Community College", 840),
("John Tyler Community College", 840),
("J Sargeant Reynolds Community College", 840),
("Lord Fairfax Community College", 840),
("Mountain Empire Community College", 840),
("New River Community College", 840),
("Northern Virginia Community College", 840),
("Patrick Henry Community College", 840),
("Paul D Camp Community College", 840),
("Piedmont Virginia Community College", 840),
("Rappahannock Community College", 840),
("Richard Bland College of the College of William and Mary", 840),
("Southside Virginia Community College", 840),
("Southwest Virginia Community College", 840),
("Thomas Nelson Community College", 840),
("Tidewater Community College", 840),
("Virginia Highlands Community College", 840),
("Virginia Western Community College", 840),
("Wytheville Community College", 840),
("Bates Technical College", 840),
("Bellingham Technical College", 840),
("Big Bend Community College", 840),
("Cascadia Community College", 840),
("Clark College", 840),
("Clover Park Technical College", 840),
("Edmonds Community College", 840),
("Everett Community College", 840),
("Grays Harbor College", 840),
("Green River Community College", 840),
("Highline Community College", 840),
("Lower Columbia College", 840),
("Pierce College at Puyallup", 840),
("Renton Technical College", 840),
("Shoreline Community College", 840),
("Skagit Valley College", 840),
("South Puget Sound Community College", 840),
("Spokane Community College", 840),
("Spokane Falls Community College", 840),
("Tacoma Community College", 840),
("Walla Walla Community College", 840),
("Wenatchee Valley College", 840),
("Whatcom Community College", 840),
("Yakima Valley Community College", 840),
("Blue Ridge Community and Technical College", 840),
("Bridgemont Community and Technical College", 840),
("Eastern West Virginia Community and Technical College", 840),
("Huntington Junior College", 840),
("Kanawha Valley Community and Technical College", 840),
("Mountwest Community and Technical College", 840),
("New River Community and Technical College", 840),
("Pierpont Community and Technical College", 840),
("Southern West Virginia Community and Technical College", 840),
("West Virginia Northern Community College", 840),
("Blackhawk Technical College", 840),
("Chippewa Valley Technical College", 840),
("Fox Valley Technical College", 840),
("Gateway Technical College", 840),
("Lac Courte Oreilles Ojibwa Community College", 840),
("Lakeshore Technical College", 840),
("Madison Area Technical College", 840),
("Mid-State Technical College", 840),
("Milwaukee Area Technical College", 840),
("Moraine Park Technical College", 840),
("Nicolet Area Technical College", 840),
("Northcentral Technical College", 840),
("Northeast Wisconsin Technical College", 840),
("Southwest Wisconsin Technical College", 840),
("University of Wisconsin Colleges", 840),
("Waukesha County Technical College", 840),
("Western Technical College", 840),
("Wisconsin Indianhead Technical College", 840),
("Casper College", 840),
("Central Wyoming College", 840),
("Eastern Wyoming College", 840),
("Laramie County Community College", 840),
("Northwest College", 840),
("Sheridan College", 840),
("Western Wyoming Community College", 840),
("Trinity Bible College & Graduate School", 840),
("University of Michigan-Flint", 840),
("Kenai Peninsula College", 840),
("Mat-Su College", 840),
("Kodiak College", 840),
("Alaska Pacific University", 840),
("Wayland Baptist University", 840),
("Polk State College", 840),
("Brescia University", 840),
("Rogers State University", 840),
("Neumann University", 840),
("Ashford University", 840),
("McPherson College", 840),
("Community College System of New Hampshire", 840),
("Medical University of South Carolina", 840)