DROP TABLE IF EXISTS wp_career_fair.ref_wcc_employ_status;

CREATE TABLE wp_career_fair.ref_wcc_employ_status 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Unemployed');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Further Study');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Self-employed with no employees');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Full-time permanent employed');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Full-time contract employed');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Part-time contract employed');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Fixed-term contract employed');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Freelancers');
INSERT IGNORE INTO ref_wcc_employ_status (val) VALUES ('Own Business consisting employees');


DROP TABLE IF EXISTS wp_career_fair.ref_wcc22_qualification;

CREATE TABLE wp_career_fair.ref_wcc22_qualification 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('No formal education');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('UPSR Level');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('PMR/ PT3 Level');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('SKM Level 1 &amp; 2');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('SPM Level');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('STPM Level/ Matriculation/ Foundation/ Pre-University');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Program');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('SKM Level 3');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Diploma/ SKM Level 4');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Advanced Diploma/ SKM Level 5');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Bachelor’s Degree/ Graduate Diploma/ Graduate');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Certificate');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Master’s Degree/ Postgraduate Diploma/ Postgraduate');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Certificate');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('PhD/ Doctoral Degree');
INSERT IGNORE INTO ref_wcc22_qualification (val) VALUES ('Others (Please specify in field below)');



DROP TABLE IF EXISTS wp_career_fair.ref_wcc22_current_industry;

CREATE TABLE wp_career_fair.ref_wcc22_current_industry 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('Not Applicable');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('A - Agriculture, forestry and fishing');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('B - Mining and quarrying');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('C - Manufacturing');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('D - Electricity, gas, steam and air conditioning supply');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('E - Water supply; sewerage, waste management and remediation activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('F - Construction');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('G - Wholesale and retail trade; repair of motor vehicles and motorcycles');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('H - Transportation and storage');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('I - Accommodation and food service activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('J - Information and communication');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('K - Financial and insurance/takaful activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('L - Real estate activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('M - Professional, scientific and technical activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('N - Administrative and support service activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('O - Public administration and defence; compulsory social security');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('P - Education');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('Q - Human health and social work activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('R - Arts, entertainment and recreation');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('S - Other service activities');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('T - Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use');
INSERT IGNORE INTO ref_wcc22_current_industry (val) VALUES ('U - Activities of extraterritorial organizations and bodies');


DROP TABLE IF EXISTS wp_career_fair.ref_wcc22_preferred_emp;

CREATE TABLE wp_career_fair.ref_wcc22_preferred_emp 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Internship');
INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Full-time permanent');
INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Full-time contract');
INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Part-time contract');
INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Fixed-term contract');
INSERT IGNORE INTO ref_wcc22_preferred_emp (val) VALUES ('Freelancers');




DROP TABLE IF EXISTS wp_career_fair.ref_wcc22_field_study;

CREATE TABLE wp_career_fair.ref_wcc22_field_study 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0000 Generic programmes and qualifications not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0011 Basic programmes and qualifications');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0021 Literacy and numeracy');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0031 Personal skills');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0099 Generic programmes and qualifications not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0110 Education not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0111 Education science');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0112 Training for pre-school teachers');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0113 Educator training without subject specialisation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0114 Educator training with subject specialisation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0119 Programmes and qualifications involving education not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0188 Inter-disciplinary programmes and qualifications involving education');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0200 Arts and humanities not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0211 Audio-visual techniques and media production');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0212 Fashion, interior and industrial design');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0213 Fine arts');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0214 Craft skills');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0215 Music and performing arts');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0216 Film, television and screen studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0219 Arts not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0221 Religion and theology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0222 History and archaeology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0223 Philosophy and ethics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0224 Islamic studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0229 Humanities (except languages) not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0231 Language acquisition');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0232 Literature and linguistics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0233 National language');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0239 Languages not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0288 Inter-disciplinary programmes and qualifications involving arts and humanities');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0299 Arts and humanities not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0300 Social sciences, journalism and information not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0311 Economics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0312 Social Sciences and Public Policy');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0313 Psychology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0314 Sociology and cultural studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0319 Social and behavioural sciences not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0321 Journalism and reporting');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0322 Library, information and archival studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0323 Media and communication');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0329 Journalism, information and communication not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0388 Inter-disciplinary programmes and qualifications involving social sciences, journalism and information');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0399 Social sciences, journalism and information not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0400 Business, administration and law not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0411 Accounting, auditing and taxation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0412 Finance, banking and insurance');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0413 Islamic banking and finance');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0414 Management and administration');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0415 Marketing and advertising');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0416 Secretarial and office studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0417 Work skills');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0419 Business and administration not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0421 Law');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0488 Inter-disciplinary programmes and qualifications involving business, administration and law');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0499 Business, administration and law not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0500 Natural sciences, mathematics and statistics not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0511 Biology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0512 Biochemistry');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0519 Biological and related sciences not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0521 Environmental sciences');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0522 Natural environments and wildlife');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0529 Environment not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0531 Chemistry');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0532 Earth sciences');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0533 Physics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0539 Physical sciences not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0540 Mathematics and statistics not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0541 Mathematics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0542 Statistics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0588 Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0599 Natural sciences, mathematics and statistics not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0610 Information and communication technologies (ICTs) not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0611 Information technology and information system');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0612 Software engineering');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0613 Computer science');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0614 Computer use');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0619 Information and communication technologies (ICTs) not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0688 Inter-disciplinary programmes and qualifications involving information and communication technologies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0700 Engineering, manufacturing and construction not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0711 Chemical engineering and processes');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0712 Electricity and energy');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0713 Electronics and automation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0714 Mechanics and metal trades');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0715 Motor vehicles, ships and aircraft');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0716 Civil engineering');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0717 Environmental protection technology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0719 Engineering and engineering trades not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0721 Food processing');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0722 Materials (glass, paper, plastic and wood)');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0723 Textiles (clothes, footwear and leather)');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0724 Mining and extraction');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0729 Manufacturing and processing not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0731 Architecture');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0732 Urban and regional planning');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0733 Building and construction');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0734 Surveying');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0741 Engineering technology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0788 Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0799 Engineering, manufacturing and construction not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0800 Agriculture, forestry, fisheries and veterinary not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0811 Crop and livestock production');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0812 Horticulture');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0819 Agriculture not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0821 Forestry');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0831 Fisheries');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0841 Veterinary');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0888 Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0899 Agriculture, forestry, fisheries and veterinary not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0900 Health and welfare not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0911 Dental studies');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0912 Medicine');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0913 Nursing, midwifery and medical assistance');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0914 Medical diagnostic and treatment technology');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0915 Therapy and rehabilitation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0916 Pharmacy');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0917 Traditional and complementary medicine and therapy');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0919 Health not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0921 Care of elderly and of disabled adults');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0922 Child care and youth services');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0923 Social work and counselling');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0929 Welfare not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0988 Inter-disciplinary programmes and qualifications involving health and welfare');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('0999 Health and welfare not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1000 Services not further defined');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1011 Domestic services');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1012 Hair and beauty services');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1013 Hotel, restaurants and catering');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1014 Sports');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1015 Travel, tourism and leisure');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1019 Personal services not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1021 Community sanitation');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1022 Occupational health and safety');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1029 Hygiene and occupational health services not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1031 Military and defence');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1032 Protection of persons and property');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1039 Security services not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1041 Transport services');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1088 Inter-disciplinary programmes and qualifications involving services');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('1099 Services not elsewhere classified');
INSERT IGNORE INTO ref_wcc22_field_study (val) VALUES ('9999 Field unknown');





DROP TABLE IF EXISTS wp_career_fair.ref_wcc22_current_role;

CREATE TABLE wp_career_fair.ref_wcc22_current_role 
( 
  ID INT NOT NULL AUTO_INCREMENT , 
  val VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ,
  PRIMARY KEY (ID), UNIQUE(val), INDEX (val)
) ENGINE = InnoDB;

INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('Not Applicable');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1111 Legislators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1112 Senior Government Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1113 Traditional Chiefs And Heads Of Village');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1114 Senior Officials Of Special-Interest Organisations');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1121 Managing Directors And Chief Executives');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1211 Finance Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1212 Human Resource Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1213 Policy And Planning Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1214 Business Services Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1215 Administrative Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1216 Quality Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1219 Business Services And Administration Managers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1221 Sales And Marketing Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1222 Advertising And Public Relations Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1223 Research And Development Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1311 Agricultural, Forestry And Livestock Production Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1312 Aquaculture And Fisheries Production Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1321 Manufacturing Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1322 Mining Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1323 Construction Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1324 Supply, Distribution And Related Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1411 Hotel And Homestay Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1412 Restaurant Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1421 Retail And Wholesale Trade Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1511 Information And Communications Technology Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1611 Child Care Services Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1612 Health Services Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1613 Aged Care Services Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1614 Social Welfare Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1615 Education Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1616 Financial And Insurance Services Branch Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1617 Legal Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1618 Property Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1619 Professional Services Managers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1621 Sports And Recreation Centre Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1622 Personal Care, Cleaning And Related Services Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1623 Security Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1624 Cultural Centre, Museum And Library Managers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('1629 Other Services Managers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2111 Physicists And Astronomers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2112 Meteorologists And Seismologists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2113 Chemists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2114 Geologists And Geophysicists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2121 Mathematicians, Actuaries And Statisticians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2131 Biologists, Botanists, Zoologists And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2132 Farming, Forestry, Plantation, And Fisheries Advisers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2133 Environmental Protection Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2134 Pharmacologists, Pathologists And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2141 Industrial And Production Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2142 Civil Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2143 Environmental Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2144 Mechanical Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2145 Chemical Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2146 Mining Engineers, Metallurgists And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2149 Engineering Professionals (Excluding Electrotechnology) Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2151 Electrical Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2152 Electronic Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2153 Telecommunications Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2161 Building Architects');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2162 Landscape Architects');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2163 Product And Garment Designers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2164 Town And Traffic Planners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2165 Cartographers And Surveyors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2166 Graphic And Multimedia Designers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2171 Ship Engineers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2172 Ship Deck Officers And Pilots');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2173 Aircraft Pilots And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2174 Air Traffic Controllers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2175 Train/ Locomotive Controllers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2179 Transport Controllers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2181 Mining Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2182 Manufacturing Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2183 Construction Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2211 Generalist Medical Practitioners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2212 Specialist Medical Practitioners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2221 Nursing Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2222 Midwifery Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2231 Traditional And Complementary Medicine Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2241 Paramedical Practitioners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2251 Veterinarians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2261 Dentists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2262 Pharmacists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2263 Environmental And Occupational Health And Hygiene Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2264 Physiotherapists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2265 Dieticians And Nutritionists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2266 Audiologists And Speech Therapists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2267 Optometrists And Ophthalmic Opticians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2268 Occupational Therapists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2269 Health Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2311 University And Higher Education Teaching Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2321 Vocational Education Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2331 Secondary School Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2341 Primary School Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2342 Early Childhood Educators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2351 Music Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2352 Arts Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2353 Performing Arts Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2361 Language Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2371 Religious Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2381 Vocational Training Officers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2391 Education Method Specialists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2392 Special Needs Teachers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2393 Information Technology Trainers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2399 Teaching Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2411 Accountants And Auditors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2412 Financial And Investment Advisers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2413 Financial Analysts');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2421 Management And Organisation Analysts');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2422 Policy Administration Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2423 Personnel And Career Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2424 Training And Staff Development Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2425 Administrative Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2426 Research And Development Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2431 Advertising And Marketing Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2432 Public Relations Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2433 Technical And Medical Sales Professionals (Excluding ICT)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2434 Information And Communications Technology (ICT) Sales Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2511 Computer Systems Analysts');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2512 Software Developers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2513 Web And Multimedia Developers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2514 Application Programmers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2519 Software And Application Developers And Analysts Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2521 Database Designers And Administrators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2522 Information Technology System Administrators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2523 Computer Network Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2524 Data Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2531 Cyber Security Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2541 Animation And Visual Effects Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2542 Digital Games And E-Sport Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2543 Creative Contents Designer Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2611 Lawyers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2612 Judges');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2619 Legal Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2711 Hotel Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2712 Restaurant Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2811 Archivists And Curators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2812 Librarians And Related Information Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2821 Economists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2822 Sociologists, Anthropologists And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2823 Philosophers, Historians And Political Scientists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2824 Psychologists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2825 Social Work And Counselling Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2826 Religious Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2831 Authors And Related Writers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2832 Journalists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2833 Translators, Interpreters And Other Linguists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2841 Visual Artists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2842 Musicians, Singers And Composers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2843 Dancers And Choreographers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2844 Film, Stage And Related Directors And Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2845 Actors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2846 Announcers On Radio, Television And Other Media');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2847 Clowns, Magicians, Acrobats And Related Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2848 Animal Keepers And Trainers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2849 Creative And Performing Artists Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2911 Professional Customs And Border Inspectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2912 Profesional Taxation And Excise Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2913 Professional Government Social Benefit Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2914 Professional Government Licensing Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2915 Professional Police Inspectors And Detectives');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2916 Professional Civil Defence Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('2919 Regulatory Government Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3111 Chemical And Physical Science Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3112 Civil Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3113 Electrical Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3114 Electronics Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3115 Mechanical Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3116 Chemical Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3117 Mining And Metallurgical Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3118 Draughtspersons And Surveying Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3119 Industrial And Production Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3121 Mining Supervisors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3122 Manufacturing Supervisors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3123 Construction Supervisors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3129 Other Supervisors Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3131 Power Production Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3132 Incinerator And Water Treatment Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3133 Chemical Processing Plant Controllers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3134 Petroleum And Natural Gas Refining Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3135 Metal Production Process Controllers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3139 Process Control Technicians Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3141 Life Science Technicians (Excluding Medical)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3142 Agricultural And Livestock Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3143 Forestry Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3144 Fishery Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3151 Aircraft Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3152 Ship/ Marine Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3153 Train/ Locomotive Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3154 Motor Vehicle Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3159 Transport Technicians Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3161 Nuclear Research And Development Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3211 Medical Imaging And Therapeutic Equipment Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3212 Medical And Pathology Laboratory Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3213 Pharmaceutical Technicians And Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3214 Medical And Dental Prosthetic Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3215 Orthotic And Prosthetic Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3221 Nursing Associate Professionals (Except Dental)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3222 Midwifery Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3231 Traditional And Complementary Medicine Associate   Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3241 Veterinary Technicians And Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3251 Dental Assistants And Therapists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3252 Medical Record And Health Information Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3253 Community Health Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3254 Dispensing Opticians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3255 Physiotherapy Technicians And Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3256 Medical Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3257 Environmental And Occupational Health Inspectors And Associates');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3258 Ambulance Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3259 Health Associate Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3311 Securities And Finance Dealers And Brokers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3312 Credit And Loan Officers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3313 Accounting And Auditing Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3314 Statistical, Mathematical And Actuarial Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3315 Valuers And Loss Assessors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3321 Insurance Representatives');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3322 Commercial Sales Representatives');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3323 Buyers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3324 Trade Brokers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3331 Clearing And Forwarding Agents');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3332 Conference And Event Agents');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3333 Employment Agents And Contractors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3334 Real Estate And Property Agents');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3339 Business Services Agents Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3341 Administrative Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3342 Legal Secretaries');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3343 Administrative And Executive Secretaries');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3344 Medical Secretaries');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3411 Legal And Related Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3511 Information And Communications Technology Operation Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3512 Information And Communications Technology User Support Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3513 Computer Network And Systems Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3514 Web Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3521 Broadcasting And Audio-Visual Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3522 Telecommunications Engineering Technicians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3611 Social Work Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3612 Religious Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3621 Athletes And Sports Players');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3622 Sports Coaches, Instructors And Officials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3623 Fitness And Recreation Instructors And Programme Leaders');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3631 Photographers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3632 Interior Designers And Decorators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3633 Gallery, Museum And Library Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3634 Cultural And Artistic Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3639 Artistic And Cultural Associate Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3641 Chefs');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3711 Customs And Border Inspector Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3712 Taxation And Excise Official Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3713 Government Social Benefit Official Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3714 Government Licensing Official Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3715 Police Officers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3716 Civil Defence Associate Professionals');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('3719 Regulatory Government Associate Professionals Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4111 General Office Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4121 Secretaries (General)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4131 Typist And Word Processor Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4132 Data Entry Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4211 Bank Tellers And Related Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4212 Bookmakers, Croupiers And Related Gaming Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4213 Pawnbrokers And Money-Lenders');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4214 Debt And Rent Collectors And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4221 Travel Consultants And Related Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4222 Contact Centre Information Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4223 Telephone Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4224 Receptionists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4225 Enquiry Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4226 Survey And Market Research Interviewers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4229 Client Information Workers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4311 Accounting And Book-Keeping Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4312 Statistical, Finance And Insurance Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4313 Payroll Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4321 Stock Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4322 Production Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4323 Transport Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4411 Library Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4412 Mail Carriers And Sorting Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4413 Coding, Proof-Reading And Related Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4414 Scribes And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4415 Filing And Copying Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4416 Personnel Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('4419 Clerical Support Workers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5111 Travel Attendants And Travel Stewards');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5112 Transport Conductors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5113 Travel Guides');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5121 Cooks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5131 Waiters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5132 Waiters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5141 Hairdressers, Beauticians And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5142 Hairdressers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5151 Building And Housekeeping Supervisors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5152 Cleaning And Housekeeping Supervisors In Offices, Hotels And Other Establishments');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5153 Domestic Housekeepers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5161 Other Personal Services Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5162 Astrologers, Fortune-Tellers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5163 Companions And Valets');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5164 Undertakers And Embalmers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5165 Pet Groomers And Animal Care Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5169 Driving Instructors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5211 Street And Market Salespersons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5212 Stall And Market Salespersons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5221 Shop Salespersons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5222 Shopkeepers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5223 Shop Supervisors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5231 Cashiers And Ticket Clerks');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5241 Other Sales Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5242 Fashion And Other Models');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5243 Sales Demonstrators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5244 Door-To-Door Salespersons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5245 Contact Centre Salespersons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5246 Service Station And Pump Attendants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5249 Food Counter Attendants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5311 Child Care Workers And Teachers\' Aides');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5312 Child Care Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5321 Personal Care Workers In Health Services');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5322 Health Care Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5329 Home-Based Personal Care Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5411 Protective Services Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5412 Fire Fighters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5413 Low Rank Police Officers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5414 Prison Guards');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5415 Security Guards');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('5419 Immigration/ Customs Officers And Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6111 Market Gardeners And Crop Growers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6112 Field Crop Growers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6113 Shrub Crop Growers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6114 Gardeners, Horticultural And Nursery Growers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6115 Mixed Crop Growers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6121 Animal Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6122 Livestock And Dairy Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6123 Poultry Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6129 Apiarists And Sericulturists');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6131 Mixed Crop And Animal Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6211 Skilled Forestry And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6221 Skilled Fishery Workers, Hunters And Trappers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6222 Fishery And Aquaculture Producers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6223 Skilled Inland And Coastal Waters Fishery Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6224 Skilled Deep-Sea Fishery Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6311 Subsistence Crop Farmers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6321 Subsistence Livestock Farmers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6331 Subsistence Mixed Crop And Livestock Farmers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('6341 Subsistence Fisherman, Hunters, Trappers And Gatherers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7111 Building Frame And Related Trades Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7112 House Builders And Construction Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7113 Bricklayers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7114 Stonemasons, Stone Cutters, Splitters And Carvers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7115 Concrete Placers, Concrete Finishers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7119 Carpenters And Joiners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7121 Building Finishers And Related Trades Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7122 Roofers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7123 Floor Layers And Tile Setters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7124 Plasterers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7125 Insulation Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7126 Glaziers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7127 Plumbers And Pipe Fitters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7131 Painters, Building Structure Cleaners And Related Trades Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7132 Painters And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7133 Spray Painters And Varnishers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7211 Sheet And Structural Metal Workers, Moulders And Welders And Related Trades Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7212 Metal Moulders And Coremakers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7213 Welders And Flame Cutters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7214 Sheet-Metal Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7215 Structural-Metal Preparers And Erectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7221 Blacksmiths, Toolmakers And Related Trades Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7222 Blacksmiths, Hammersmiths And Forging-Press Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7223 Toolmakers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7224 Metal Working Machine Tool Setters And Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7231 Machinery Mechanics And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7232 Motor Vehicle Mechanics And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7233 Aircraft Engine Mechanics And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7234 Agricultural And Industrial Machinery Mechanics And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7239 Bicycle And Related Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7311 Handicraft Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7312 Precision Instrument Makers And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7313 Musical Instrument Makers And Tuners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7314 Jewellery And Precious Metal Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7315 Potters And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7316 Glass Makers, Cutters, Grinders And Finishers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7317 Sign Writers, Decorative Painters, Engravers And Etchers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7318 Handicraft Workers In Wood, Basketry And Related Materials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7319 Handicraft Workers In Textile, Leather And Related Materials');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7321 Pre-Press Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7322 Printers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7323 Print Finishing And Binding Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7324 Printing And Photo Engravers And Etchers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7411 Building And Related Electricians');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7412 Electrical Mechanics And Fitters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7413 Electrical Line Installers And Repairers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7421 Electronics Mechanics And Services');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7422 Information And Communications Technology Installers And Services');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7511 Meat And Fish Processing Workers And Related Food Preparers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7512 Bakers, Pastry And Pasta-Cooks, And Confectionery Makers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7513 Dairy-Product Makers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7514 Fruit, Vegetable And Related Preservers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7515 Food And Beverage Tasters And Graders');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7516 Tobacco Preparers And Tobacco Product Makers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7611 Wood Treaters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7612 Cabinet-Makers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7613 Woodworking-Machine Tool Setters And Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7621 Tailors, Dressmakers, Furriers And Hatters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7622 Garment And Related Pattern-Makers And Cutters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7623 Shoemakers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7624 Upholsterers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7625 Pelt Dressers, Tanners And Fellmongers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7631 Underwater Divers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7632 Shotfirers And Blasters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7633 Product Graders And Testers (Excluding Foods And Beverages)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7634 Fumigators And Pest And Weed Controllers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('7639 Other Related Craft Workers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8111 Miners And Quarry Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8112 Mineral And Stone Processing Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8113 Well Drillers And Borers And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8114 Cement, Stone And Other Mineral Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8121 Metal Processing Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8122 Metal Finishing, Plating And Coating Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8131 Chemical Products Plant And Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8132 Photographic Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8141 Rubber Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8142 Plastic Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8143 Paper Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8151 Fibre Preparing, Spinning And Winding Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8152 Weaving And Knitting Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8153 Sewing Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8154 Bleaching, Dyeing And Fabric Cleaning Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8155 Fur And Leather Preparing Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8156 Shoemaking And Related Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8157 Laundry Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8159 Textile, Fur And Leather Products Machine Operators Not Elesewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8161 Food And Related Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8171 Pulp And Papermaking Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8172 Wood Processing Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8173 Wood Products Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8181 Glass And Ceramics Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8182 Steam Engine And Boiler Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8183 Packing, Bottling And Labelling Machine Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8189 Stationary Plant And Machine Operators Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8211 Mechanical Machinery Assemblers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8212 Electrical And Electronic Equipment Assemblers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8213 Leather, Metal, Rubber And Plastic Products Assemblers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8219 Assemblers Not Elsewhere Classified');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8221 Machine-Tool Setter-Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8311 Locomotive Engine Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8312 Railway Brake, Signal And Switch Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8321 Motorcycle Riders (Drivers)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8322 Car, Taxi And Van Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8331 Bus And Tram Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8332 Heavy Truck And Lorry Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8341 Mobile Farm And Forestry Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8342 Earth-Moving And Related Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8343 Crane, Hoist And Related Plant Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8344 Lifting Truck Operators');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('8351 Ships Deck Crews And Related Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9111 Domestic, Hotel And Office Cleaners And Helpers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9112 Domestic Cleaners And Helpers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9121 Vehicle, Window, Laundry And Other Hand Cleaning Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9122 Hand Launderers And Ironers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9123 Vehicle Cleaners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9129 Surface And Window Cleaners');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9211 Agricultural, Forestry, Farming And Fishery Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9212 Crop Farm Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9213 Livestock Farm Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9214 Mixed Crop And Livestock Farm Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9215 Garden And Horticultural Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9216 Forestry Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9219 Fishery And Aquaculture Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9311 Mining And Construction Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9312 Mining And Quarrying Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9313 Civil Engineering Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9321 Manufacturing Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9329 Manufacturing Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9331 Transport And Storage Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9332 Hand Or Pedal Vehicle Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9333 Animal-Drawn Machinery And Vehicle Drivers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9334 Transport And Storage Labourers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9411 Food Preparation Assistants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9412 Fast Food Preparers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9511 Street And Related Service Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9521 Street Vendors (Excluding Food)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9611 Garbage Collectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9612 Garbage Collectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9613 Refuse And Recyclable Waste Sorters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9621 Other Elementary Workers');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9622 Messengers, Package Deliverers And Luggage Porters');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9623 Odd-Job Persons');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9624 Meter Readers And Vending-Machine Collectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9625 Water And Firewood Collectors');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('9629 Attendants');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0111 Professional Duty Officers (Malaysian Army)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0121 General Duty Officers (Malaysian Army)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0131 Personnel Of Other Ranks (Malaysian Army)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0211 General Duty Officers (Royal Malaysian Navy)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0221 Personnel Of Other Ranks (Royal Malaysian Navy)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0311 General Duty Officers (Royal Malaysian Air Force)');
INSERT IGNORE INTO ref_wcc22_current_role (val) VALUES ('0321 Personnel Of Other Ranks (Royal Malaysian Air Force)');
