

const Type = {
    COMPANY_SCHEDULE_INTERVIEW: "COMPANY_SCHEDULE_INTERVIEW",
    COMPANY_START_CHAT: "COMPANY_START_CHAT",
    INTERVIEW_REMINDER: "INTERVIEW_REMINDER",
}

module.exports = {
    Type
};