

const Type = {
    COMPANY_SCHEDULE_INTERVIEW: "COMPANY_SCHEDULE_INTERVIEW",
    COMPANY_START_CHAT: "COMPANY_START_CHAT",
    INTERVIEW_REMINDER: "INTERVIEW_REMINDER",
    INTERVIEW_REMINDER_1DAY: "INTERVIEW_REMINDER_1DAY",
    INTERVIEW_PENDING_REMINDER_1DAY : "INTERVIEW_PENDING_REMINDER_1DAY"
}

module.exports = {
    Type
};