obj = {
  "arts-visual-and-performing": {
    "id": "arts-visual-and-performing",
    "label": "Arts, Visual, and Performing",
    "children": [
      "Arts and Entertainment Management",
      "Ballet",
      "Crafts, Folk Art, and Artisanry",
      "Dance",
      "Commercial and Advertising Art",
      "Commercial Photography",
      "Design and Visual Communications",
      "Fashion Design",
      "Game and Interactive Media Design",
      "Graphic Design",
      "Illustration",
      "Industrial and Product Design",
      "Interior Design",
      "Digital Arts",
      "Documentary Production",
      "Film Production",
      "Film Studies",
      "Art History, Criticism, and Conservation",
      "Arts, General",
      "Ceramics",
      "Drawing",
      "Fiber, Textile, and Weaving Arts",
      "Metal and Jewelry Arts",
      "Multimedia",
      "Painting",
      "Printmaking",
      "Sculpture",
      "Studio Arts",
      "Fine and Studio Arts Management",
      "Brass Instruments",
      "Conducting",
      "Jazz Studies",
      "Keyboard Instruments",
      "Music",
      "Music History, Literature, and Theory",
      "Music Pedagogy",
      "Music Performance",
      "Music Technology",
      "Music Theory and Composition",
      "Musicology and Ethnomusicology",
      "Percussion Instruments",
      "Stringed Instruments",
      "Voice and Opera",
      "Woodwind Instruments",
      "Music Management and Merchandising",
      "Photography",
      "Acting",
      "Costume Design",
      "Directing and Theatrical Production",
      "Musical Theater",
      "Playwriting and Screenwriting",
      "Theater Arts",
      "Theater Design and Stagecraft",
      "Theater Literature, History, and Criticism",
      "Theater Management",
      "Visual and Performing Arts, General"
    ]
  },
  "english-language-and-literature": {
    "id": "english-language-and-literature",
    "label": "English Language and Literature",
    "children": [
      "American Literature",
      "British Literature",
      "Canadian Literature",
      "Children's and Adolescent Literature",
      "Creative Writing",
      "English",
      "English Composition",
      "General Literature",
      "Professional, Technical, Business, and Scientific Writing",
      "Rhetoric and Composition",
      "Speech and Rhetorical Studies",
      "Writing, General"
    ]
  },
  "languages-literatures-and-linguistics": {
    "id": "languages-literatures-and-linguistics",
    "label": "Languages, Literatures, and Linguistics",
    "children": [
      "African Languages",
      "American Sign Language (ASL)",
      "Ancient Greek",
      "Ancient Near Eastern and Biblical Languages",
      "Applied Linguistics",
      "Arabic",
      "Celtic Languages",
      "Classics",
      "Comparative Literature",
      "Chinese",
      "East Asian Languages, General",
      "Japanese",
      "Korean",
      "Filipino/Tagalog",
      "Foreign Languages and Literatures, General",
      "Danish",
      "Dutch",
      "German",
      "Germanic Languages, General",
      "Norwegian",
      "Scandinavian Languages",
      "Swedish",
      "Hebrew",
      "Hindi",
      "Iranian Languages",
      "Language Interpretation and Translation",
      "Latin",
      "Linguistics",
      "Linguistics of Sign Language",
      "Modern Greek",
      "Native American Languages",
      "French",
      "Hispanic and Latin American Languages",
      "Italian",
      "Portuguese",
      "Romance Languages",
      "Spanish",
      "Sanskrit and Classical Indian Languages",
      "Semitic Languages, General",
      "Sign Language Interpretation",
      "Bosnian, Serbian, and Croatian",
      "Czech",
      "Polish",
      "Russian",
      "Slavic Languages, General",
      "Slovak",
      "Ukrainian",
      "South Asian Languages, General",
      "Southeast Asian Languages, General",
      "Turkish",
      "Urdu"
    ]
  },
  "philosophy-and-religion": {
    "id": "philosophy-and-religion",
    "label": "Philosophy and Religion",
    "children": [
      "Applied and Professional Ethics",
      "Buddhist Studies",
      "Christian Studies",
      "Ethics",
      "Islamic Studies",
      "Judaic Studies",
      "Logic",
      "Philosophy",
      "Philosophy and Religious Studies, General",
      "Religious Studies"
    ]
  },
  "business": {
    "id": "business",
    "label": "Business",
    "children": [
      "Accounting",
      "Accounting and Business Management",
      "Accounting and Finance",
      "Accounting Technology and Bookkeeping",
      "Auditing",
      "Banking and Financial Support Services",
      "Credit Management",
      "Finance",
      "Financial Planning",
      "International Finance",
      "Investments and Securities",
      "Public Finance",
      "Actuarial Science",
      "Business Administration and Management",
      "Customer Service Management",
      "Ecommerce",
      "Logistics and Materials Management",
      "Nonprofit Management",
      "Office Management",
      "Operations Management",
      "Organizational Leadership",
      "Professional Golf Management",
      "Project Management",
      "Purchasing, Procurement, and Contracts Management",
      "Research and Development Management",
      "Retail Management",
      "Transportation Management",
      "Administrative Assistance and Secretarial Science",
      "Customer Service",
      "Executive Assistant and Executive Secretary",
      "General Office Services",
      "Office Technology",
      "Receptionist",
      "Warehousing and Inventory Management",
      "Casino Management",
      "Hospitality Administration and Management",
      "Hotel and Motel Management",
      "Hotel, Motel, and Restaurant Management",
      "Meeting and Event Planning",
      "Resort Management",
      "Restaurant and Food Services Management",
      "Tourism and Travel Management",
      "Human Resources Development",
      "Human Resources Management",
      "Labor and Industrial Relations",
      "Labor Studies",
      "Organizational Behavior Studies",
      "Business and Managerial Economics",
      "Business Communications",
      "Business, General",
      "Business Statistics",
      "Construction Management",
      "Entrepreneurial Studies",
      "Franchising",
      "Information Resources Management",
      "Insurance",
      "International Business",
      "Knowledge Management",
      "Management Information Systems",
      "Management Science",
      "Real Estate",
      "Apparel and Accessories Marketing Operations",
      "Auctioneering",
      "Fashion Merchandising",
      "Fashion Modeling",
      "Financial Services Marketing Operations",
      "Hospitality and Recreation Marketing",
      "International Marketing",
      "Marketing",
      "Marketing Research",
      "Merchandising and Buying Operations",
      "Retailing",
      "Sales and Distribution",
      "Selling Skills and Sales Operations",
      "Special Products Marketing Operations",
      "Tourism and Travel Services Marketing Operations",
      "Tourism Marketing",
      "Vehicle Parts and Accessories Marketing Operations",
      "Small Business Administration and Management",
      "Taxation",
      "Telecommunications Management"
    ]
  },
  "health-professions-and-related-clinical-sciences": {
    "id": "health-professions-and-related-clinical-sciences",
    "label": "Health Professions and Related Clinical Sciences",
    "children": [
      "Anesthesiologist Assistance",
      "Chiropractic Assistance",
      "Clinical Laboratory Assisting",
      "Emergency Care Attendance",
      "Lactation Consultant",
      "Medical Assisting",
      "Occupational Therapy Assistance",
      "Pathology Assistance",
      "Pharmacy Technology",
      "Physical Therapy Assistance",
      "Radiologist Assistant",
      "Respiratory Therapy Assistance",
      "Speech-Language Pathology Assistant",
      "Veterinary Technology",
      "Athletic Training",
      "Cardiopulmonary Technology",
      "Cardiovascular Technology",
      "Diagnostic Medical Sonography",
      "Electrocardiograph Technology",
      "Electroneurodiagnostic and Electroencephalographic Technology",
      "Emergency Medical Technology",
      "Gene Therapy",
      "Health Physics Technology",
      "Hearing Instrument Specialist",
      "Magnetic Resonance Imaging (MRI) Technology",
      "Mammography Technology",
      "Medical Radiologic Technology",
      "Nuclear Medical Technology",
      "Perfusion Technology",
      "Physician Assistance",
      "Polysomnography",
      "Radiologic Technology",
      "Respiratory Therapy",
      "Surgical Technology",
      "Acupuncture and Oriental Medicine",
      "Alternative and Complementary Medicine and Medical Systems, General",
      "Ayurvedic Medicine",
      "Chinese Medicine and Herbology",
      "Holistic Health",
      "Homeopathic Medicine",
      "Naturopathic Medicine",
      "Aromatherapy",
      "Asian Bodywork Therapy",
      "Audiology",
      "Bioethics and Medical Ethics",
      "Blood Bank Technology",
      "Clinical Genetics Technology",
      "Clinical Laboratory Science",
      "Clinical Laboratory Technology",
      "Cytotechnology",
      "Dialysis Technology",
      "Hematology Technology",
      "Histologic Assistance",
      "Histologic Technology",
      "Ophthalmic Laboratory Technology",
      "Phlebotomy",
      "Sterile Processing Technology",
      "Chiropractic (DC)",
      "Clinical Nutrition",
      "Communication Sciences and Disorders",
      "Dental Assisting",
      "Dental Hygiene",
      "Dental Laboratory Technology",
      "Dietetic Assistance",
      "Dietetics",
      "Dietetic Technology",
      "Health Aide",
      "Clinical Research Coordinator",
      "Health Information Technology",
      "Health Management and Clinical Assistance",
      "Health Services Administration",
      "Health Unit Coordination",
      "Hospital Facilities Administration",
      "Long Term Care Administration",
      "Medical Claims Examination",
      "Medical Insurance Billing",
      "Medical Insurance Coding",
      "Medical Office Assistance",
      "Medical Office Computer Specialist",
      "Medical Office Management",
      "Medical Reception",
      "Medical Records Administration",
      "Medical Secretary",
      "Medical Staff Services Technology",
      "Medical Transcription",
      "Ward Supervisor",
      "Health and Wellness, General",
      "Health Sciences, General",
      "Herbalism",
      "Home Health Aide",
      "Hypnotherapy",
      "Massage Therapy",
      "Medical Illustrating",
      "Medical Informatics",
      "Medication Aide",
      "Medicinal and Pharmaceutical Chemistry",
      "Addiction Counseling",
      "Clinical Pastoral Counseling",
      "Community Health Services",
      "Genetic Counseling",
      "Marriage and Family Therapy",
      "Medical Social Work",
      "Mental Health Counseling",
      "Psychiatric Technology",
      "Midwifery",
      "Movement Therapy and Movement Education",
      "Adult Health Nursing",
      "Clinical Nurse Leader",
      "Clinical Nurse Specialist",
      "Critical Care Nursing",
      "Emergency Room/Trauma Nursing",
      "Family Practice Nurse Practitioner",
      "Geriatric Nursing",
      "Maternal Health and Neonatal Nursing",
      "Mental Health Nursing",
      "Nurse Anesthetist",
      "Nursing Administration",
      "Nursing Assistance",
      "Nursing Education",
      "Nursing Midwifery",
      "Nursing Practice",
      "Nursing (RN)",
      "Nursing Science",
      "Occupational and Environmental Health Nursing",
      "Palliative Care Nursing",
      "Pediatric Nursing",
      "Practical Nursing",
      "Prenursing Studies",
      "Public Health Nursing",
      "Surgical Nursing",
      "Women's Health Nursing",
      "Ophthalmic Technology",
      "Opticianry",
      "Optometric Technology",
      "Optometry",
      "Osteopathic Medicine (DO)",
      "Pharmaceutical Marketing and Management",
      "Pharmaceutical Sciences",
      "Pharmacy",
      "Podiatric Medicine (DPM)",
      "Polarity Therapy",
      "Prechiropractic Studies",
      "Predentistry",
      "Premedicine",
      "Pre-Occupational Therapy Studies",
      "Preoptometry Studies",
      "Prepharmacy",
      "Preveterinary Studies",
      "Behavioral Aspects of Health",
      "Community Health and Preventive Medicine",
      "Environmental Health",
      "Health Physics",
      "Health Services Administration",
      "International Health",
      "Maternal and Child Health",
      "Occupational Health and Industrial Hygiene",
      "Public Health",
      "Public Health Education",
      "Rehabilitation Aide",
      "Animal-Assisted Therapy",
      "Art Therapy",
      "Dance Therapy",
      "Kinesiotherapy",
      "Music Therapy",
      "Occupational Therapy",
      "Orthotics and Prosthetics",
      "Physical Therapy",
      "Pre-Physical Therapy",
      "Rehabilitation Science",
      "Therapeutic Recreation",
      "Vocational Rehabilitation Counseling",
      "Reiki",
      "Somatic Bodywork",
      "Speech-Language Pathology",
      "Speech-Language Pathology and Audiology",
      "Sports Medicine",
      "Yoga Therapy and Teacher Training"
    ]
  },
  "area-ethnic-cultural-and-gender-studies": {
    "id": "area-ethnic-cultural-and-gender-studies",
    "label": "Area, Ethnic, Cultural, and Gender Studies",
    "children": [
      "African Studies",
      "American Studies",
      "Area Studies",
      "Asian Studies",
      "Balkans Studies",
      "Baltic Studies",
      "Canadian Studies",
      "Caribbean Studies",
      "Chinese Studies",
      "Commonwealth Studies",
      "East Asian Studies",
      "European Studies",
      "French Studies",
      "German Studies",
      "Irish Studies",
      "Italian Studies",
      "Japanese Studies",
      "Korean Studies",
      "Latin American and Caribbean Studies",
      "Latin American Studies",
      "Near and Middle Eastern Studies",
      "Pacific Rim Studies",
      "Polish Studies",
      "Regional Studies",
      "Russian, Central and Eastern European, and Eurasian Studies",
      "Russian Studies",
      "Scandinavian Studies",
      "Slavic Studies",
      "South Asian Studies",
      "Southeast Asian Studies",
      "Spanish and Iberian Studies",
      "Ukraine Studies",
      "Ural-Altaic and Central Asian Studies",
      "Western European Studies",
      "African American Studies",
      "American Indian Studies",
      "Asian American Studies",
      "Deaf Studies",
      "Disability Studies",
      "Ethnic Studies, General",
      "Folklore Studies",
      "Gay and Lesbian Studies",
      "Latino and Latina Studies",
      "Women's Studies"
    ]
  },
  "family-and-consumer-sciences": {
    "id": "family-and-consumer-sciences",
    "label": "Family and Consumer Sciences",
    "children": [
      "Apparel and Textile Manufacture",
      "Apparel and Textile Marketing",
      "Clothing and Textiles Studies",
      "Fashion and Fabric Consultation",
      "Textile Science",
      "Business, Family, and Consumer Sciences",
      "Consumer Economics",
      "Consumer Merchandising",
      "Consumer Services and Advocacy",
      "Facilities Planning and Management",
      "Family and Consumer Sciences",
      "Family and Consumer Sciences Communication",
      "Family Resource Management Studies",
      "Food Service Systems Administration",
      "Foods, Nutrition, and Wellness Studies",
      "Home Furnishings and Equipment Installers",
      "Housing Studies",
      "Adult Development and Aging",
      "Child Care",
      "Child Care Management",
      "Child Development",
      "Developmental Services Worker",
      "Family and Community Services",
      "Family Systems",
      "Human Development and Family Studies",
      "Human Nutrition",
      "Work and Family Studies"
    ]
  },
  "liberal-arts-and-sciences-general-studies-and-humanities": {
    "id": "liberal-arts-and-sciences-general-studies-and-humanities",
    "label": "Liberal Arts and Sciences, General Studies, and Humanities",
    "children": [
      "General Studies",
      "Humanities",
      "Liberal Arts and Sciences"
    ]
  },
  "multi-interdisciplinary-studies": {
    "id": "multi-interdisciplinary-studies",
    "label": "Multi-/Interdisciplinary Studies",
    "children": [
      "Accounting and Computer Science",
      "Ancient Studies",
      "Behavioral Sciences",
      "Biological and Physical Sciences",
      "Biopsychology",
      "Classical, Ancient Mediterranean, and Near Eastern Studies",
      "Cognitive Science",
      "Computational Science",
      "Cultural Resource Management",
      "Cultural Studies",
      "Dispute Resolution",
      "Gerontology",
      "Global Studies",
      "Historic Preservation and Conservation",
      "Holocaust and Related Studies",
      "Human Biology",
      "Human-Computer Interaction",
      "Intercultural, Multicultural, and Diversity Studies",
      "Marine Sciences",
      "Maritime Studies",
      "Mathematics and Computer Science",
      "Medieval and Renaissance Studies",
      "Multi-/Interdisciplinary Studies, General",
      "Museum Studies",
      "Natural Sciences",
      "Nutrition Sciences",
      "Peace and Conflict Resolution Studies",
      "Science, Technology, and Society",
      "Sustainability Studies",
      "Systems Science and Theory"
    ]
  },
  "parks-recreation-and-fitness": {
    "id": "parks-recreation-and-fitness",
    "label": "Parks, Recreation, and Fitness",
    "children": [
      "Exercise Science",
      "Golf Course Operation and Grounds Management",
      "Health and Physical Fitness",
      "Outdoor Education",
      "Parks, Recreation, and Leisure Facilities Management",
      "Parks, Recreation, and Leisure Studies",
      "Physical Fitness Technician",
      "Sports and Fitness Administration",
      "Sports Studies"
    ]
  },
  "law-and-legal-studies": {
    "id": "law-and-legal-studies",
    "label": "Law and Legal Studies",
    "children": [
      "Court Reporting",
      "Legal Administrative Assistance",
      "Legal Studies",
      "Paralegal Studies",
      "Prelaw Studies"
    ]
  },
  "military": {
    "id": "military",
    "label": "Military",
    "children": [
      "Command & Control (C3, C4I) Systems and Operations",
      "Cyber/Electronic Operations and Warfare",
      "Information Operations/Joint Information Operations",
      "Information/Psychological Warfare and Military Media Relations",
      "Intelligence, General",
      "Signal/Geospatial Intelligence",
      "Strategic Intelligence",
      "Combat Systems Engineering",
      "Directed Energy Systems",
      "Engineering Acoustics",
      "Low-Observables and Stealth Technology",
      "Operational Oceanography",
      "Space Systems Operations",
      "Undersea Warfare",
      "Aerospace Ground Equipment Technology",
      "Air and Space Operations Technology",
      "Aircraft Armament Systems Technology",
      "Explosive Ordnance/Bomb Disposal",
      "Joint Command/Task Force (C3, C4I) Systems",
      "Military Information Systems Technology",
      "Missile and Space Systems Technology",
      "Munitions Systems Technology",
      "Radar Communications and Systems Technology",
      "Military Technologies"
    ]
  },
  "public-administration-and-social-services": {
    "id": "public-administration-and-social-services",
    "label": "Public Administration and Social Services",
    "children": [
      "Community Organization and Advocacy",
      "Education Policy Analysis",
      "Health Policy Analysis",
      "Human Services",
      "International Policy Analysis",
      "Public Administration",
      "Public Policy Analysis",
      "Public Services",
      "Social Work",
      "Youth Services"
    ]
  },
  "security-and-protective-services": {
    "id": "security-and-protective-services",
    "label": "Security and Protective Services",
    "children": [
      "Computer Forensics",
      "Corrections",
      "Corrections Administration",
      "Criminal Justice",
      "Criminalistics and Criminal Science",
      "Critical Incident Response/Special Police Operations",
      "Financial Forensics and Fraud Investigation",
      "Forensic Science",
      "Juvenile Corrections",
      "Law Enforcement Administration",
      "Law Enforcement Intelligence Analysis",
      "Law Enforcement Investigation and Interviewing",
      "Law Enforcement Record-Keeping and Evidence Management",
      "Maritime Law Enforcement",
      "Police Science",
      "Protective Services Operations",
      "Security and Loss Prevention Services",
      "Security and Protective Services",
      "Security Services Administration and Management",
      "Suspension and Debarment Investigation",
      "Emergency Management/Homeland Security",
      "Fire Prevention and Safety Technology",
      "Fire Science",
      "Fire Services Administration",
      "Wildland/Forest Firefighting and Investigation"
    ]
  },
  "theological-studies-and-religious-vocations": {
    "id": "theological-studies-and-religious-vocations",
    "label": "Theological Studies and Religious Vocations",
    "children": [
      "Bible Studies",
      "Lay Ministry",
      "Ministry",
      "Missionary Studies",
      "Pastoral Counseling",
      "Pre-ministerial Studies",
      "Religious Education",
      "Sacred Music",
      "Talmudic Studies",
      "Theology",
      "Urban Ministry",
      "Women's Ministry",
      "Youth Ministry"
    ]
  },
  "agriculture-and-related-sciences": {
    "id": "agriculture-and-related-sciences",
    "label": "Agriculture and Related Sciences",
    "children": [
      "Agribusiness Operations",
      "Agricultural and Food Products Processing",
      "Agricultural Business",
      "Agricultural Business Technology",
      "Agricultural Communications",
      "Agricultural Economics",
      "Agricultural Equipment Technology",
      "Agricultural Mechanization",
      "Agricultural Power Machinery",
      "Agricultural Production",
      "Animal Husbandry",
      "Aquaculture",
      "Crop Production",
      "Dairy Husbandry and Production",
      "Horse Husbandry and Equine Science",
      "Sustainable Agriculture",
      "Viticulture and Enology",
      "Agricultural Supplies",
      "Agriculture Education Services",
      "Agriculture, General",
      "Animal Grooming",
      "Animal Breeding",
      "Animal Health",
      "Animal Nutrition",
      "Animal Sciences",
      "Dairy Science",
      "Livestock Management",
      "Poultry Science",
      "Animal Training",
      "Floristry Operations and Management",
      "Greenhouse Management",
      "Horticultural Services",
      "Landscaping",
      "Ornamental Horticulture",
      "Plant Nursery Management",
      "Turf Management",
      "Equestrian Studies",
      "Farm and Ranch Management",
      "Food Science",
      "Food Technology and Processing",
      "International Agriculture",
      "Agronomy and Crop Science",
      "Horticultural Science",
      "Plant Breeding",
      "Plant Protection and Pest Management",
      "Plant Sciences, General",
      "Range Science",
      "Soil Chemistry and Physics",
      "Soil Science",
      "Taxidermy"
    ]
  },
  "architecture-and-planning": {
    "id": "architecture-and-planning",
    "label": "Architecture and Planning",
    "children": [
      "Architectural and Building Sciences/Technology",
      "Architectural History and Criticism",
      "Architectural Technology",
      "Architecture",
      "City, Community, and Regional Planning",
      "Environmental Design",
      "Interior Architecture",
      "Landscape Architecture",
      "Real Estate Development"
    ]
  },
  "biological-and-biomedical-sciences": {
    "id": "biological-and-biomedical-sciences",
    "label": "Biological and Biomedical Sciences",
    "children": [
      "Animal Behavior and Ethology",
      "Animal Genetics",
      "Animal Physiology",
      "Biochemistry",
      "Biochemistry and Molecular Biology",
      "Biophysics",
      "Molecular Biochemistry",
      "Molecular Biology",
      "Molecular Biophysics",
      "Radiation Biology",
      "Bioinformatics",
      "Biology, General",
      "Biomedical Sciences",
      "Biometrics",
      "Biostatistics",
      "Biotechnology",
      "Botany",
      "Anatomy",
      "Cell Biology and Anatomy",
      "Cellular and Molecular Biology",
      "Cellular Biology and Histology",
      "Developmental Biology and Embryology",
      "Computational Biology",
      "Aquatic Biology and Limnology",
      "Conservation Biology",
      "Ecology",
      "Ecology and Evolutionary Biology",
      "Environmental Biology",
      "Epidemiology",
      "Evolutionary Biology",
      "Marine Biology",
      "Population Biology",
      "Systematic Biology",
      "Entomology",
      "Environmental Toxicology",
      "Genetics",
      "Genomics",
      "Immunology",
      "Medical Genetics",
      "Medical Microbiology and Bacteriology",
      "Microbiology",
      "Microbiology and Immunology",
      "Molecular Genetics",
      "Molecular Medicine",
      "Molecular Pharmacology",
      "Neuroanatomy",
      "Neurobiology and Anatomy",
      "Neurobiology and Behavior",
      "Neuroscience",
      "Parasitology",
      "Pharmacology",
      "Pharmacology and Toxicology",
      "Aerospace Physiology and Medicine",
      "Cell Physiology",
      "Endocrinology",
      "Exercise Physiology",
      "Molecular Physiology",
      "Oncology",
      "Pathology",
      "Physiology",
      "Reproductive Biology",
      "Vision Science",
      "Plant Genetics",
      "Plant Molecular Biology",
      "Plant Pathology",
      "Plant Physiology",
      "Toxicology",
      "Wildlife Biology",
      "Zoology"
    ]
  },
  "communications-technologies": {
    "id": "communications-technologies",
    "label": "Communications Technologies",
    "children": [
      "Animation and Special Effects",
      "Communications Technologies",
      "Computer Typography and Composition",
      "Desktop Publishing",
      "Graphic Communications",
      "Photographic, Film, and Video Technology",
      "Platemaking and Imaging",
      "Printing Management",
      "Printing Press Operation",
      "Printing Technology",
      "Radio and Television Broadcasting Technology",
      "Recording Arts Technology"
    ]
  },
  "computer-and-information-sciences": {
    "id": "computer-and-information-sciences",
    "label": "Computer and Information Sciences",
    "children": [
      "Artificial Intelligence",
      "Computer and Information Sciences, General",
      "Computer and Information Systems Security",
      "Computer Graphics",
      "Computer Networking and Telecommunications",
      "Computer Programming, General",
      "Computer Programming, Specific Applications",
      "Computer Programming, Vendor Certification",
      "Computer Science",
      "Computer Support Specialist",
      "Computer Systems Analysis",
      "Data Entry",
      "Data Processing Technology",
      "Database Management",
      "Informatics",
      "Information Science",
      "Information Technology",
      "Information Technology Project Management",
      "LAN and WAN Management",
      "Modeling, Virtual Environments and Simulation",
      "Network and System Administration",
      "Web Development",
      "Web Management",
      "Word Processing"
    ]
  },
  "engineering": {
    "id": "engineering",
    "label": "Engineering",
    "children": [
      "Aerospace Engineering",
      "Agricultural Engineering",
      "Architectural Engineering",
      "Biochemical Engineering",
      "Biological/Biosystems Engineering",
      "Biomedical Engineering",
      "Ceramic Sciences and Engineering",
      "Chemical and Biomolecular Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Geotechnical and Geo-Environmental Engineering",
      "Structural Engineering",
      "Transportation and Highway Engineering",
      "Water Resources Engineering",
      "Computer Engineering, General",
      "Computer Hardware Engineering",
      "Computer Software Engineering",
      "Construction Engineering",
      "Electrical Engineering",
      "Laser and Optical Engineering",
      "Telecommunications Engineering",
      "Electromechanical Engineering",
      "Engineering Chemistry",
      "Engineering, General",
      "Engineering Mechanics",
      "Engineering Physics",
      "Engineering Science",
      "Environmental Engineering",
      "Forest Engineering",
      "Geological Engineering",
      "Industrial Engineering",
      "Manufacturing Engineering",
      "Marine Engineering and Naval Architecture",
      "Materials Engineering",
      "Mechanical Engineering",
      "Mechatronics, Robotics, and Automation Engineering",
      "Metallurgical Engineering",
      "Mining and Mineral Engineering",
      "Nuclear Engineering",
      "Ocean Engineering",
      "Operations Research",
      "Paper Science and Engineering",
      "Petroleum Engineering",
      "Polymer and Plastics Engineering",
      "Pre-engineering",
      "Surveying Engineering",
      "Systems Engineering",
      "Textile Sciences and Engineering"
    ]
  },
  "engineering-technologies": {
    "id": "engineering-technologies",
    "label": "Engineering Technologies",
    "children": [
      "Aerospace Engineering Technology",
      "Architectural Engineering Technology",
      "Automation Engineer Technology",
      "Automotive Engineering Technology",
      "Biomedical Technology",
      "Civil Engineering Technology",
      "Computer Engineering Technology",
      "Computer Hardware Technology",
      "Computer Software Technology",
      "Computer Systems Technology",
      "Construction Technology",
      "Architectural Drafting",
      "Civil Drafting and Civil Engineering",
      "Computer-Aided Drafting and Design",
      "Drafting and Design Technology",
      "Electrical and Electronics Drafting",
      "Mechanical Drafting",
      "Electrical Engineering Technology",
      "Electromechanical Technology",
      "Engineering and Industrial Management",
      "Engineering Design",
      "Engineering Technology",
      "Energy Systems",
      "Environmental Engineering Technology",
      "Hazardous Materials Management and Waste Technology",
      "Heating, Air Conditioning, and Refrigeration Technology",
      "Solar Energy Technology",
      "Water Quality and Wastewater Treatment",
      "GIS Technology",
      "Hazardous Materials Information Systems Technology",
      "Hydraulics and Fluid Power Technology",
      "Chemical Engineering Technology",
      "Industrial Technology",
      "Manufacturing Engineering Technology",
      "Metallurgical Technology",
      "Plastics Engineering Technology",
      "Semiconductor Manufacturing Technology",
      "Welding Engineering Technology",
      "Industrial Safety Technology",
      "Instrumentation Technology",
      "Integrated Circuit Design",
      "Laser and Optical Technology",
      "Mechanical Engineering Technology",
      "Mining Technology",
      "Nanotechnology",
      "Nuclear Engineering Technology",
      "Occupational Safety and Health Technology",
      "Packaging Science",
      "Petroleum Technology",
      "Quality Control Technology",
      "Robotics Technology",
      "Surveying",
      "Telecommunications Technology"
    ]
  },
  "math-and-statistics": {
    "id": "math-and-statistics",
    "label": "Math and Statistics",
    "children": [
      "Algebra and Number Theory",
      "Analysis and Functional Analysis",
      "Applied Mathematics",
      "Computational Mathematics",
      "Financial Mathematics",
      "Geometry",
      "Mathematical Statistics and Probability",
      "Mathematics",
      "Mathematics and Statistics",
      "Statistics"
    ]
  },
  "natural-resources-and-conservation": {
    "id": "natural-resources-and-conservation",
    "label": "Natural Resources and Conservation",
    "children": [
      "Environmental Science",
      "Environmental Studies",
      "Fishing and Fisheries",
      "Forest Management",
      "Forest Resources Production",
      "Forest Sciences and Biology",
      "Forest Technology",
      "Forestry",
      "Land Use Planning",
      "Natural Resource Economics",
      "Natural Resource Recreation and Tourism",
      "Natural Resources and Conservation",
      "Natural Resources Law Enforcement and Protective Services",
      "Natural Resources Management and Policy",
      "Urban Forestry",
      "Water, Wetlands, and Marine Resources Management",
      "Wildlife, Fish, and Wildlands Science and Management",
      "Wood Science and Wood Products Technology"
    ]
  },
  "physical-sciences": {
    "id": "physical-sciences",
    "label": "Physical Sciences",
    "children": [
      "Astronomy",
      "Astrophysics",
      "Atmospheric Chemistry and Climatology",
      "Atmospheric Physics and Dynamics",
      "Atmospheric Sciences and Meteorology",
      "Analytical Chemistry",
      "Chemical Physics",
      "Chemistry",
      "Environmental Chemistry",
      "Forensic Chemistry",
      "Inorganic Chemistry",
      "Organic Chemistry",
      "Physical Chemistry",
      "Polymer Chemistry",
      "Theoretical Chemistry",
      "Chemical and Physical Oceanography",
      "Geochemistry",
      "Geology",
      "Geophysics and Seismology",
      "Hydrology and Water Resources Science",
      "Paleontology",
      "Materials Chemistry",
      "Materials Science",
      "Meteorology",
      "Physical Sciences",
      "Acoustics",
      "Applied Physics",
      "Atomic and Molecular Physics",
      "Elementary Particle Physics",
      "Nuclear Physics",
      "Optics",
      "Physics",
      "Theoretical and Mathematical Physics",
      "Planetary Astronomy and Science"
    ]
  },
  "science-technologies": {
    "id": "science-technologies",
    "label": "Science Technologies",
    "children": [
      "Biology and Biotechnology Laboratory Technology",
      "Chemical Technology",
      "Industrial Radiologic Technology",
      "Nuclear Technology",
      "Science Technology"
    ]
  },
  "communication-and-journalism": {
    "id": "communication-and-journalism",
    "label": "Communication and Journalism",
    "children": [
      "Advertising",
      "Broadcast Journalism",
      "Communication and Rhetoric",
      "Communication, General",
      "Digital Communications and Multimedia",
      "Health Communication",
      "International and Intercultural Communication",
      "Journalism",
      "Mass Communications",
      "Organizational Communication",
      "Photojournalism",
      "Political Communication",
      "Public Relations",
      "Public Relations, Advertising, and Applied Communication",
      "Publishing",
      "Radio and Television",
      "Sports Communication",
      "Technical and Scientific Communication"
    ]
  },
  "education": {
    "id": "education",
    "label": "Education",
    "children": [
      "Adult Literacy Instructor",
      "American Indian Education",
      "Bilingual Education",
      "College Student Counseling and Personnel Services",
      "Counselor Education",
      "Curriculum and Instruction",
      "Education",
      "Adult and Continuing Education Administration",
      "Educational Administration",
      "Educational, Instructional, and Curriculum Supervision",
      "Elementary and Middle School Administration",
      "High School Administration",
      "Higher Education Administration",
      "Urban Education and Leadership",
      "Adult and Continuing Education",
      "Early Childhood Education",
      "Elementary School Teaching",
      "High School Teaching",
      "Kindergarten and Preschool Education",
      "Middle School Teaching",
      "Montessori Teacher Education",
      "Teacher Education, Multiple Levels",
      "Waldorf/Steiner Teacher Education",
      "Agricultural Teacher Education",
      "Art Teacher Education",
      "Biology Teacher Education",
      "Business Teacher Education",
      "Chemistry Teacher Education",
      "Computer Teacher Education",
      "Drama and Dance Teacher Education",
      "Driver and Safety Teacher Education",
      "Earth Science Teacher Education",
      "Environmental Education",
      "Family and Consumer Sciences Education",
      "Foreign Language Teacher Education",
      "French Teacher Education",
      "Geography Teacher Education",
      "German Teacher Education",
      "Health Occupations Teacher Education",
      "Health Teacher Education",
      "History Teacher Education",
      "Language Arts Teacher Education",
      "Latin Teacher Education",
      "Mathematics Teacher Education",
      "Music Teacher Education",
      "Physical Education Teaching and Coaching",
      "Physics Teacher Education",
      "Psychology Teacher Education",
      "Reading Teacher Education",
      "Sales and Marketing Education",
      "School Librarianship",
      "Science Teacher Education",
      "Social Science Teacher Education",
      "Social Studies Teacher Education",
      "Spanish Teacher Education",
      "Speech Teacher Education",
      "Technology and Industrial Arts Education",
      "Trade and Industrial Teacher Education",
      "Vocational-Technical Education",
      "Educational Assessment, Testing, and Measurement",
      "Educational Evaluation and Research",
      "Educational Statistics and Research Methods",
      "Instructional Technology",
      "International and Comparative Education",
      "Learning Sciences",
      "Multicultural Education",
      "Social and Philosophical Foundations of Education",
      "Early Childhood Special Education",
      "Education of Developmentally Delayed Individuals",
      "Education of Individuals in Elementary Special Education Programs",
      "Education of Individuals in Middle School Special Education Programs",
      "Education of Individuals in Secondary Special Education Programs",
      "Education of Individuals With Autism",
      "Education of Individuals With Multiple Disabilities",
      "Education of Individuals With Traumatic Brain Injuries",
      "Education of Individuals With Vision Impairments",
      "Education of Mentally Handicapped",
      "Education of the Deaf and Hearing Impaired",
      "Education of the Emotionally Handicapped",
      "Education of the Gifted and Talented",
      "Education of the Learning Disabled",
      "Education of the Physically Handicapped",
      "Education of the Speech Impaired",
      "Special Education",
      "Teacher Assistant",
      "Teaching English as a Second Language (ESL)",
      "Teaching French as a Second or Foreign Language"
    ]
  },
  "history": {
    "id": "history",
    "label": "History",
    "children": [
      "Asian History",
      "Canadian History",
      "European History",
      "History",
      "History and Philosophy of Science and Technology",
      "Public History",
      "U.S. History"
    ]
  },
  "library-science": {
    "id": "library-science",
    "label": "Library Science",
    "children": [
      "Archival Administration",
      "Children and Youth Library Services",
      "Library and Archives Assisting",
      "Library and Information Science"
    ]
  },
  "psychology": {
    "id": "psychology",
    "label": "Psychology",
    "children": [
      "Applied Behavior Analysis",
      "Applied Psychology",
      "Clinical Child Psychology",
      "Clinical Psychology",
      "Cognitive Psychology and Psycholinguistics",
      "Community Psychology",
      "Comparative Psychology",
      "Counseling Psychology",
      "Developmental Psychology",
      "Educational Psychology",
      "Environmental Psychology",
      "Experimental Psychology",
      "Family Psychology",
      "Forensic Psychology",
      "Geropsychology",
      "Health/Medical Psychology",
      "Industrial and Organizational Psychology",
      "Psychobiology",
      "Psychology",
      "Psychometrics and Quantitative Psychology",
      "School Psychology",
      "Social Psychology"
    ]
  },
  "social-sciences": {
    "id": "social-sciences",
    "label": "Social Sciences",
    "children": [
      "Anthropology",
      "Cultural Anthropology",
      "Medical Anthropology",
      "Physical Anthropology",
      "Applied Economics",
      "Archaeology",
      "Cartography",
      "Criminology",
      "Demography and Population Studies",
      "Development Economics and International Development",
      "Econometrics and Quantitative Economics",
      "Economics",
      "Geography",
      "International Economics",
      "International Relations",
      "National Security Studies",
      "Canadian Government and Politics",
      "Political Economy",
      "Political Science and Government",
      "United States Government and Politics",
      "Research Methodology and Quantitative Methods",
      "Rural Sociology",
      "Social Sciences",
      "Sociology",
      "Sociology and Anthropology",
      "Urban Studies"
    ]
  },
  "construction-trades": {
    "id": "construction-trades",
    "label": "Construction Trades",
    "children": [
      "Building and Property Maintenance",
      "Building Construction Technology",
      "Carpentry",
      "Carpet, Floor, and Tile Worker",
      "Concrete Finishing",
      "Construction Inspection",
      "Construction Site Management",
      "Construction Trades, General",
      "Drywall Installation",
      "Electrical and Power Transmission Installation",
      "Electrician",
      "Glazing",
      "Insulator",
      "Lineworking",
      "Masonry",
      "Metal Building Assembly",
      "Painting and Wallpapering",
      "Pipefitting",
      "Plumbing Technology",
      "Roofing",
      "Well Drilling"
    ]
  },
  "mechanic-and-repair-technologies": {
    "id": "mechanic-and-repair-technologies",
    "label": "Mechanic and Repair Technologies",
    "children": [
      "Appliance Installation and Repair Technology",
      "Business Machine Repair",
      "Communications Systems Technology",
      "Computer Installation and Repair Technology",
      "Electronics Technology",
      "Industrial Electronics Technology",
      "Security System Technology",
      "Gunsmithing",
      "Heating, Ventilation, Air-Conditioning, and Refrigeration Technology",
      "Heavy Equipment Maintenance Technology",
      "Industrial Maintenance Technology",
      "Locksmithing and Safe Repair",
      "Mechanics and Repairers, General",
      "Musical Instrument Fabrication and Repair",
      "Aircraft Maintenance",
      "Aircraft Powerplant Technology",
      "Alternative Fuel Vehicle Technology",
      "Automotive Technology",
      "Automotive-Body Technology",
      "Avionics Maintenance Technology",
      "Diesel Mechanics Technology",
      "Engine Machinist",
      "High Performance and Custom Engine Technology",
      "Marine Maintenance and Ship Repair",
      "Medium-to-Heavy Vehicle and Truck Technology",
      "Motorcycle Maintenance and Repair Technology",
      "Recreation Vehicle (RV) Service Technology",
      "Small Engine Mechanics and Repair Technology",
      "Vehicle Emissions Technology",
      "Vehicle Maintenance and Repair Technologies, General",
      "Warehousing Operations and Maintenance Technology",
      "Watchmaking and Jewelrymaking"
    ]
  },
  "personal-and-culinary-services": {
    "id": "personal-and-culinary-services",
    "label": "Personal and Culinary Services",
    "children": [
      "Barbering",
      "Cosmetology",
      "Cosmetology Education",
      "Electrolysis",
      "Facial Treatment",
      "Hair Design",
      "Make-Up",
      "Master Aesthetician",
      "Nail Technician",
      "Permanent Cosmetics and Tattooing",
      "Salon Management",
      "Skin Care",
      "Baking and Pastry Arts",
      "Bartending",
      "Chef Training",
      "Culinary Arts",
      "Culinary Science",
      "Food Preparation",
      "Food Service",
      "Institutional Food Service",
      "Meat Cutting",
      "Restaurant and Culinary Management",
      "Wine Steward",
      "Funeral Direction",
      "Funeral Service and Mortuary Science",
      "Mortuary Science and Embalming",
      "Personal and Culinary Services, General"
    ]
  },
  "precision-production-trades": {
    "id": "precision-production-trades",
    "label": "Precision Production Trades",
    "children": [
      "Boilermaking",
      "Cabinetmaking and Millwork",
      "Computer Numerically Controlled (CNC) Machinist Technology",
      "Furniture Design and Manufacturing",
      "Ironworking",
      "Machine Shop Technology",
      "Machine Tool Technology",
      "Metal Fabricator",
      "Precision Production Trades, General",
      "Sheet Metal Technology",
      "Shoe, Boot, and Leather Repair",
      "Tool and Die Technology",
      "Upholstery",
      "Welding",
      "Woodworking"
    ]
  },
  "transportation-and-materials-moving": {
    "id": "transportation-and-materials-moving",
    "label": "Transportation and Materials Moving",
    "children": [
      "Air Traffic Control",
      "Air Transportation",
      "Aviation Management",
      "Commercial Fishing",
      "Construction Equipment Operation",
      "Flagging and Traffic Control",
      "Flight Attendance",
      "Flight Instruction",
      "Merchant Marine Science",
      "Pilot and Flight Crew",
      "Professional Diving and Instruction",
      "Railroad and Railway Transportation",
      "Transportation and Materials Moving, General",
      "Truck and Bus Driving"
    ]
  }
}


String.prototype.capitalizeAll = function() {
	let arr = this.split(" ");

	let toRet = "";
	for (var i in arr) {
		if (i > 0) {
			toRet += " ";
		}
		toRet += arr[i].capitalize();
	}
	return toRet;
};

String.prototype.capitalize = function() {
	return this.charAt(0).toUpperCase() + this.slice(1);
};

sql = "insert into wp_career_fair.ref_major (val, category) VALUES \n";
for (var i in obj) {
	let o = obj[i];
	let id = o.id;
	let label = o.label;
  let children = o.children;
  let inserted = [];
	for (var k in children) {
    let c = children[k];
    if(inserted.indexOf(c)>=0){
      continue;
    }
    sql += ` ("${c.capitalizeAll()}", "${id}"), \n` ;
    inserted.push(c);
  }
}

console.log(sql);